// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module int4_decoder_token_controller_int4_broadcast_activation (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        quantized_address0,
        quantized_ce0,
        quantized_we0,
        quantized_d0,
        quantized_q0,
        packed_scales_address0,
        packed_scales_ce0,
        packed_scales_we0,
        packed_scales_d0,
        packed_scales_q0,
        quantized_stream_dout,
        quantized_stream_num_data_valid,
        quantized_stream_fifo_cap,
        quantized_stream_empty_n,
        quantized_stream_read,
        scale_stream_dout,
        scale_stream_num_data_valid,
        scale_stream_fifo_cap,
        scale_stream_empty_n,
        scale_stream_read,
        stream_activation,
        quantized_pe0_din,
        quantized_pe0_num_data_valid,
        quantized_pe0_fifo_cap,
        quantized_pe0_full_n,
        quantized_pe0_write,
        quantized_pe1_din,
        quantized_pe1_num_data_valid,
        quantized_pe1_fifo_cap,
        quantized_pe1_full_n,
        quantized_pe1_write,
        quantized_pe2_din,
        quantized_pe2_num_data_valid,
        quantized_pe2_fifo_cap,
        quantized_pe2_full_n,
        quantized_pe2_write,
        quantized_pe3_din,
        quantized_pe3_num_data_valid,
        quantized_pe3_fifo_cap,
        quantized_pe3_full_n,
        quantized_pe3_write,
        activation_scale_pe0_din,
        activation_scale_pe0_num_data_valid,
        activation_scale_pe0_fifo_cap,
        activation_scale_pe0_full_n,
        activation_scale_pe0_write,
        activation_scale_pe1_din,
        activation_scale_pe1_num_data_valid,
        activation_scale_pe1_fifo_cap,
        activation_scale_pe1_full_n,
        activation_scale_pe1_write,
        activation_scale_pe2_din,
        activation_scale_pe2_num_data_valid,
        activation_scale_pe2_fifo_cap,
        activation_scale_pe2_full_n,
        activation_scale_pe2_write,
        activation_scale_pe3_din,
        activation_scale_pe3_num_data_valid,
        activation_scale_pe3_fifo_cap,
        activation_scale_pe3_full_n,
        activation_scale_pe3_write,
        local_tiles_0,
        local_tiles_1,
        local_tiles_2,
        local_tiles_3,
        input_tiles
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [8:0] quantized_address0;
output   quantized_ce0;
output   quantized_we0;
output  [479:0] quantized_d0;
input  [479:0] quantized_q0;
output  [4:0] packed_scales_address0;
output   packed_scales_ce0;
output   packed_scales_we0;
output  [511:0] packed_scales_d0;
input  [511:0] packed_scales_q0;
input  [479:0] quantized_stream_dout;
input  [2:0] quantized_stream_num_data_valid;
input  [2:0] quantized_stream_fifo_cap;
input   quantized_stream_empty_n;
output   quantized_stream_read;
input  [31:0] scale_stream_dout;
input  [2:0] scale_stream_num_data_valid;
input  [2:0] scale_stream_fifo_cap;
input   scale_stream_empty_n;
output   scale_stream_read;
input  [0:0] stream_activation;
output  [479:0] quantized_pe0_din;
input  [2:0] quantized_pe0_num_data_valid;
input  [2:0] quantized_pe0_fifo_cap;
input   quantized_pe0_full_n;
output   quantized_pe0_write;
output  [479:0] quantized_pe1_din;
input  [2:0] quantized_pe1_num_data_valid;
input  [2:0] quantized_pe1_fifo_cap;
input   quantized_pe1_full_n;
output   quantized_pe1_write;
output  [479:0] quantized_pe2_din;
input  [2:0] quantized_pe2_num_data_valid;
input  [2:0] quantized_pe2_fifo_cap;
input   quantized_pe2_full_n;
output   quantized_pe2_write;
output  [479:0] quantized_pe3_din;
input  [2:0] quantized_pe3_num_data_valid;
input  [2:0] quantized_pe3_fifo_cap;
input   quantized_pe3_full_n;
output   quantized_pe3_write;
output  [31:0] activation_scale_pe0_din;
input  [2:0] activation_scale_pe0_num_data_valid;
input  [2:0] activation_scale_pe0_fifo_cap;
input   activation_scale_pe0_full_n;
output   activation_scale_pe0_write;
output  [31:0] activation_scale_pe1_din;
input  [2:0] activation_scale_pe1_num_data_valid;
input  [2:0] activation_scale_pe1_fifo_cap;
input   activation_scale_pe1_full_n;
output   activation_scale_pe1_write;
output  [31:0] activation_scale_pe2_din;
input  [2:0] activation_scale_pe2_num_data_valid;
input  [2:0] activation_scale_pe2_fifo_cap;
input   activation_scale_pe2_full_n;
output   activation_scale_pe2_write;
output  [31:0] activation_scale_pe3_din;
input  [2:0] activation_scale_pe3_num_data_valid;
input  [2:0] activation_scale_pe3_fifo_cap;
input   activation_scale_pe3_full_n;
output   activation_scale_pe3_write;
input  [5:0] local_tiles_0;
input  [5:0] local_tiles_1;
input  [5:0] local_tiles_2;
input  [5:0] local_tiles_3;
input  [5:0] input_tiles;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[4:0] packed_scales_address0;
reg packed_scales_ce0;
reg packed_scales_we0;
reg[511:0] packed_scales_d0;
reg quantized_stream_read;
reg scale_stream_read;
reg quantized_pe0_write;
reg quantized_pe1_write;
reg quantized_pe2_write;
reg quantized_pe3_write;
reg activation_scale_pe0_write;
reg activation_scale_pe1_write;
reg activation_scale_pe2_write;
reg activation_scale_pe3_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [0:0] trunc_ln282_fu_176_p1;
reg   [0:0] trunc_ln282_reg_266;
wire   [0:0] active_0_fu_180_p2;
reg   [0:0] active_0_reg_271;
wire   [0:0] active_1_fu_186_p2;
reg   [0:0] active_1_reg_276;
wire   [0:0] active_2_fu_192_p2;
reg   [0:0] active_2_reg_281;
wire   [0:0] active_3_fu_198_p2;
reg   [0:0] active_3_reg_286;
wire   [8:0] shl_ln_fu_204_p3;
reg   [8:0] shl_ln_reg_291;
wire    ap_CS_fsm_state2;
wire   [0:0] and_ln345_fu_212_p2;
reg   [0:0] and_ln345_reg_296;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_start;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_done;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_idle;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_ready;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_stream_read;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_scale_stream_read;
wire   [479:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe0_din;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe0_write;
wire   [31:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe0_din;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe0_write;
wire   [479:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe1_din;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe1_write;
wire   [31:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe1_din;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe1_write;
wire   [479:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe2_din;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe2_write;
wire   [31:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe2_din;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe2_write;
wire   [479:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe3_din;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe3_write;
wire   [31:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe3_din;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe3_write;
wire   [8:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_address0;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_ce0;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_we0;
wire   [479:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_d0;
wire   [4:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_address0;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_ce0;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_we0;
wire   [511:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_d0;
wire   [511:0] grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_streamed_scale_word_out;
wire    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_streamed_scale_word_out_ap_vld;
reg    grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln348_fu_243_p1;
wire    ap_CS_fsm_state4;
wire   [511:0] streamed_scale_word_fu_229_p1;
wire   [255:0] streamed_scale_word_2_fu_219_p4;
wire   [4:0] lshr_ln_fu_234_p4;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_start_reg = 1'b0;
end

int4_decoder_token_controller_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_start),
    .ap_done(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_done),
    .ap_idle(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_idle),
    .ap_ready(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_ready),
    .quantized_stream_dout(quantized_stream_dout),
    .quantized_stream_num_data_valid(3'd0),
    .quantized_stream_fifo_cap(3'd0),
    .quantized_stream_empty_n(quantized_stream_empty_n),
    .quantized_stream_read(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_stream_read),
    .scale_stream_dout(scale_stream_dout),
    .scale_stream_num_data_valid(3'd0),
    .scale_stream_fifo_cap(3'd0),
    .scale_stream_empty_n(scale_stream_empty_n),
    .scale_stream_read(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_scale_stream_read),
    .quantized_pe0_din(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe0_din),
    .quantized_pe0_num_data_valid(3'd0),
    .quantized_pe0_fifo_cap(3'd0),
    .quantized_pe0_full_n(quantized_pe0_full_n),
    .quantized_pe0_write(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe0_write),
    .activation_scale_pe0_din(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe0_din),
    .activation_scale_pe0_num_data_valid(3'd0),
    .activation_scale_pe0_fifo_cap(3'd0),
    .activation_scale_pe0_full_n(activation_scale_pe0_full_n),
    .activation_scale_pe0_write(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe0_write),
    .quantized_pe1_din(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe1_din),
    .quantized_pe1_num_data_valid(3'd0),
    .quantized_pe1_fifo_cap(3'd0),
    .quantized_pe1_full_n(quantized_pe1_full_n),
    .quantized_pe1_write(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe1_write),
    .activation_scale_pe1_din(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe1_din),
    .activation_scale_pe1_num_data_valid(3'd0),
    .activation_scale_pe1_fifo_cap(3'd0),
    .activation_scale_pe1_full_n(activation_scale_pe1_full_n),
    .activation_scale_pe1_write(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe1_write),
    .quantized_pe2_din(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe2_din),
    .quantized_pe2_num_data_valid(3'd0),
    .quantized_pe2_fifo_cap(3'd0),
    .quantized_pe2_full_n(quantized_pe2_full_n),
    .quantized_pe2_write(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe2_write),
    .activation_scale_pe2_din(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe2_din),
    .activation_scale_pe2_num_data_valid(3'd0),
    .activation_scale_pe2_fifo_cap(3'd0),
    .activation_scale_pe2_full_n(activation_scale_pe2_full_n),
    .activation_scale_pe2_write(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe2_write),
    .quantized_pe3_din(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe3_din),
    .quantized_pe3_num_data_valid(3'd0),
    .quantized_pe3_fifo_cap(3'd0),
    .quantized_pe3_full_n(quantized_pe3_full_n),
    .quantized_pe3_write(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe3_write),
    .activation_scale_pe3_din(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe3_din),
    .activation_scale_pe3_num_data_valid(3'd0),
    .activation_scale_pe3_fifo_cap(3'd0),
    .activation_scale_pe3_full_n(activation_scale_pe3_full_n),
    .activation_scale_pe3_write(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe3_write),
    .shl_ln(shl_ln_reg_291),
    .active_3(active_3_reg_286),
    .active_2(active_2_reg_281),
    .active_1(active_1_reg_276),
    .active_0(active_0_reg_271),
    .quantized_address0(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_address0),
    .quantized_ce0(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_ce0),
    .quantized_we0(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_we0),
    .quantized_d0(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_d0),
    .quantized_q0(quantized_q0),
    .stream_activation(stream_activation),
    .packed_scales_address0(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_address0),
    .packed_scales_ce0(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_ce0),
    .packed_scales_we0(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_we0),
    .packed_scales_d0(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_d0),
    .packed_scales_q0(packed_scales_q0),
    .streamed_scale_word_out(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_streamed_scale_word_out),
    .streamed_scale_word_out_ap_vld(grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_streamed_scale_word_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_start_reg <= 1'b1;
        end else if ((grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_ready == 1'b1)) begin
            grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        active_0_reg_271 <= active_0_fu_180_p2;
        active_1_reg_276 <= active_1_fu_186_p2;
        active_2_reg_281 <= active_2_fu_192_p2;
        active_3_reg_286 <= active_3_fu_198_p2;
        trunc_ln282_reg_266 <= trunc_ln282_fu_176_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        and_ln345_reg_296 <= and_ln345_fu_212_p2;
        shl_ln_reg_291[8 : 3] <= shl_ln_fu_204_p3[8 : 3];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        activation_scale_pe0_write = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe0_write;
    end else begin
        activation_scale_pe0_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        activation_scale_pe1_write = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe1_write;
    end else begin
        activation_scale_pe1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        activation_scale_pe2_write = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe2_write;
    end else begin
        activation_scale_pe2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        activation_scale_pe3_write = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe3_write;
    end else begin
        activation_scale_pe3_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        packed_scales_address0 = zext_ln348_fu_243_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        packed_scales_address0 = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_address0;
    end else begin
        packed_scales_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        packed_scales_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        packed_scales_ce0 = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_ce0;
    end else begin
        packed_scales_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        packed_scales_d0 = streamed_scale_word_fu_229_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        packed_scales_d0 = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_d0;
    end else begin
        packed_scales_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln345_reg_296) & (1'b1 == ap_CS_fsm_state4))) begin
        packed_scales_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        packed_scales_we0 = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_packed_scales_we0;
    end else begin
        packed_scales_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        quantized_pe0_write = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe0_write;
    end else begin
        quantized_pe0_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        quantized_pe1_write = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe1_write;
    end else begin
        quantized_pe1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        quantized_pe2_write = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe2_write;
    end else begin
        quantized_pe2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        quantized_pe3_write = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe3_write;
    end else begin
        quantized_pe3_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        quantized_stream_read = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_stream_read;
    end else begin
        quantized_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        scale_stream_read = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_scale_stream_read;
    end else begin
        scale_stream_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign activation_scale_pe0_din = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe0_din;

assign activation_scale_pe1_din = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe1_din;

assign activation_scale_pe2_din = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe2_din;

assign activation_scale_pe3_din = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_activation_scale_pe3_din;

assign active_0_fu_180_p2 = ((local_tiles_0 == 6'd0) ? 1'b1 : 1'b0);

assign active_1_fu_186_p2 = ((local_tiles_1 == 6'd0) ? 1'b1 : 1'b0);

assign active_2_fu_192_p2 = ((local_tiles_2 == 6'd0) ? 1'b1 : 1'b0);

assign active_3_fu_198_p2 = ((local_tiles_3 == 6'd0) ? 1'b1 : 1'b0);

assign and_ln345_fu_212_p2 = (trunc_ln282_reg_266 & stream_activation);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_start = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_ap_start_reg;

assign lshr_ln_fu_234_p4 = {{input_tiles[5:1]}};

assign quantized_address0 = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_address0;

assign quantized_ce0 = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_ce0;

assign quantized_d0 = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_d0;

assign quantized_pe0_din = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe0_din;

assign quantized_pe1_din = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe1_din;

assign quantized_pe2_din = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe2_din;

assign quantized_pe3_din = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_pe3_din;

assign quantized_we0 = grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_quantized_we0;

assign shl_ln_fu_204_p3 = {{input_tiles}, {3'd0}};

assign streamed_scale_word_2_fu_219_p4 = {{grp_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop_fu_141_streamed_scale_word_out[511:256]}};

assign streamed_scale_word_fu_229_p1 = streamed_scale_word_2_fu_219_p4;

assign trunc_ln282_fu_176_p1 = input_tiles[0:0];

assign zext_ln348_fu_243_p1 = lshr_ln_fu_234_p4;

always @ (posedge ap_clk) begin
    shl_ln_reg_291[2:0] <= 3'b000;
end

endmodule //int4_decoder_token_controller_int4_broadcast_activation
