// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module int4_decoder_token_controller_swiftkv_quantize_kv_record_Pipeline_quantize_kv_group_block_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v_raw_3433,
        v_raw_3841,
        v_raw_4249,
        v_raw_4657,
        v_raw_5063,
        v_raw_5471,
        v_raw_5879,
        v_raw_6287,
        conv3_i12_i_i,
        sh_prom_i_i,
        k_raw_3432,
        k_raw_3840,
        k_raw_4248,
        k_raw_4656,
        k_raw_5062,
        k_raw_5470,
        k_raw_5878,
        k_raw_6286,
        conv3_i12_i_i313,
        sh_prom_i_i328,
        v_raw_3331,
        v_raw_3739,
        v_raw_4147,
        v_raw_4555,
        v_raw_4961,
        v_raw_5369,
        v_raw_5777,
        v_raw_6185,
        k_raw_3330,
        k_raw_3738,
        k_raw_4146,
        k_raw_4554,
        k_raw_4960,
        k_raw_5368,
        k_raw_5776,
        k_raw_6184,
        v_raw_3229,
        v_raw_3637,
        v_raw_4045,
        v_raw_4453,
        v_raw_4859,
        v_raw_5267,
        v_raw_5675,
        v_raw_6083,
        k_raw_3228,
        k_raw_3636,
        k_raw_4044,
        k_raw_4452,
        k_raw_4858,
        k_raw_5266,
        k_raw_5674,
        k_raw_6082,
        empty_609,
        v_raw_3535,
        v_raw_3943,
        v_raw_4351,
        empty_610,
        v_raw_5165,
        v_raw_5573,
        v_raw_5981,
        empty_611,
        k_raw_3534,
        k_raw_3942,
        k_raw_4350,
        empty,
        k_raw_5164,
        k_raw_5572,
        k_raw_5980,
        quantized_k_group_31_out,
        quantized_k_group_31_out_ap_vld,
        quantized_k_group_30_out,
        quantized_k_group_30_out_ap_vld,
        quantized_k_group_29_out,
        quantized_k_group_29_out_ap_vld,
        quantized_k_group_28_out,
        quantized_k_group_28_out_ap_vld,
        quantized_k_group_27_out,
        quantized_k_group_27_out_ap_vld,
        quantized_k_group_26_out,
        quantized_k_group_26_out_ap_vld,
        quantized_k_group_25_out,
        quantized_k_group_25_out_ap_vld,
        quantized_k_group_24_out,
        quantized_k_group_24_out_ap_vld,
        quantized_k_group_23_out,
        quantized_k_group_23_out_ap_vld,
        quantized_k_group_22_out,
        quantized_k_group_22_out_ap_vld,
        quantized_k_group_21_out,
        quantized_k_group_21_out_ap_vld,
        quantized_k_group_20_out,
        quantized_k_group_20_out_ap_vld,
        quantized_k_group_19_out,
        quantized_k_group_19_out_ap_vld,
        quantized_k_group_18_out,
        quantized_k_group_18_out_ap_vld,
        quantized_k_group_17_out,
        quantized_k_group_17_out_ap_vld,
        quantized_k_group_16_out,
        quantized_k_group_16_out_ap_vld,
        quantized_k_group_15_out,
        quantized_k_group_15_out_ap_vld,
        quantized_k_group_14_out,
        quantized_k_group_14_out_ap_vld,
        quantized_k_group_13_out,
        quantized_k_group_13_out_ap_vld,
        quantized_k_group_12_out,
        quantized_k_group_12_out_ap_vld,
        quantized_k_group_11_out,
        quantized_k_group_11_out_ap_vld,
        quantized_k_group_10_out,
        quantized_k_group_10_out_ap_vld,
        quantized_k_group_9_out,
        quantized_k_group_9_out_ap_vld,
        quantized_k_group_8_out,
        quantized_k_group_8_out_ap_vld,
        quantized_k_group_7_out,
        quantized_k_group_7_out_ap_vld,
        quantized_k_group_6_out,
        quantized_k_group_6_out_ap_vld,
        quantized_k_group_5_out,
        quantized_k_group_5_out_ap_vld,
        quantized_k_group_4_out,
        quantized_k_group_4_out_ap_vld,
        quantized_k_group_3_out,
        quantized_k_group_3_out_ap_vld,
        quantized_k_group_2_out,
        quantized_k_group_2_out_ap_vld,
        quantized_k_group_1_out,
        quantized_k_group_1_out_ap_vld,
        quantized_k_group_out,
        quantized_k_group_out_ap_vld,
        quantized_v_group_31_out,
        quantized_v_group_31_out_ap_vld,
        quantized_v_group_30_out,
        quantized_v_group_30_out_ap_vld,
        quantized_v_group_29_out,
        quantized_v_group_29_out_ap_vld,
        quantized_v_group_28_out,
        quantized_v_group_28_out_ap_vld,
        quantized_v_group_27_out,
        quantized_v_group_27_out_ap_vld,
        quantized_v_group_26_out,
        quantized_v_group_26_out_ap_vld,
        quantized_v_group_25_out,
        quantized_v_group_25_out_ap_vld,
        quantized_v_group_24_out,
        quantized_v_group_24_out_ap_vld,
        quantized_v_group_23_out,
        quantized_v_group_23_out_ap_vld,
        quantized_v_group_22_out,
        quantized_v_group_22_out_ap_vld,
        quantized_v_group_21_out,
        quantized_v_group_21_out_ap_vld,
        quantized_v_group_20_out,
        quantized_v_group_20_out_ap_vld,
        quantized_v_group_19_out,
        quantized_v_group_19_out_ap_vld,
        quantized_v_group_18_out,
        quantized_v_group_18_out_ap_vld,
        quantized_v_group_17_out,
        quantized_v_group_17_out_ap_vld,
        quantized_v_group_16_out,
        quantized_v_group_16_out_ap_vld,
        quantized_v_group_15_out,
        quantized_v_group_15_out_ap_vld,
        quantized_v_group_14_out,
        quantized_v_group_14_out_ap_vld,
        quantized_v_group_13_out,
        quantized_v_group_13_out_ap_vld,
        quantized_v_group_12_out,
        quantized_v_group_12_out_ap_vld,
        quantized_v_group_11_out,
        quantized_v_group_11_out_ap_vld,
        quantized_v_group_10_out,
        quantized_v_group_10_out_ap_vld,
        quantized_v_group_9_out,
        quantized_v_group_9_out_ap_vld,
        quantized_v_group_8_out,
        quantized_v_group_8_out_ap_vld,
        quantized_v_group_7_out,
        quantized_v_group_7_out_ap_vld,
        quantized_v_group_6_out,
        quantized_v_group_6_out_ap_vld,
        quantized_v_group_5_out,
        quantized_v_group_5_out_ap_vld,
        quantized_v_group_4_out,
        quantized_v_group_4_out_ap_vld,
        quantized_v_group_3_out,
        quantized_v_group_3_out_ap_vld,
        quantized_v_group_2_out,
        quantized_v_group_2_out_ap_vld,
        quantized_v_group_1_out,
        quantized_v_group_1_out_ap_vld,
        quantized_v_group_out,
        quantized_v_group_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] v_raw_3433;
input  [31:0] v_raw_3841;
input  [31:0] v_raw_4249;
input  [31:0] v_raw_4657;
input  [31:0] v_raw_5063;
input  [31:0] v_raw_5471;
input  [31:0] v_raw_5879;
input  [31:0] v_raw_6287;
input  [31:0] conv3_i12_i_i;
input  [4:0] sh_prom_i_i;
input  [31:0] k_raw_3432;
input  [31:0] k_raw_3840;
input  [31:0] k_raw_4248;
input  [31:0] k_raw_4656;
input  [31:0] k_raw_5062;
input  [31:0] k_raw_5470;
input  [31:0] k_raw_5878;
input  [31:0] k_raw_6286;
input  [31:0] conv3_i12_i_i313;
input  [4:0] sh_prom_i_i328;
input  [31:0] v_raw_3331;
input  [31:0] v_raw_3739;
input  [31:0] v_raw_4147;
input  [31:0] v_raw_4555;
input  [31:0] v_raw_4961;
input  [31:0] v_raw_5369;
input  [31:0] v_raw_5777;
input  [31:0] v_raw_6185;
input  [31:0] k_raw_3330;
input  [31:0] k_raw_3738;
input  [31:0] k_raw_4146;
input  [31:0] k_raw_4554;
input  [31:0] k_raw_4960;
input  [31:0] k_raw_5368;
input  [31:0] k_raw_5776;
input  [31:0] k_raw_6184;
input  [31:0] v_raw_3229;
input  [31:0] v_raw_3637;
input  [31:0] v_raw_4045;
input  [31:0] v_raw_4453;
input  [31:0] v_raw_4859;
input  [31:0] v_raw_5267;
input  [31:0] v_raw_5675;
input  [31:0] v_raw_6083;
input  [31:0] k_raw_3228;
input  [31:0] k_raw_3636;
input  [31:0] k_raw_4044;
input  [31:0] k_raw_4452;
input  [31:0] k_raw_4858;
input  [31:0] k_raw_5266;
input  [31:0] k_raw_5674;
input  [31:0] k_raw_6082;
input  [31:0] empty_609;
input  [31:0] v_raw_3535;
input  [31:0] v_raw_3943;
input  [31:0] v_raw_4351;
input  [31:0] empty_610;
input  [31:0] v_raw_5165;
input  [31:0] v_raw_5573;
input  [31:0] v_raw_5981;
input  [31:0] empty_611;
input  [31:0] k_raw_3534;
input  [31:0] k_raw_3942;
input  [31:0] k_raw_4350;
input  [31:0] empty;
input  [31:0] k_raw_5164;
input  [31:0] k_raw_5572;
input  [31:0] k_raw_5980;
output  [7:0] quantized_k_group_31_out;
output   quantized_k_group_31_out_ap_vld;
output  [7:0] quantized_k_group_30_out;
output   quantized_k_group_30_out_ap_vld;
output  [7:0] quantized_k_group_29_out;
output   quantized_k_group_29_out_ap_vld;
output  [7:0] quantized_k_group_28_out;
output   quantized_k_group_28_out_ap_vld;
output  [7:0] quantized_k_group_27_out;
output   quantized_k_group_27_out_ap_vld;
output  [7:0] quantized_k_group_26_out;
output   quantized_k_group_26_out_ap_vld;
output  [7:0] quantized_k_group_25_out;
output   quantized_k_group_25_out_ap_vld;
output  [7:0] quantized_k_group_24_out;
output   quantized_k_group_24_out_ap_vld;
output  [7:0] quantized_k_group_23_out;
output   quantized_k_group_23_out_ap_vld;
output  [7:0] quantized_k_group_22_out;
output   quantized_k_group_22_out_ap_vld;
output  [7:0] quantized_k_group_21_out;
output   quantized_k_group_21_out_ap_vld;
output  [7:0] quantized_k_group_20_out;
output   quantized_k_group_20_out_ap_vld;
output  [7:0] quantized_k_group_19_out;
output   quantized_k_group_19_out_ap_vld;
output  [7:0] quantized_k_group_18_out;
output   quantized_k_group_18_out_ap_vld;
output  [7:0] quantized_k_group_17_out;
output   quantized_k_group_17_out_ap_vld;
output  [7:0] quantized_k_group_16_out;
output   quantized_k_group_16_out_ap_vld;
output  [7:0] quantized_k_group_15_out;
output   quantized_k_group_15_out_ap_vld;
output  [7:0] quantized_k_group_14_out;
output   quantized_k_group_14_out_ap_vld;
output  [7:0] quantized_k_group_13_out;
output   quantized_k_group_13_out_ap_vld;
output  [7:0] quantized_k_group_12_out;
output   quantized_k_group_12_out_ap_vld;
output  [7:0] quantized_k_group_11_out;
output   quantized_k_group_11_out_ap_vld;
output  [7:0] quantized_k_group_10_out;
output   quantized_k_group_10_out_ap_vld;
output  [7:0] quantized_k_group_9_out;
output   quantized_k_group_9_out_ap_vld;
output  [7:0] quantized_k_group_8_out;
output   quantized_k_group_8_out_ap_vld;
output  [7:0] quantized_k_group_7_out;
output   quantized_k_group_7_out_ap_vld;
output  [7:0] quantized_k_group_6_out;
output   quantized_k_group_6_out_ap_vld;
output  [7:0] quantized_k_group_5_out;
output   quantized_k_group_5_out_ap_vld;
output  [7:0] quantized_k_group_4_out;
output   quantized_k_group_4_out_ap_vld;
output  [7:0] quantized_k_group_3_out;
output   quantized_k_group_3_out_ap_vld;
output  [7:0] quantized_k_group_2_out;
output   quantized_k_group_2_out_ap_vld;
output  [7:0] quantized_k_group_1_out;
output   quantized_k_group_1_out_ap_vld;
output  [7:0] quantized_k_group_out;
output   quantized_k_group_out_ap_vld;
output  [7:0] quantized_v_group_31_out;
output   quantized_v_group_31_out_ap_vld;
output  [7:0] quantized_v_group_30_out;
output   quantized_v_group_30_out_ap_vld;
output  [7:0] quantized_v_group_29_out;
output   quantized_v_group_29_out_ap_vld;
output  [7:0] quantized_v_group_28_out;
output   quantized_v_group_28_out_ap_vld;
output  [7:0] quantized_v_group_27_out;
output   quantized_v_group_27_out_ap_vld;
output  [7:0] quantized_v_group_26_out;
output   quantized_v_group_26_out_ap_vld;
output  [7:0] quantized_v_group_25_out;
output   quantized_v_group_25_out_ap_vld;
output  [7:0] quantized_v_group_24_out;
output   quantized_v_group_24_out_ap_vld;
output  [7:0] quantized_v_group_23_out;
output   quantized_v_group_23_out_ap_vld;
output  [7:0] quantized_v_group_22_out;
output   quantized_v_group_22_out_ap_vld;
output  [7:0] quantized_v_group_21_out;
output   quantized_v_group_21_out_ap_vld;
output  [7:0] quantized_v_group_20_out;
output   quantized_v_group_20_out_ap_vld;
output  [7:0] quantized_v_group_19_out;
output   quantized_v_group_19_out_ap_vld;
output  [7:0] quantized_v_group_18_out;
output   quantized_v_group_18_out_ap_vld;
output  [7:0] quantized_v_group_17_out;
output   quantized_v_group_17_out_ap_vld;
output  [7:0] quantized_v_group_16_out;
output   quantized_v_group_16_out_ap_vld;
output  [7:0] quantized_v_group_15_out;
output   quantized_v_group_15_out_ap_vld;
output  [7:0] quantized_v_group_14_out;
output   quantized_v_group_14_out_ap_vld;
output  [7:0] quantized_v_group_13_out;
output   quantized_v_group_13_out_ap_vld;
output  [7:0] quantized_v_group_12_out;
output   quantized_v_group_12_out_ap_vld;
output  [7:0] quantized_v_group_11_out;
output   quantized_v_group_11_out_ap_vld;
output  [7:0] quantized_v_group_10_out;
output   quantized_v_group_10_out_ap_vld;
output  [7:0] quantized_v_group_9_out;
output   quantized_v_group_9_out_ap_vld;
output  [7:0] quantized_v_group_8_out;
output   quantized_v_group_8_out_ap_vld;
output  [7:0] quantized_v_group_7_out;
output   quantized_v_group_7_out_ap_vld;
output  [7:0] quantized_v_group_6_out;
output   quantized_v_group_6_out_ap_vld;
output  [7:0] quantized_v_group_5_out;
output   quantized_v_group_5_out_ap_vld;
output  [7:0] quantized_v_group_4_out;
output   quantized_v_group_4_out_ap_vld;
output  [7:0] quantized_v_group_3_out;
output   quantized_v_group_3_out_ap_vld;
output  [7:0] quantized_v_group_2_out;
output   quantized_v_group_2_out_ap_vld;
output  [7:0] quantized_v_group_1_out;
output   quantized_v_group_1_out_ap_vld;
output  [7:0] quantized_v_group_out;
output   quantized_v_group_out_ap_vld;

reg ap_idle;
reg quantized_k_group_31_out_ap_vld;
reg quantized_k_group_30_out_ap_vld;
reg quantized_k_group_29_out_ap_vld;
reg quantized_k_group_28_out_ap_vld;
reg quantized_k_group_27_out_ap_vld;
reg quantized_k_group_26_out_ap_vld;
reg quantized_k_group_25_out_ap_vld;
reg quantized_k_group_24_out_ap_vld;
reg quantized_k_group_23_out_ap_vld;
reg quantized_k_group_22_out_ap_vld;
reg quantized_k_group_21_out_ap_vld;
reg quantized_k_group_20_out_ap_vld;
reg quantized_k_group_19_out_ap_vld;
reg quantized_k_group_18_out_ap_vld;
reg quantized_k_group_17_out_ap_vld;
reg quantized_k_group_16_out_ap_vld;
reg quantized_k_group_15_out_ap_vld;
reg quantized_k_group_14_out_ap_vld;
reg quantized_k_group_13_out_ap_vld;
reg quantized_k_group_12_out_ap_vld;
reg quantized_k_group_11_out_ap_vld;
reg quantized_k_group_10_out_ap_vld;
reg quantized_k_group_9_out_ap_vld;
reg quantized_k_group_8_out_ap_vld;
reg quantized_k_group_7_out_ap_vld;
reg quantized_k_group_6_out_ap_vld;
reg quantized_k_group_5_out_ap_vld;
reg quantized_k_group_4_out_ap_vld;
reg quantized_k_group_3_out_ap_vld;
reg quantized_k_group_2_out_ap_vld;
reg quantized_k_group_1_out_ap_vld;
reg quantized_k_group_out_ap_vld;
reg quantized_v_group_31_out_ap_vld;
reg quantized_v_group_30_out_ap_vld;
reg quantized_v_group_29_out_ap_vld;
reg quantized_v_group_28_out_ap_vld;
reg quantized_v_group_27_out_ap_vld;
reg quantized_v_group_26_out_ap_vld;
reg quantized_v_group_25_out_ap_vld;
reg quantized_v_group_24_out_ap_vld;
reg quantized_v_group_23_out_ap_vld;
reg quantized_v_group_22_out_ap_vld;
reg quantized_v_group_21_out_ap_vld;
reg quantized_v_group_20_out_ap_vld;
reg quantized_v_group_19_out_ap_vld;
reg quantized_v_group_18_out_ap_vld;
reg quantized_v_group_17_out_ap_vld;
reg quantized_v_group_16_out_ap_vld;
reg quantized_v_group_15_out_ap_vld;
reg quantized_v_group_14_out_ap_vld;
reg quantized_v_group_13_out_ap_vld;
reg quantized_v_group_12_out_ap_vld;
reg quantized_v_group_11_out_ap_vld;
reg quantized_v_group_10_out_ap_vld;
reg quantized_v_group_9_out_ap_vld;
reg quantized_v_group_8_out_ap_vld;
reg quantized_v_group_7_out_ap_vld;
reg quantized_v_group_6_out_ap_vld;
reg quantized_v_group_5_out_ap_vld;
reg quantized_v_group_4_out_ap_vld;
reg quantized_v_group_3_out_ap_vld;
reg quantized_v_group_2_out_ap_vld;
reg quantized_v_group_1_out_ap_vld;
reg quantized_v_group_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln505_fu_1466_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [32:0] sh_prom_i_i328_cast_fu_1442_p1;
reg   [32:0] sh_prom_i_i328_cast_reg_3374;
wire   [32:0] sh_prom_i_i_cast_fu_1450_p1;
reg   [32:0] sh_prom_i_i_cast_reg_3382;
reg   [0:0] icmp_ln505_reg_3390;
wire   [2:0] trunc_ln504_fu_1478_p1;
reg   [2:0] trunc_ln504_reg_3394;
reg   [2:0] trunc_ln504_reg_3394_pp0_iter1_reg;
wire   [0:0] tmp_123_fu_1522_p3;
reg   [0:0] tmp_123_reg_3398;
reg   [0:0] tmp_123_reg_3398_pp0_iter1_reg;
wire   [32:0] add_ln364_fu_1548_p2;
reg   [32:0] add_ln364_reg_3403;
wire   [0:0] tmp_125_fu_1594_p3;
reg   [0:0] tmp_125_reg_3408;
reg   [0:0] tmp_125_reg_3408_pp0_iter1_reg;
wire   [32:0] add_ln364_1_fu_1620_p2;
reg   [32:0] add_ln364_1_reg_3413;
wire   [0:0] tmp_127_fu_1666_p3;
reg   [0:0] tmp_127_reg_3418;
reg   [0:0] tmp_127_reg_3418_pp0_iter1_reg;
wire   [32:0] add_ln364_2_fu_1692_p2;
reg   [32:0] add_ln364_2_reg_3423;
wire   [0:0] tmp_129_fu_1738_p3;
reg   [0:0] tmp_129_reg_3428;
reg   [0:0] tmp_129_reg_3428_pp0_iter1_reg;
wire   [32:0] add_ln364_3_fu_1764_p2;
reg   [32:0] add_ln364_3_reg_3433;
wire   [0:0] tmp_131_fu_1810_p3;
reg   [0:0] tmp_131_reg_3438;
reg   [0:0] tmp_131_reg_3438_pp0_iter1_reg;
wire   [32:0] add_ln364_4_fu_1836_p2;
reg   [32:0] add_ln364_4_reg_3443;
wire   [0:0] tmp_133_fu_1882_p3;
reg   [0:0] tmp_133_reg_3448;
reg   [0:0] tmp_133_reg_3448_pp0_iter1_reg;
wire   [32:0] add_ln364_5_fu_1908_p2;
reg   [32:0] add_ln364_5_reg_3453;
wire   [0:0] tmp_135_fu_1954_p3;
reg   [0:0] tmp_135_reg_3458;
reg   [0:0] tmp_135_reg_3458_pp0_iter1_reg;
wire   [32:0] add_ln364_6_fu_1980_p2;
reg   [32:0] add_ln364_6_reg_3463;
wire   [0:0] tmp_137_fu_2026_p3;
reg   [0:0] tmp_137_reg_3468;
reg   [0:0] tmp_137_reg_3468_pp0_iter1_reg;
wire   [32:0] add_ln364_7_fu_2052_p2;
reg   [32:0] add_ln364_7_reg_3473;
wire   [7:0] select_ln369_fu_2087_p3;
reg   [7:0] select_ln369_reg_3478;
wire   [7:0] select_ln369_1_fu_2119_p3;
reg   [7:0] select_ln369_1_reg_3484;
wire   [7:0] select_ln369_2_fu_2151_p3;
reg   [7:0] select_ln369_2_reg_3490;
wire   [7:0] select_ln369_3_fu_2183_p3;
reg   [7:0] select_ln369_3_reg_3496;
wire   [7:0] select_ln369_4_fu_2215_p3;
reg   [7:0] select_ln369_4_reg_3502;
wire   [7:0] select_ln369_5_fu_2247_p3;
reg   [7:0] select_ln369_5_reg_3508;
wire   [7:0] select_ln369_6_fu_2279_p3;
reg   [7:0] select_ln369_6_reg_3514;
wire   [7:0] select_ln369_7_fu_2311_p3;
reg   [7:0] select_ln369_7_reg_3520;
reg   [3:0] block_fu_326;
wire   [3:0] add_ln506_fu_1472_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_block_1;
wire    ap_block_pp0_stage0;
reg   [7:0] quantized_v_group_fu_330;
wire   [7:0] quantized_v_group_35_fu_2681_p3;
reg   [7:0] quantized_v_group_1_fu_334;
wire   [7:0] quantized_v_group_34_fu_2579_p3;
reg   [7:0] quantized_v_group_2_fu_338;
wire   [7:0] quantized_v_group_33_fu_2477_p3;
reg   [7:0] quantized_v_group_3_fu_342;
wire   [7:0] quantized_v_group_32_fu_2375_p3;
reg   [7:0] quantized_v_group_4_fu_346;
reg   [7:0] quantized_v_group_5_fu_350;
reg   [7:0] quantized_v_group_6_fu_354;
reg   [7:0] quantized_v_group_7_fu_358;
reg   [7:0] quantized_v_group_8_fu_362;
reg   [7:0] quantized_v_group_9_fu_366;
reg   [7:0] quantized_v_group_10_fu_370;
reg   [7:0] quantized_v_group_11_fu_374;
reg   [7:0] quantized_v_group_12_fu_378;
reg   [7:0] quantized_v_group_13_fu_382;
reg   [7:0] quantized_v_group_14_fu_386;
reg   [7:0] quantized_v_group_15_fu_390;
reg   [7:0] quantized_v_group_16_fu_394;
reg   [7:0] quantized_v_group_17_fu_398;
reg   [7:0] quantized_v_group_18_fu_402;
reg   [7:0] quantized_v_group_19_fu_406;
reg   [7:0] quantized_v_group_20_fu_410;
reg   [7:0] quantized_v_group_21_fu_414;
reg   [7:0] quantized_v_group_22_fu_418;
reg   [7:0] quantized_v_group_23_fu_422;
reg   [7:0] quantized_v_group_24_fu_426;
reg   [7:0] quantized_v_group_25_fu_430;
reg   [7:0] quantized_v_group_26_fu_434;
reg   [7:0] quantized_v_group_27_fu_438;
reg   [7:0] quantized_v_group_28_fu_442;
reg   [7:0] quantized_v_group_29_fu_446;
reg   [7:0] quantized_v_group_30_fu_450;
reg   [7:0] quantized_v_group_31_fu_454;
reg   [7:0] quantized_k_group_fu_458;
wire   [7:0] quantized_k_group_35_fu_2630_p3;
reg   [7:0] quantized_k_group_1_fu_462;
wire   [7:0] quantized_k_group_34_fu_2528_p3;
reg   [7:0] quantized_k_group_2_fu_466;
wire   [7:0] quantized_k_group_33_fu_2426_p3;
reg   [7:0] quantized_k_group_3_fu_470;
wire   [7:0] quantized_k_group_32_fu_2324_p3;
reg   [7:0] quantized_k_group_4_fu_474;
reg   [7:0] quantized_k_group_5_fu_478;
reg   [7:0] quantized_k_group_6_fu_482;
reg   [7:0] quantized_k_group_7_fu_486;
reg   [7:0] quantized_k_group_8_fu_490;
reg   [7:0] quantized_k_group_9_fu_494;
reg   [7:0] quantized_k_group_10_fu_498;
reg   [7:0] quantized_k_group_11_fu_502;
reg   [7:0] quantized_k_group_12_fu_506;
reg   [7:0] quantized_k_group_13_fu_510;
reg   [7:0] quantized_k_group_14_fu_514;
reg   [7:0] quantized_k_group_15_fu_518;
reg   [7:0] quantized_k_group_16_fu_522;
reg   [7:0] quantized_k_group_17_fu_526;
reg   [7:0] quantized_k_group_18_fu_530;
reg   [7:0] quantized_k_group_19_fu_534;
reg   [7:0] quantized_k_group_20_fu_538;
reg   [7:0] quantized_k_group_21_fu_542;
reg   [7:0] quantized_k_group_22_fu_546;
reg   [7:0] quantized_k_group_23_fu_550;
reg   [7:0] quantized_k_group_24_fu_554;
reg   [7:0] quantized_k_group_25_fu_558;
reg   [7:0] quantized_k_group_26_fu_562;
reg   [7:0] quantized_k_group_27_fu_566;
reg   [7:0] quantized_k_group_28_fu_570;
reg   [7:0] quantized_k_group_29_fu_574;
reg   [7:0] quantized_k_group_30_fu_578;
reg   [7:0] quantized_k_group_31_fu_582;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] raw_fu_1482_p17;
wire   [31:0] raw_fu_1482_p19;
wire   [31:0] magnitude_fu_1530_p2;
wire   [31:0] magnitude_3_fu_1536_p3;
wire   [32:0] zext_ln364_fu_1544_p1;
wire   [32:0] conv3_i12_i_i313_cast_fu_1446_p1;
wire   [31:0] raw_1_fu_1554_p17;
wire   [31:0] raw_1_fu_1554_p19;
wire   [31:0] magnitude_4_fu_1602_p2;
wire   [31:0] magnitude_5_fu_1608_p3;
wire   [32:0] zext_ln364_1_fu_1616_p1;
wire   [32:0] conv3_i12_i_i_cast_fu_1454_p1;
wire   [31:0] raw_2_fu_1626_p17;
wire   [31:0] raw_2_fu_1626_p19;
wire   [31:0] magnitude_6_fu_1674_p2;
wire   [31:0] magnitude_7_fu_1680_p3;
wire   [32:0] zext_ln364_2_fu_1688_p1;
wire   [31:0] raw_3_fu_1698_p17;
wire   [31:0] raw_3_fu_1698_p19;
wire   [31:0] magnitude_8_fu_1746_p2;
wire   [31:0] magnitude_9_fu_1752_p3;
wire   [32:0] zext_ln364_3_fu_1760_p1;
wire   [31:0] raw_4_fu_1770_p17;
wire   [31:0] raw_4_fu_1770_p19;
wire   [31:0] magnitude_10_fu_1818_p2;
wire   [31:0] magnitude_11_fu_1824_p3;
wire   [32:0] zext_ln364_4_fu_1832_p1;
wire   [31:0] raw_5_fu_1842_p17;
wire   [31:0] raw_5_fu_1842_p19;
wire   [31:0] magnitude_12_fu_1890_p2;
wire   [31:0] magnitude_13_fu_1896_p3;
wire   [32:0] zext_ln364_5_fu_1904_p1;
wire   [31:0] raw_6_fu_1914_p17;
wire   [31:0] raw_6_fu_1914_p19;
wire   [31:0] magnitude_14_fu_1962_p2;
wire   [31:0] magnitude_15_fu_1968_p3;
wire   [32:0] zext_ln364_6_fu_1976_p1;
wire   [31:0] raw_7_fu_1986_p17;
wire   [31:0] raw_7_fu_1986_p19;
wire   [31:0] magnitude_16_fu_2034_p2;
wire   [31:0] magnitude_17_fu_2040_p3;
wire   [32:0] zext_ln364_7_fu_2048_p1;
wire   [32:0] lshr_ln364_fu_2063_p2;
wire   [24:0] tmp_124_fu_2067_p4;
wire   [0:0] icmp_ln365_fu_2077_p2;
wire   [7:0] trunc_ln369_fu_2083_p1;
wire   [32:0] lshr_ln364_1_fu_2095_p2;
wire   [24:0] tmp_126_fu_2099_p4;
wire   [0:0] icmp_ln365_1_fu_2109_p2;
wire   [7:0] trunc_ln369_1_fu_2115_p1;
wire   [32:0] lshr_ln364_2_fu_2127_p2;
wire   [24:0] tmp_128_fu_2131_p4;
wire   [0:0] icmp_ln365_2_fu_2141_p2;
wire   [7:0] trunc_ln369_2_fu_2147_p1;
wire   [32:0] lshr_ln364_3_fu_2159_p2;
wire   [24:0] tmp_130_fu_2163_p4;
wire   [0:0] icmp_ln365_3_fu_2173_p2;
wire   [7:0] trunc_ln369_3_fu_2179_p1;
wire   [32:0] lshr_ln364_4_fu_2191_p2;
wire   [24:0] tmp_132_fu_2195_p4;
wire   [0:0] icmp_ln365_4_fu_2205_p2;
wire   [7:0] trunc_ln369_4_fu_2211_p1;
wire   [32:0] lshr_ln364_5_fu_2223_p2;
wire   [24:0] tmp_134_fu_2227_p4;
wire   [0:0] icmp_ln365_5_fu_2237_p2;
wire   [7:0] trunc_ln369_5_fu_2243_p1;
wire   [32:0] lshr_ln364_6_fu_2255_p2;
wire   [24:0] tmp_136_fu_2259_p4;
wire   [0:0] icmp_ln365_6_fu_2269_p2;
wire   [7:0] trunc_ln369_6_fu_2275_p1;
wire   [32:0] lshr_ln364_7_fu_2287_p2;
wire   [24:0] tmp_138_fu_2291_p4;
wire   [0:0] icmp_ln365_7_fu_2301_p2;
wire   [7:0] trunc_ln369_7_fu_2307_p1;
wire   [7:0] sub_ln370_fu_2319_p2;
wire   [7:0] sub_ln370_1_fu_2370_p2;
wire   [7:0] sub_ln370_2_fu_2421_p2;
wire   [7:0] sub_ln370_3_fu_2472_p2;
wire   [7:0] sub_ln370_4_fu_2523_p2;
wire   [7:0] sub_ln370_5_fu_2574_p2;
wire   [7:0] sub_ln370_6_fu_2625_p2;
wire   [7:0] sub_ln370_7_fu_2676_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [2:0] raw_fu_1482_p1;
wire   [2:0] raw_fu_1482_p3;
wire   [2:0] raw_fu_1482_p5;
wire   [2:0] raw_fu_1482_p7;
wire  signed [2:0] raw_fu_1482_p9;
wire  signed [2:0] raw_fu_1482_p11;
wire  signed [2:0] raw_fu_1482_p13;
wire  signed [2:0] raw_fu_1482_p15;
wire   [2:0] raw_1_fu_1554_p1;
wire   [2:0] raw_1_fu_1554_p3;
wire   [2:0] raw_1_fu_1554_p5;
wire   [2:0] raw_1_fu_1554_p7;
wire  signed [2:0] raw_1_fu_1554_p9;
wire  signed [2:0] raw_1_fu_1554_p11;
wire  signed [2:0] raw_1_fu_1554_p13;
wire  signed [2:0] raw_1_fu_1554_p15;
wire   [2:0] raw_2_fu_1626_p1;
wire   [2:0] raw_2_fu_1626_p3;
wire   [2:0] raw_2_fu_1626_p5;
wire   [2:0] raw_2_fu_1626_p7;
wire  signed [2:0] raw_2_fu_1626_p9;
wire  signed [2:0] raw_2_fu_1626_p11;
wire  signed [2:0] raw_2_fu_1626_p13;
wire  signed [2:0] raw_2_fu_1626_p15;
wire   [2:0] raw_3_fu_1698_p1;
wire   [2:0] raw_3_fu_1698_p3;
wire   [2:0] raw_3_fu_1698_p5;
wire   [2:0] raw_3_fu_1698_p7;
wire  signed [2:0] raw_3_fu_1698_p9;
wire  signed [2:0] raw_3_fu_1698_p11;
wire  signed [2:0] raw_3_fu_1698_p13;
wire  signed [2:0] raw_3_fu_1698_p15;
wire   [2:0] raw_4_fu_1770_p1;
wire   [2:0] raw_4_fu_1770_p3;
wire   [2:0] raw_4_fu_1770_p5;
wire   [2:0] raw_4_fu_1770_p7;
wire  signed [2:0] raw_4_fu_1770_p9;
wire  signed [2:0] raw_4_fu_1770_p11;
wire  signed [2:0] raw_4_fu_1770_p13;
wire  signed [2:0] raw_4_fu_1770_p15;
wire   [2:0] raw_5_fu_1842_p1;
wire   [2:0] raw_5_fu_1842_p3;
wire   [2:0] raw_5_fu_1842_p5;
wire   [2:0] raw_5_fu_1842_p7;
wire  signed [2:0] raw_5_fu_1842_p9;
wire  signed [2:0] raw_5_fu_1842_p11;
wire  signed [2:0] raw_5_fu_1842_p13;
wire  signed [2:0] raw_5_fu_1842_p15;
wire   [2:0] raw_6_fu_1914_p1;
wire   [2:0] raw_6_fu_1914_p3;
wire   [2:0] raw_6_fu_1914_p5;
wire   [2:0] raw_6_fu_1914_p7;
wire  signed [2:0] raw_6_fu_1914_p9;
wire  signed [2:0] raw_6_fu_1914_p11;
wire  signed [2:0] raw_6_fu_1914_p13;
wire  signed [2:0] raw_6_fu_1914_p15;
wire   [2:0] raw_7_fu_1986_p1;
wire   [2:0] raw_7_fu_1986_p3;
wire   [2:0] raw_7_fu_1986_p5;
wire   [2:0] raw_7_fu_1986_p7;
wire  signed [2:0] raw_7_fu_1986_p9;
wire  signed [2:0] raw_7_fu_1986_p11;
wire  signed [2:0] raw_7_fu_1986_p13;
wire  signed [2:0] raw_7_fu_1986_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 block_fu_326 = 4'd0;
#0 quantized_v_group_fu_330 = 8'd0;
#0 quantized_v_group_1_fu_334 = 8'd0;
#0 quantized_v_group_2_fu_338 = 8'd0;
#0 quantized_v_group_3_fu_342 = 8'd0;
#0 quantized_v_group_4_fu_346 = 8'd0;
#0 quantized_v_group_5_fu_350 = 8'd0;
#0 quantized_v_group_6_fu_354 = 8'd0;
#0 quantized_v_group_7_fu_358 = 8'd0;
#0 quantized_v_group_8_fu_362 = 8'd0;
#0 quantized_v_group_9_fu_366 = 8'd0;
#0 quantized_v_group_10_fu_370 = 8'd0;
#0 quantized_v_group_11_fu_374 = 8'd0;
#0 quantized_v_group_12_fu_378 = 8'd0;
#0 quantized_v_group_13_fu_382 = 8'd0;
#0 quantized_v_group_14_fu_386 = 8'd0;
#0 quantized_v_group_15_fu_390 = 8'd0;
#0 quantized_v_group_16_fu_394 = 8'd0;
#0 quantized_v_group_17_fu_398 = 8'd0;
#0 quantized_v_group_18_fu_402 = 8'd0;
#0 quantized_v_group_19_fu_406 = 8'd0;
#0 quantized_v_group_20_fu_410 = 8'd0;
#0 quantized_v_group_21_fu_414 = 8'd0;
#0 quantized_v_group_22_fu_418 = 8'd0;
#0 quantized_v_group_23_fu_422 = 8'd0;
#0 quantized_v_group_24_fu_426 = 8'd0;
#0 quantized_v_group_25_fu_430 = 8'd0;
#0 quantized_v_group_26_fu_434 = 8'd0;
#0 quantized_v_group_27_fu_438 = 8'd0;
#0 quantized_v_group_28_fu_442 = 8'd0;
#0 quantized_v_group_29_fu_446 = 8'd0;
#0 quantized_v_group_30_fu_450 = 8'd0;
#0 quantized_v_group_31_fu_454 = 8'd0;
#0 quantized_k_group_fu_458 = 8'd0;
#0 quantized_k_group_1_fu_462 = 8'd0;
#0 quantized_k_group_2_fu_466 = 8'd0;
#0 quantized_k_group_3_fu_470 = 8'd0;
#0 quantized_k_group_4_fu_474 = 8'd0;
#0 quantized_k_group_5_fu_478 = 8'd0;
#0 quantized_k_group_6_fu_482 = 8'd0;
#0 quantized_k_group_7_fu_486 = 8'd0;
#0 quantized_k_group_8_fu_490 = 8'd0;
#0 quantized_k_group_9_fu_494 = 8'd0;
#0 quantized_k_group_10_fu_498 = 8'd0;
#0 quantized_k_group_11_fu_502 = 8'd0;
#0 quantized_k_group_12_fu_506 = 8'd0;
#0 quantized_k_group_13_fu_510 = 8'd0;
#0 quantized_k_group_14_fu_514 = 8'd0;
#0 quantized_k_group_15_fu_518 = 8'd0;
#0 quantized_k_group_16_fu_522 = 8'd0;
#0 quantized_k_group_17_fu_526 = 8'd0;
#0 quantized_k_group_18_fu_530 = 8'd0;
#0 quantized_k_group_19_fu_534 = 8'd0;
#0 quantized_k_group_20_fu_538 = 8'd0;
#0 quantized_k_group_21_fu_542 = 8'd0;
#0 quantized_k_group_22_fu_546 = 8'd0;
#0 quantized_k_group_23_fu_550 = 8'd0;
#0 quantized_k_group_24_fu_554 = 8'd0;
#0 quantized_k_group_25_fu_558 = 8'd0;
#0 quantized_k_group_26_fu_562 = 8'd0;
#0 quantized_k_group_27_fu_566 = 8'd0;
#0 quantized_k_group_28_fu_570 = 8'd0;
#0 quantized_k_group_29_fu_574 = 8'd0;
#0 quantized_k_group_30_fu_578 = 8'd0;
#0 quantized_k_group_31_fu_582 = 8'd0;
#0 ap_done_reg = 1'b0;
end

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U197(
    .din0(empty_611),
    .din1(k_raw_3534),
    .din2(k_raw_3942),
    .din3(k_raw_4350),
    .din4(empty),
    .din5(k_raw_5164),
    .din6(k_raw_5572),
    .din7(k_raw_5980),
    .def(raw_fu_1482_p17),
    .sel(trunc_ln504_fu_1478_p1),
    .dout(raw_fu_1482_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U198(
    .din0(empty_609),
    .din1(v_raw_3535),
    .din2(v_raw_3943),
    .din3(v_raw_4351),
    .din4(empty_610),
    .din5(v_raw_5165),
    .din6(v_raw_5573),
    .din7(v_raw_5981),
    .def(raw_1_fu_1554_p17),
    .sel(trunc_ln504_fu_1478_p1),
    .dout(raw_1_fu_1554_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U199(
    .din0(k_raw_3228),
    .din1(k_raw_3636),
    .din2(k_raw_4044),
    .din3(k_raw_4452),
    .din4(k_raw_4858),
    .din5(k_raw_5266),
    .din6(k_raw_5674),
    .din7(k_raw_6082),
    .def(raw_2_fu_1626_p17),
    .sel(trunc_ln504_fu_1478_p1),
    .dout(raw_2_fu_1626_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U200(
    .din0(v_raw_3229),
    .din1(v_raw_3637),
    .din2(v_raw_4045),
    .din3(v_raw_4453),
    .din4(v_raw_4859),
    .din5(v_raw_5267),
    .din6(v_raw_5675),
    .din7(v_raw_6083),
    .def(raw_3_fu_1698_p17),
    .sel(trunc_ln504_fu_1478_p1),
    .dout(raw_3_fu_1698_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U201(
    .din0(k_raw_3330),
    .din1(k_raw_3738),
    .din2(k_raw_4146),
    .din3(k_raw_4554),
    .din4(k_raw_4960),
    .din5(k_raw_5368),
    .din6(k_raw_5776),
    .din7(k_raw_6184),
    .def(raw_4_fu_1770_p17),
    .sel(trunc_ln504_fu_1478_p1),
    .dout(raw_4_fu_1770_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U202(
    .din0(v_raw_3331),
    .din1(v_raw_3739),
    .din2(v_raw_4147),
    .din3(v_raw_4555),
    .din4(v_raw_4961),
    .din5(v_raw_5369),
    .din6(v_raw_5777),
    .din7(v_raw_6185),
    .def(raw_5_fu_1842_p17),
    .sel(trunc_ln504_fu_1478_p1),
    .dout(raw_5_fu_1842_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U203(
    .din0(k_raw_3432),
    .din1(k_raw_3840),
    .din2(k_raw_4248),
    .din3(k_raw_4656),
    .din4(k_raw_5062),
    .din5(k_raw_5470),
    .din6(k_raw_5878),
    .din7(k_raw_6286),
    .def(raw_6_fu_1914_p17),
    .sel(trunc_ln504_fu_1478_p1),
    .dout(raw_6_fu_1914_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U204(
    .din0(v_raw_3433),
    .din1(v_raw_3841),
    .din2(v_raw_4249),
    .din3(v_raw_4657),
    .din4(v_raw_5063),
    .din5(v_raw_5471),
    .din6(v_raw_5879),
    .din7(v_raw_6287),
    .def(raw_7_fu_1986_p17),
    .sel(trunc_ln504_fu_1478_p1),
    .dout(raw_7_fu_1986_p19)
);

int4_decoder_token_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln505_fu_1466_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            block_fu_326 <= add_ln506_fu_1472_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            block_fu_326 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln364_1_reg_3413 <= add_ln364_1_fu_1620_p2;
        add_ln364_2_reg_3423 <= add_ln364_2_fu_1692_p2;
        add_ln364_3_reg_3433 <= add_ln364_3_fu_1764_p2;
        add_ln364_4_reg_3443 <= add_ln364_4_fu_1836_p2;
        add_ln364_5_reg_3453 <= add_ln364_5_fu_1908_p2;
        add_ln364_6_reg_3463 <= add_ln364_6_fu_1980_p2;
        add_ln364_7_reg_3473 <= add_ln364_7_fu_2052_p2;
        add_ln364_reg_3403 <= add_ln364_fu_1548_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln505_reg_3390 <= icmp_ln505_fu_1466_p2;
        select_ln369_1_reg_3484 <= select_ln369_1_fu_2119_p3;
        select_ln369_2_reg_3490 <= select_ln369_2_fu_2151_p3;
        select_ln369_3_reg_3496 <= select_ln369_3_fu_2183_p3;
        select_ln369_4_reg_3502 <= select_ln369_4_fu_2215_p3;
        select_ln369_5_reg_3508 <= select_ln369_5_fu_2247_p3;
        select_ln369_6_reg_3514 <= select_ln369_6_fu_2279_p3;
        select_ln369_7_reg_3520 <= select_ln369_7_fu_2311_p3;
        select_ln369_reg_3478 <= select_ln369_fu_2087_p3;
        sh_prom_i_i328_cast_reg_3374[4 : 0] <= sh_prom_i_i328_cast_fu_1442_p1[4 : 0];
        sh_prom_i_i_cast_reg_3382[4 : 0] <= sh_prom_i_i_cast_fu_1450_p1[4 : 0];
        tmp_123_reg_3398 <= raw_fu_1482_p19[32'd31];
        tmp_123_reg_3398_pp0_iter1_reg <= tmp_123_reg_3398;
        tmp_125_reg_3408 <= raw_1_fu_1554_p19[32'd31];
        tmp_125_reg_3408_pp0_iter1_reg <= tmp_125_reg_3408;
        tmp_127_reg_3418 <= raw_2_fu_1626_p19[32'd31];
        tmp_127_reg_3418_pp0_iter1_reg <= tmp_127_reg_3418;
        tmp_129_reg_3428 <= raw_3_fu_1698_p19[32'd31];
        tmp_129_reg_3428_pp0_iter1_reg <= tmp_129_reg_3428;
        tmp_131_reg_3438 <= raw_4_fu_1770_p19[32'd31];
        tmp_131_reg_3438_pp0_iter1_reg <= tmp_131_reg_3438;
        tmp_133_reg_3448 <= raw_5_fu_1842_p19[32'd31];
        tmp_133_reg_3448_pp0_iter1_reg <= tmp_133_reg_3448;
        tmp_135_reg_3458 <= raw_6_fu_1914_p19[32'd31];
        tmp_135_reg_3458_pp0_iter1_reg <= tmp_135_reg_3458;
        tmp_137_reg_3468 <= raw_7_fu_1986_p19[32'd31];
        tmp_137_reg_3468_pp0_iter1_reg <= tmp_137_reg_3468;
        trunc_ln504_reg_3394 <= trunc_ln504_fu_1478_p1;
        trunc_ln504_reg_3394_pp0_iter1_reg <= trunc_ln504_reg_3394;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln504_reg_3394_pp0_iter1_reg == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        quantized_k_group_10_fu_498 <= quantized_k_group_33_fu_2426_p3;
        quantized_k_group_11_fu_502 <= quantized_k_group_32_fu_2324_p3;
        quantized_k_group_8_fu_490 <= quantized_k_group_35_fu_2630_p3;
        quantized_k_group_9_fu_494 <= quantized_k_group_34_fu_2528_p3;
        quantized_v_group_10_fu_370 <= quantized_v_group_33_fu_2477_p3;
        quantized_v_group_11_fu_374 <= quantized_v_group_32_fu_2375_p3;
        quantized_v_group_8_fu_362 <= quantized_v_group_35_fu_2681_p3;
        quantized_v_group_9_fu_366 <= quantized_v_group_34_fu_2579_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln504_reg_3394_pp0_iter1_reg == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        quantized_k_group_12_fu_506 <= quantized_k_group_35_fu_2630_p3;
        quantized_k_group_13_fu_510 <= quantized_k_group_34_fu_2528_p3;
        quantized_k_group_14_fu_514 <= quantized_k_group_33_fu_2426_p3;
        quantized_k_group_15_fu_518 <= quantized_k_group_32_fu_2324_p3;
        quantized_v_group_12_fu_378 <= quantized_v_group_35_fu_2681_p3;
        quantized_v_group_13_fu_382 <= quantized_v_group_34_fu_2579_p3;
        quantized_v_group_14_fu_386 <= quantized_v_group_33_fu_2477_p3;
        quantized_v_group_15_fu_390 <= quantized_v_group_32_fu_2375_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln504_reg_3394_pp0_iter1_reg == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        quantized_k_group_16_fu_522 <= quantized_k_group_35_fu_2630_p3;
        quantized_k_group_17_fu_526 <= quantized_k_group_34_fu_2528_p3;
        quantized_k_group_18_fu_530 <= quantized_k_group_33_fu_2426_p3;
        quantized_k_group_19_fu_534 <= quantized_k_group_32_fu_2324_p3;
        quantized_v_group_16_fu_394 <= quantized_v_group_35_fu_2681_p3;
        quantized_v_group_17_fu_398 <= quantized_v_group_34_fu_2579_p3;
        quantized_v_group_18_fu_402 <= quantized_v_group_33_fu_2477_p3;
        quantized_v_group_19_fu_406 <= quantized_v_group_32_fu_2375_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln504_reg_3394_pp0_iter1_reg == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        quantized_k_group_1_fu_462 <= quantized_k_group_34_fu_2528_p3;
        quantized_k_group_2_fu_466 <= quantized_k_group_33_fu_2426_p3;
        quantized_k_group_3_fu_470 <= quantized_k_group_32_fu_2324_p3;
        quantized_k_group_fu_458 <= quantized_k_group_35_fu_2630_p3;
        quantized_v_group_1_fu_334 <= quantized_v_group_34_fu_2579_p3;
        quantized_v_group_2_fu_338 <= quantized_v_group_33_fu_2477_p3;
        quantized_v_group_3_fu_342 <= quantized_v_group_32_fu_2375_p3;
        quantized_v_group_fu_330 <= quantized_v_group_35_fu_2681_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln504_reg_3394_pp0_iter1_reg == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        quantized_k_group_20_fu_538 <= quantized_k_group_35_fu_2630_p3;
        quantized_k_group_21_fu_542 <= quantized_k_group_34_fu_2528_p3;
        quantized_k_group_22_fu_546 <= quantized_k_group_33_fu_2426_p3;
        quantized_k_group_23_fu_550 <= quantized_k_group_32_fu_2324_p3;
        quantized_v_group_20_fu_410 <= quantized_v_group_35_fu_2681_p3;
        quantized_v_group_21_fu_414 <= quantized_v_group_34_fu_2579_p3;
        quantized_v_group_22_fu_418 <= quantized_v_group_33_fu_2477_p3;
        quantized_v_group_23_fu_422 <= quantized_v_group_32_fu_2375_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln504_reg_3394_pp0_iter1_reg == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        quantized_k_group_24_fu_554 <= quantized_k_group_35_fu_2630_p3;
        quantized_k_group_25_fu_558 <= quantized_k_group_34_fu_2528_p3;
        quantized_k_group_26_fu_562 <= quantized_k_group_33_fu_2426_p3;
        quantized_k_group_27_fu_566 <= quantized_k_group_32_fu_2324_p3;
        quantized_v_group_24_fu_426 <= quantized_v_group_35_fu_2681_p3;
        quantized_v_group_25_fu_430 <= quantized_v_group_34_fu_2579_p3;
        quantized_v_group_26_fu_434 <= quantized_v_group_33_fu_2477_p3;
        quantized_v_group_27_fu_438 <= quantized_v_group_32_fu_2375_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln504_reg_3394_pp0_iter1_reg == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        quantized_k_group_28_fu_570 <= quantized_k_group_35_fu_2630_p3;
        quantized_k_group_29_fu_574 <= quantized_k_group_34_fu_2528_p3;
        quantized_k_group_30_fu_578 <= quantized_k_group_33_fu_2426_p3;
        quantized_k_group_31_fu_582 <= quantized_k_group_32_fu_2324_p3;
        quantized_v_group_28_fu_442 <= quantized_v_group_35_fu_2681_p3;
        quantized_v_group_29_fu_446 <= quantized_v_group_34_fu_2579_p3;
        quantized_v_group_30_fu_450 <= quantized_v_group_33_fu_2477_p3;
        quantized_v_group_31_fu_454 <= quantized_v_group_32_fu_2375_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln504_reg_3394_pp0_iter1_reg == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        quantized_k_group_4_fu_474 <= quantized_k_group_35_fu_2630_p3;
        quantized_k_group_5_fu_478 <= quantized_k_group_34_fu_2528_p3;
        quantized_k_group_6_fu_482 <= quantized_k_group_33_fu_2426_p3;
        quantized_k_group_7_fu_486 <= quantized_k_group_32_fu_2324_p3;
        quantized_v_group_4_fu_346 <= quantized_v_group_35_fu_2681_p3;
        quantized_v_group_5_fu_350 <= quantized_v_group_34_fu_2579_p3;
        quantized_v_group_6_fu_354 <= quantized_v_group_33_fu_2477_p3;
        quantized_v_group_7_fu_358 <= quantized_v_group_32_fu_2375_p3;
    end
end

always @ (*) begin
    if (((icmp_ln505_fu_1466_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_block_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_block_1 = block_fu_326;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_10_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_11_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_12_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_13_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_14_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_15_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_16_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_17_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_18_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_19_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_1_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_20_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_21_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_22_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_23_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_24_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_25_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_26_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_27_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_28_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_29_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_2_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_30_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_31_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_3_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_4_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_5_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_6_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_7_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_8_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_9_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_k_group_out_ap_vld = 1'b1;
    end else begin
        quantized_k_group_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_10_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_11_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_12_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_13_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_14_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_15_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_16_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_17_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_18_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_19_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_1_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_20_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_21_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_22_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_23_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_24_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_25_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_26_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_27_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_28_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_29_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_2_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_30_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_31_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_3_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_4_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_5_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_6_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_7_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_8_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_9_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln505_reg_3390 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        quantized_v_group_out_ap_vld = 1'b1;
    end else begin
        quantized_v_group_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln364_1_fu_1620_p2 = (zext_ln364_1_fu_1616_p1 + conv3_i12_i_i_cast_fu_1454_p1);

assign add_ln364_2_fu_1692_p2 = (zext_ln364_2_fu_1688_p1 + conv3_i12_i_i313_cast_fu_1446_p1);

assign add_ln364_3_fu_1764_p2 = (zext_ln364_3_fu_1760_p1 + conv3_i12_i_i_cast_fu_1454_p1);

assign add_ln364_4_fu_1836_p2 = (zext_ln364_4_fu_1832_p1 + conv3_i12_i_i313_cast_fu_1446_p1);

assign add_ln364_5_fu_1908_p2 = (zext_ln364_5_fu_1904_p1 + conv3_i12_i_i_cast_fu_1454_p1);

assign add_ln364_6_fu_1980_p2 = (zext_ln364_6_fu_1976_p1 + conv3_i12_i_i313_cast_fu_1446_p1);

assign add_ln364_7_fu_2052_p2 = (zext_ln364_7_fu_2048_p1 + conv3_i12_i_i_cast_fu_1454_p1);

assign add_ln364_fu_1548_p2 = (zext_ln364_fu_1544_p1 + conv3_i12_i_i313_cast_fu_1446_p1);

assign add_ln506_fu_1472_p2 = (ap_sig_allocacmp_block_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign conv3_i12_i_i313_cast_fu_1446_p1 = conv3_i12_i_i313;

assign conv3_i12_i_i_cast_fu_1454_p1 = conv3_i12_i_i;

assign icmp_ln365_1_fu_2109_p2 = ((tmp_126_fu_2099_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln365_2_fu_2141_p2 = ((tmp_128_fu_2131_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln365_3_fu_2173_p2 = ((tmp_130_fu_2163_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln365_4_fu_2205_p2 = ((tmp_132_fu_2195_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln365_5_fu_2237_p2 = ((tmp_134_fu_2227_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln365_6_fu_2269_p2 = ((tmp_136_fu_2259_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln365_7_fu_2301_p2 = ((tmp_138_fu_2291_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln365_fu_2077_p2 = ((tmp_124_fu_2067_p4 != 25'd0) ? 1'b1 : 1'b0);

assign icmp_ln505_fu_1466_p2 = ((ap_sig_allocacmp_block_1 == 4'd8) ? 1'b1 : 1'b0);

assign lshr_ln364_1_fu_2095_p2 = add_ln364_1_reg_3413 >> sh_prom_i_i_cast_reg_3382;

assign lshr_ln364_2_fu_2127_p2 = add_ln364_2_reg_3423 >> sh_prom_i_i328_cast_reg_3374;

assign lshr_ln364_3_fu_2159_p2 = add_ln364_3_reg_3433 >> sh_prom_i_i_cast_reg_3382;

assign lshr_ln364_4_fu_2191_p2 = add_ln364_4_reg_3443 >> sh_prom_i_i328_cast_reg_3374;

assign lshr_ln364_5_fu_2223_p2 = add_ln364_5_reg_3453 >> sh_prom_i_i_cast_reg_3382;

assign lshr_ln364_6_fu_2255_p2 = add_ln364_6_reg_3463 >> sh_prom_i_i328_cast_reg_3374;

assign lshr_ln364_7_fu_2287_p2 = add_ln364_7_reg_3473 >> sh_prom_i_i_cast_reg_3382;

assign lshr_ln364_fu_2063_p2 = add_ln364_reg_3403 >> sh_prom_i_i328_cast_reg_3374;

assign magnitude_10_fu_1818_p2 = (32'd0 - raw_4_fu_1770_p19);

assign magnitude_11_fu_1824_p3 = ((tmp_131_fu_1810_p3[0:0] == 1'b1) ? magnitude_10_fu_1818_p2 : raw_4_fu_1770_p19);

assign magnitude_12_fu_1890_p2 = (32'd0 - raw_5_fu_1842_p19);

assign magnitude_13_fu_1896_p3 = ((tmp_133_fu_1882_p3[0:0] == 1'b1) ? magnitude_12_fu_1890_p2 : raw_5_fu_1842_p19);

assign magnitude_14_fu_1962_p2 = (32'd0 - raw_6_fu_1914_p19);

assign magnitude_15_fu_1968_p3 = ((tmp_135_fu_1954_p3[0:0] == 1'b1) ? magnitude_14_fu_1962_p2 : raw_6_fu_1914_p19);

assign magnitude_16_fu_2034_p2 = (32'd0 - raw_7_fu_1986_p19);

assign magnitude_17_fu_2040_p3 = ((tmp_137_fu_2026_p3[0:0] == 1'b1) ? magnitude_16_fu_2034_p2 : raw_7_fu_1986_p19);

assign magnitude_3_fu_1536_p3 = ((tmp_123_fu_1522_p3[0:0] == 1'b1) ? magnitude_fu_1530_p2 : raw_fu_1482_p19);

assign magnitude_4_fu_1602_p2 = (32'd0 - raw_1_fu_1554_p19);

assign magnitude_5_fu_1608_p3 = ((tmp_125_fu_1594_p3[0:0] == 1'b1) ? magnitude_4_fu_1602_p2 : raw_1_fu_1554_p19);

assign magnitude_6_fu_1674_p2 = (32'd0 - raw_2_fu_1626_p19);

assign magnitude_7_fu_1680_p3 = ((tmp_127_fu_1666_p3[0:0] == 1'b1) ? magnitude_6_fu_1674_p2 : raw_2_fu_1626_p19);

assign magnitude_8_fu_1746_p2 = (32'd0 - raw_3_fu_1698_p19);

assign magnitude_9_fu_1752_p3 = ((tmp_129_fu_1738_p3[0:0] == 1'b1) ? magnitude_8_fu_1746_p2 : raw_3_fu_1698_p19);

assign magnitude_fu_1530_p2 = (32'd0 - raw_fu_1482_p19);

assign quantized_k_group_10_out = quantized_k_group_10_fu_498;

assign quantized_k_group_11_out = quantized_k_group_11_fu_502;

assign quantized_k_group_12_out = quantized_k_group_12_fu_506;

assign quantized_k_group_13_out = quantized_k_group_13_fu_510;

assign quantized_k_group_14_out = quantized_k_group_14_fu_514;

assign quantized_k_group_15_out = quantized_k_group_15_fu_518;

assign quantized_k_group_16_out = quantized_k_group_16_fu_522;

assign quantized_k_group_17_out = quantized_k_group_17_fu_526;

assign quantized_k_group_18_out = quantized_k_group_18_fu_530;

assign quantized_k_group_19_out = quantized_k_group_19_fu_534;

assign quantized_k_group_1_out = quantized_k_group_1_fu_462;

assign quantized_k_group_20_out = quantized_k_group_20_fu_538;

assign quantized_k_group_21_out = quantized_k_group_21_fu_542;

assign quantized_k_group_22_out = quantized_k_group_22_fu_546;

assign quantized_k_group_23_out = quantized_k_group_23_fu_550;

assign quantized_k_group_24_out = quantized_k_group_24_fu_554;

assign quantized_k_group_25_out = quantized_k_group_25_fu_558;

assign quantized_k_group_26_out = quantized_k_group_26_fu_562;

assign quantized_k_group_27_out = quantized_k_group_27_fu_566;

assign quantized_k_group_28_out = quantized_k_group_28_fu_570;

assign quantized_k_group_29_out = quantized_k_group_29_fu_574;

assign quantized_k_group_2_out = quantized_k_group_2_fu_466;

assign quantized_k_group_30_out = quantized_k_group_30_fu_578;

assign quantized_k_group_31_out = quantized_k_group_31_fu_582;

assign quantized_k_group_32_fu_2324_p3 = ((tmp_123_reg_3398_pp0_iter1_reg[0:0] == 1'b1) ? sub_ln370_fu_2319_p2 : select_ln369_reg_3478);

assign quantized_k_group_33_fu_2426_p3 = ((tmp_127_reg_3418_pp0_iter1_reg[0:0] == 1'b1) ? sub_ln370_2_fu_2421_p2 : select_ln369_2_reg_3490);

assign quantized_k_group_34_fu_2528_p3 = ((tmp_131_reg_3438_pp0_iter1_reg[0:0] == 1'b1) ? sub_ln370_4_fu_2523_p2 : select_ln369_4_reg_3502);

assign quantized_k_group_35_fu_2630_p3 = ((tmp_135_reg_3458_pp0_iter1_reg[0:0] == 1'b1) ? sub_ln370_6_fu_2625_p2 : select_ln369_6_reg_3514);

assign quantized_k_group_3_out = quantized_k_group_3_fu_470;

assign quantized_k_group_4_out = quantized_k_group_4_fu_474;

assign quantized_k_group_5_out = quantized_k_group_5_fu_478;

assign quantized_k_group_6_out = quantized_k_group_6_fu_482;

assign quantized_k_group_7_out = quantized_k_group_7_fu_486;

assign quantized_k_group_8_out = quantized_k_group_8_fu_490;

assign quantized_k_group_9_out = quantized_k_group_9_fu_494;

assign quantized_k_group_out = quantized_k_group_fu_458;

assign quantized_v_group_10_out = quantized_v_group_10_fu_370;

assign quantized_v_group_11_out = quantized_v_group_11_fu_374;

assign quantized_v_group_12_out = quantized_v_group_12_fu_378;

assign quantized_v_group_13_out = quantized_v_group_13_fu_382;

assign quantized_v_group_14_out = quantized_v_group_14_fu_386;

assign quantized_v_group_15_out = quantized_v_group_15_fu_390;

assign quantized_v_group_16_out = quantized_v_group_16_fu_394;

assign quantized_v_group_17_out = quantized_v_group_17_fu_398;

assign quantized_v_group_18_out = quantized_v_group_18_fu_402;

assign quantized_v_group_19_out = quantized_v_group_19_fu_406;

assign quantized_v_group_1_out = quantized_v_group_1_fu_334;

assign quantized_v_group_20_out = quantized_v_group_20_fu_410;

assign quantized_v_group_21_out = quantized_v_group_21_fu_414;

assign quantized_v_group_22_out = quantized_v_group_22_fu_418;

assign quantized_v_group_23_out = quantized_v_group_23_fu_422;

assign quantized_v_group_24_out = quantized_v_group_24_fu_426;

assign quantized_v_group_25_out = quantized_v_group_25_fu_430;

assign quantized_v_group_26_out = quantized_v_group_26_fu_434;

assign quantized_v_group_27_out = quantized_v_group_27_fu_438;

assign quantized_v_group_28_out = quantized_v_group_28_fu_442;

assign quantized_v_group_29_out = quantized_v_group_29_fu_446;

assign quantized_v_group_2_out = quantized_v_group_2_fu_338;

assign quantized_v_group_30_out = quantized_v_group_30_fu_450;

assign quantized_v_group_31_out = quantized_v_group_31_fu_454;

assign quantized_v_group_32_fu_2375_p3 = ((tmp_125_reg_3408_pp0_iter1_reg[0:0] == 1'b1) ? sub_ln370_1_fu_2370_p2 : select_ln369_1_reg_3484);

assign quantized_v_group_33_fu_2477_p3 = ((tmp_129_reg_3428_pp0_iter1_reg[0:0] == 1'b1) ? sub_ln370_3_fu_2472_p2 : select_ln369_3_reg_3496);

assign quantized_v_group_34_fu_2579_p3 = ((tmp_133_reg_3448_pp0_iter1_reg[0:0] == 1'b1) ? sub_ln370_5_fu_2574_p2 : select_ln369_5_reg_3508);

assign quantized_v_group_35_fu_2681_p3 = ((tmp_137_reg_3468_pp0_iter1_reg[0:0] == 1'b1) ? sub_ln370_7_fu_2676_p2 : select_ln369_7_reg_3520);

assign quantized_v_group_3_out = quantized_v_group_3_fu_342;

assign quantized_v_group_4_out = quantized_v_group_4_fu_346;

assign quantized_v_group_5_out = quantized_v_group_5_fu_350;

assign quantized_v_group_6_out = quantized_v_group_6_fu_354;

assign quantized_v_group_7_out = quantized_v_group_7_fu_358;

assign quantized_v_group_8_out = quantized_v_group_8_fu_362;

assign quantized_v_group_9_out = quantized_v_group_9_fu_366;

assign quantized_v_group_out = quantized_v_group_fu_330;

assign raw_1_fu_1554_p17 = 'bx;

assign raw_2_fu_1626_p17 = 'bx;

assign raw_3_fu_1698_p17 = 'bx;

assign raw_4_fu_1770_p17 = 'bx;

assign raw_5_fu_1842_p17 = 'bx;

assign raw_6_fu_1914_p17 = 'bx;

assign raw_7_fu_1986_p17 = 'bx;

assign raw_fu_1482_p17 = 'bx;

assign select_ln369_1_fu_2119_p3 = ((icmp_ln365_1_fu_2109_p2[0:0] == 1'b1) ? 8'd127 : trunc_ln369_1_fu_2115_p1);

assign select_ln369_2_fu_2151_p3 = ((icmp_ln365_2_fu_2141_p2[0:0] == 1'b1) ? 8'd127 : trunc_ln369_2_fu_2147_p1);

assign select_ln369_3_fu_2183_p3 = ((icmp_ln365_3_fu_2173_p2[0:0] == 1'b1) ? 8'd127 : trunc_ln369_3_fu_2179_p1);

assign select_ln369_4_fu_2215_p3 = ((icmp_ln365_4_fu_2205_p2[0:0] == 1'b1) ? 8'd127 : trunc_ln369_4_fu_2211_p1);

assign select_ln369_5_fu_2247_p3 = ((icmp_ln365_5_fu_2237_p2[0:0] == 1'b1) ? 8'd127 : trunc_ln369_5_fu_2243_p1);

assign select_ln369_6_fu_2279_p3 = ((icmp_ln365_6_fu_2269_p2[0:0] == 1'b1) ? 8'd127 : trunc_ln369_6_fu_2275_p1);

assign select_ln369_7_fu_2311_p3 = ((icmp_ln365_7_fu_2301_p2[0:0] == 1'b1) ? 8'd127 : trunc_ln369_7_fu_2307_p1);

assign select_ln369_fu_2087_p3 = ((icmp_ln365_fu_2077_p2[0:0] == 1'b1) ? 8'd127 : trunc_ln369_fu_2083_p1);

assign sh_prom_i_i328_cast_fu_1442_p1 = sh_prom_i_i328;

assign sh_prom_i_i_cast_fu_1450_p1 = sh_prom_i_i;

assign sub_ln370_1_fu_2370_p2 = (8'd0 - select_ln369_1_reg_3484);

assign sub_ln370_2_fu_2421_p2 = (8'd0 - select_ln369_2_reg_3490);

assign sub_ln370_3_fu_2472_p2 = (8'd0 - select_ln369_3_reg_3496);

assign sub_ln370_4_fu_2523_p2 = (8'd0 - select_ln369_4_reg_3502);

assign sub_ln370_5_fu_2574_p2 = (8'd0 - select_ln369_5_reg_3508);

assign sub_ln370_6_fu_2625_p2 = (8'd0 - select_ln369_6_reg_3514);

assign sub_ln370_7_fu_2676_p2 = (8'd0 - select_ln369_7_reg_3520);

assign sub_ln370_fu_2319_p2 = (8'd0 - select_ln369_reg_3478);

assign tmp_123_fu_1522_p3 = raw_fu_1482_p19[32'd31];

assign tmp_124_fu_2067_p4 = {{lshr_ln364_fu_2063_p2[31:7]}};

assign tmp_125_fu_1594_p3 = raw_1_fu_1554_p19[32'd31];

assign tmp_126_fu_2099_p4 = {{lshr_ln364_1_fu_2095_p2[31:7]}};

assign tmp_127_fu_1666_p3 = raw_2_fu_1626_p19[32'd31];

assign tmp_128_fu_2131_p4 = {{lshr_ln364_2_fu_2127_p2[31:7]}};

assign tmp_129_fu_1738_p3 = raw_3_fu_1698_p19[32'd31];

assign tmp_130_fu_2163_p4 = {{lshr_ln364_3_fu_2159_p2[31:7]}};

assign tmp_131_fu_1810_p3 = raw_4_fu_1770_p19[32'd31];

assign tmp_132_fu_2195_p4 = {{lshr_ln364_4_fu_2191_p2[31:7]}};

assign tmp_133_fu_1882_p3 = raw_5_fu_1842_p19[32'd31];

assign tmp_134_fu_2227_p4 = {{lshr_ln364_5_fu_2223_p2[31:7]}};

assign tmp_135_fu_1954_p3 = raw_6_fu_1914_p19[32'd31];

assign tmp_136_fu_2259_p4 = {{lshr_ln364_6_fu_2255_p2[31:7]}};

assign tmp_137_fu_2026_p3 = raw_7_fu_1986_p19[32'd31];

assign tmp_138_fu_2291_p4 = {{lshr_ln364_7_fu_2287_p2[31:7]}};

assign trunc_ln369_1_fu_2115_p1 = lshr_ln364_1_fu_2095_p2[7:0];

assign trunc_ln369_2_fu_2147_p1 = lshr_ln364_2_fu_2127_p2[7:0];

assign trunc_ln369_3_fu_2179_p1 = lshr_ln364_3_fu_2159_p2[7:0];

assign trunc_ln369_4_fu_2211_p1 = lshr_ln364_4_fu_2191_p2[7:0];

assign trunc_ln369_5_fu_2243_p1 = lshr_ln364_5_fu_2223_p2[7:0];

assign trunc_ln369_6_fu_2275_p1 = lshr_ln364_6_fu_2255_p2[7:0];

assign trunc_ln369_7_fu_2307_p1 = lshr_ln364_7_fu_2287_p2[7:0];

assign trunc_ln369_fu_2083_p1 = lshr_ln364_fu_2063_p2[7:0];

assign trunc_ln504_fu_1478_p1 = ap_sig_allocacmp_block_1[2:0];

assign zext_ln364_1_fu_1616_p1 = magnitude_5_fu_1608_p3;

assign zext_ln364_2_fu_1688_p1 = magnitude_7_fu_1680_p3;

assign zext_ln364_3_fu_1760_p1 = magnitude_9_fu_1752_p3;

assign zext_ln364_4_fu_1832_p1 = magnitude_11_fu_1824_p3;

assign zext_ln364_5_fu_1904_p1 = magnitude_13_fu_1896_p3;

assign zext_ln364_6_fu_1976_p1 = magnitude_15_fu_1968_p3;

assign zext_ln364_7_fu_2048_p1 = magnitude_17_fu_2040_p3;

assign zext_ln364_fu_1544_p1 = magnitude_3_fu_1536_p3;

always @ (posedge ap_clk) begin
    sh_prom_i_i328_cast_reg_3374[32:5] <= 28'b0000000000000000000000000000;
    sh_prom_i_i_cast_reg_3382[32:5] <= 28'b0000000000000000000000000000;
end

endmodule //int4_decoder_token_controller_swiftkv_quantize_kv_record_Pipeline_quantize_kv_group_block_loop
