set SynModuleInfo {
  {SRCNAME swiftkv_preload_rope_lut_Pipeline_preload_rope_lut_loop MODELNAME swiftkv_preload_rope_lut_Pipeline_preload_rope_lut_loop RTLNAME int4_decoder_token_controller_swiftkv_preload_rope_lut_Pipeline_preload_rope_lut_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_flow_control_loop_pipe_sequential_init RTLNAME int4_decoder_token_controller_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME int4_decoder_token_controller_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME swiftkv_preload_rope_lut MODELNAME swiftkv_preload_rope_lut RTLNAME int4_decoder_token_controller_swiftkv_preload_rope_lut}
  {SRCNAME int4_preload_model_prefix_4ddr_Pipeline_preload_model_prefix_word_loop MODELNAME int4_preload_model_prefix_4ddr_Pipeline_preload_model_prefix_word_loop RTLNAME int4_decoder_token_controller_int4_preload_model_prefix_4ddr_Pipeline_preload_model_prefix_word_loop}
  {SRCNAME int4_preload_model_prefix_4ddr MODELNAME int4_preload_model_prefix_4ddr RTLNAME int4_decoder_token_controller_int4_preload_model_prefix_4ddr}
  {SRCNAME swiftkv_load_rope_position MODELNAME swiftkv_load_rope_position RTLNAME int4_decoder_token_controller_swiftkv_load_rope_position}
  {SRCNAME int4_load_residual_4ddr_Pipeline_load_residual_word_loop MODELNAME int4_load_residual_4ddr_Pipeline_load_residual_word_loop RTLNAME int4_decoder_token_controller_int4_load_residual_4ddr_Pipeline_load_residual_word_loop}
  {SRCNAME int4_load_residual_4ddr MODELNAME int4_load_residual_4ddr RTLNAME int4_decoder_token_controller_int4_load_residual_4ddr}
  {SRCNAME swiftkv_broadcast_pe_commands MODELNAME swiftkv_broadcast_pe_commands RTLNAME int4_decoder_token_controller_swiftkv_broadcast_pe_commands}
  {SRCNAME swiftkv_broadcast_rope MODELNAME swiftkv_broadcast_rope RTLNAME int4_decoder_token_controller_swiftkv_broadcast_rope
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_flow_control_loop_pipe RTLNAME int4_decoder_token_controller_flow_control_loop_pipe BINDTYPE interface TYPE internal_upc_flow_control INSTNAME int4_decoder_token_controller_flow_control_loop_pipe_U}
    }
  }
  {SRCNAME swiftkv_run_bank_Pipeline_pe_cache_rope_pair_loop MODELNAME swiftkv_run_bank_Pipeline_pe_cache_rope_pair_loop RTLNAME int4_decoder_token_controller_swiftkv_run_bank_Pipeline_pe_cache_rope_pair_loop}
  {SRCNAME swiftkv_run_bank_Pipeline_pe_load_q_word_loop MODELNAME swiftkv_run_bank_Pipeline_pe_load_q_word_loop RTLNAME int4_decoder_token_controller_swiftkv_run_bank_Pipeline_pe_load_q_word_loop}
  {SRCNAME swiftkv_run_bank_Pipeline_pe_load_k_word_loop MODELNAME swiftkv_run_bank_Pipeline_pe_load_k_word_loop RTLNAME int4_decoder_token_controller_swiftkv_run_bank_Pipeline_pe_load_k_word_loop}
  {SRCNAME swiftkv_run_bank_Pipeline_pe_load_v_word_loop MODELNAME swiftkv_run_bank_Pipeline_pe_load_v_word_loop RTLNAME int4_decoder_token_controller_swiftkv_run_bank_Pipeline_pe_load_v_word_loop}
  {SRCNAME swiftkv_run_bank_Pipeline_pe_rope_word_loop_pe_rope_pair_phase_loop MODELNAME swiftkv_run_bank_Pipeline_pe_rope_word_loop_pe_rope_pair_phase_loop RTLNAME int4_decoder_token_controller_swiftkv_run_bank_Pipeline_pe_rope_word_loop_pe_rope_pair_phase_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_mul_32s_19s_51_4_1 RTLNAME int4_decoder_token_controller_mul_32s_19s_51_4_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME swiftkv_quantize_kv_record_Pipeline_find_kv_group_max_block_loop MODELNAME swiftkv_quantize_kv_record_Pipeline_find_kv_group_max_block_loop RTLNAME int4_decoder_token_controller_swiftkv_quantize_kv_record_Pipeline_find_kv_group_max_block_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_sparsemux_17_3_32_1_1 RTLNAME int4_decoder_token_controller_sparsemux_17_3_32_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
    }
  }
  {SRCNAME swiftkv_quantize_kv_record_Pipeline_quantize_kv_group_block_loop MODELNAME swiftkv_quantize_kv_record_Pipeline_quantize_kv_group_block_loop RTLNAME int4_decoder_token_controller_swiftkv_quantize_kv_record_Pipeline_quantize_kv_group_block_loop}
  {SRCNAME swiftkv_quantize_kv_record MODELNAME swiftkv_quantize_kv_record RTLNAME int4_decoder_token_controller_swiftkv_quantize_kv_record}
  {SRCNAME swiftkv_run_bank_Pipeline_pe_write_kv_word_loop MODELNAME swiftkv_run_bank_Pipeline_pe_write_kv_word_loop RTLNAME int4_decoder_token_controller_swiftkv_run_bank_Pipeline_pe_write_kv_word_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_sparsemux_11_3_512_1_1 RTLNAME int4_decoder_token_controller_sparsemux_11_3_512_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
    }
  }
  {SRCNAME entry_proc57 MODELNAME entry_proc57 RTLNAME int4_decoder_token_controller_entry_proc57}
  {SRCNAME swiftkv_read_compressed_kv_cache_Pipeline_read_compressed_kv_loop MODELNAME swiftkv_read_compressed_kv_cache_Pipeline_read_compressed_kv_loop RTLNAME int4_decoder_token_controller_swiftkv_read_compressed_kv_cache_Pipeline_read_compressed_kv_loop}
  {SRCNAME swiftkv_read_compressed_kv_cache MODELNAME swiftkv_read_compressed_kv_cache RTLNAME int4_decoder_token_controller_swiftkv_read_compressed_kv_cache}
  {SRCNAME swiftkv_route_compressed_kv_cache_Pipeline_route_cached_compressed_kv_loop MODELNAME swiftkv_route_compressed_kv_cache_Pipeline_route_cached_compressed_kv_loop RTLNAME int4_decoder_token_controller_swiftkv_route_compressed_kv_cache_Pipeline_route_cached_compressed_kv_loop}
  {SRCNAME swiftkv_route_compressed_kv_cache_Pipeline_stream_current_compressed_kv_loop MODELNAME swiftkv_route_compressed_kv_cache_Pipeline_stream_current_compressed_kv_loop RTLNAME int4_decoder_token_controller_swiftkv_route_compressed_kv_cache_Pipeline_stream_current_compressed_kv_loop}
  {SRCNAME swiftkv_route_compressed_kv_cache MODELNAME swiftkv_route_compressed_kv_cache RTLNAME int4_decoder_token_controller_swiftkv_route_compressed_kv_cache}
  {SRCNAME swiftkv_process_compressed_kv_Pipeline_compressed_dot_phase_loop MODELNAME swiftkv_process_compressed_kv_Pipeline_compressed_dot_phase_loop RTLNAME int4_decoder_token_controller_swiftkv_process_compressed_kv_Pipeline_compressed_dot_phase_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_mul_32s_8s_40_2_1 RTLNAME int4_decoder_token_controller_mul_32s_8s_40_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_mul_44s_15ns_58_5_1 RTLNAME int4_decoder_token_controller_mul_44s_15ns_58_5_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_sparsemux_17_3_128_1_1 RTLNAME int4_decoder_token_controller_sparsemux_17_3_128_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME int4_decoder_token_controller_sparsemux_9_2_5_1_1 RTLNAME int4_decoder_token_controller_sparsemux_9_2_5_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
      {MODELNAME int4_decoder_token_controller_frp_fifoout RTLNAME int4_decoder_token_controller_frp_fifoout BINDTYPE interface TYPE internal_frp_fifoout}
      {MODELNAME int4_decoder_token_controller_frp_pipeline_valid RTLNAME int4_decoder_token_controller_frp_pipeline_valid BINDTYPE interface TYPE internal_frp_validbits INSTNAME int4_decoder_token_controller_frp_pipeline_valid_U}
    }
  }
  {SRCNAME swiftkv_process_compressed_kv MODELNAME swiftkv_process_compressed_kv RTLNAME int4_decoder_token_controller_swiftkv_process_compressed_kv}
  {SRCNAME swiftkv_coefficient_producer_Pipeline_coefficient_token_loop MODELNAME swiftkv_coefficient_producer_Pipeline_coefficient_token_loop RTLNAME int4_decoder_token_controller_swiftkv_coefficient_producer_Pipeline_coefficient_token_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_mul_32ns_12ns_44_2_1 RTLNAME int4_decoder_token_controller_mul_32ns_12ns_44_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_mul_32s_23ns_46_2_1 RTLNAME int4_decoder_token_controller_mul_32s_23ns_46_2_1 BINDTYPE op TYPE mul IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_mul_30ns_18ns_48_5_1 RTLNAME int4_decoder_token_controller_mul_30ns_18ns_48_5_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_swiftkv_coefficient_producer_Pipeline_coefficient_token_loop_SWIFTKV_EXP2_LUTbkb RTLNAME int4_decoder_token_controller_swiftkv_coefficient_producer_Pipeline_coefficient_token_loop_SWIFTKV_EXP2_LUTbkb BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME swiftkv_reciprocal_normalization MODELNAME swiftkv_reciprocal_normalization RTLNAME int4_decoder_token_controller_swiftkv_reciprocal_normalization}
  {SRCNAME swiftkv_coefficient_producer MODELNAME swiftkv_coefficient_producer RTLNAME int4_decoder_token_controller_swiftkv_coefficient_producer}
  {SRCNAME swiftkv_broadcast_update_controls_Pipeline_broadcast_update_control_loop MODELNAME swiftkv_broadcast_update_controls_Pipeline_broadcast_update_control_loop RTLNAME int4_decoder_token_controller_swiftkv_broadcast_update_controls_Pipeline_broadcast_update_control_loop}
  {SRCNAME swiftkv_broadcast_update_controls MODELNAME swiftkv_broadcast_update_controls RTLNAME int4_decoder_token_controller_swiftkv_broadcast_update_controls}
  {SRCNAME swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop.3 MODELNAME swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop_3 RTLNAME int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop_3}
  {SRCNAME swiftkv_prepare_update_engine_phases<0> MODELNAME swiftkv_prepare_update_engine_phases_0_s RTLNAME int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_0_s}
  {SRCNAME swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop.2 MODELNAME swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop_2 RTLNAME int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop_2}
  {SRCNAME swiftkv_prepare_update_engine_phases<1> MODELNAME swiftkv_prepare_update_engine_phases_1_s RTLNAME int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_1_s}
  {SRCNAME swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop.1 MODELNAME swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop_1 RTLNAME int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop_1}
  {SRCNAME swiftkv_prepare_update_engine_phases<2> MODELNAME swiftkv_prepare_update_engine_phases_2_s RTLNAME int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_2_s}
  {SRCNAME swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop MODELNAME swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop RTLNAME int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop}
  {SRCNAME swiftkv_prepare_update_engine_phases<3> MODELNAME swiftkv_prepare_update_engine_phases_3_s RTLNAME int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_3_s}
  {SRCNAME swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop.3 MODELNAME swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop_3 RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop_3}
  {SRCNAME swiftkv_update_value_engine<0>_Pipeline_update_value_engine_phase_loop MODELNAME swiftkv_update_value_engine_0_Pipeline_update_value_engine_phase_loop RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_0_Pipeline_update_value_engine_phase_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_mul_32s_18ns_50_5_1 RTLNAME int4_decoder_token_controller_mul_32s_18ns_50_5_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 4 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME swiftkv_update_value_engine<0> MODELNAME swiftkv_update_value_engine_0_s RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_0_s}
  {SRCNAME swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop.2 MODELNAME swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop_2 RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop_2}
  {SRCNAME swiftkv_update_value_engine<1>_Pipeline_update_value_engine_phase_loop MODELNAME swiftkv_update_value_engine_1_Pipeline_update_value_engine_phase_loop RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_1_Pipeline_update_value_engine_phase_loop}
  {SRCNAME swiftkv_update_value_engine<1> MODELNAME swiftkv_update_value_engine_1_s RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_1_s}
  {SRCNAME swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop.1 MODELNAME swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop_1 RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop_1}
  {SRCNAME swiftkv_update_value_engine<2>_Pipeline_update_value_engine_phase_loop MODELNAME swiftkv_update_value_engine_2_Pipeline_update_value_engine_phase_loop RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_2_Pipeline_update_value_engine_phase_loop}
  {SRCNAME swiftkv_update_value_engine<2> MODELNAME swiftkv_update_value_engine_2_s RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_2_s}
  {SRCNAME swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop MODELNAME swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_Pipeline_initialize_weighted_value_engine_phase_loop}
  {SRCNAME swiftkv_update_value_engine<3>_Pipeline_update_value_engine_phase_loop MODELNAME swiftkv_update_value_engine_3_Pipeline_update_value_engine_phase_loop RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_3_Pipeline_update_value_engine_phase_loop}
  {SRCNAME swiftkv_update_value_engine<3> MODELNAME swiftkv_update_value_engine_3_s RTLNAME int4_decoder_token_controller_swiftkv_update_value_engine_3_s}
  {SRCNAME swiftkv_accumulate_values_split MODELNAME swiftkv_accumulate_values_split RTLNAME int4_decoder_token_controller_swiftkv_accumulate_values_split
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w59_d4_S RTLNAME int4_decoder_token_controller_fifo_w59_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME engine0_control_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w59_d4_S RTLNAME int4_decoder_token_controller_fifo_w59_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME engine1_control_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w59_d4_S RTLNAME int4_decoder_token_controller_fifo_w59_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME engine2_control_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w59_d4_S RTLNAME int4_decoder_token_controller_fifo_w59_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME engine3_control_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S RTLNAME int4_decoder_token_controller_fifo_w12_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c33_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S RTLNAME int4_decoder_token_controller_fifo_w12_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c34_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S RTLNAME int4_decoder_token_controller_fifo_w12_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c35_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S RTLNAME int4_decoder_token_controller_fifo_w12_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c36_U}
      {MODELNAME int4_decoder_token_controller_fifo_w57_d8_S RTLNAME int4_decoder_token_controller_fifo_w57_d8_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME engine0_phase_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S RTLNAME int4_decoder_token_controller_fifo_w12_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c32_U}
      {MODELNAME int4_decoder_token_controller_fifo_w57_d8_S RTLNAME int4_decoder_token_controller_fifo_w57_d8_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME engine1_phase_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S RTLNAME int4_decoder_token_controller_fifo_w12_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c31_U}
      {MODELNAME int4_decoder_token_controller_fifo_w57_d8_S RTLNAME int4_decoder_token_controller_fifo_w57_d8_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME engine2_phase_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S RTLNAME int4_decoder_token_controller_fifo_w12_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c30_U}
      {MODELNAME int4_decoder_token_controller_fifo_w57_d8_S RTLNAME int4_decoder_token_controller_fifo_w57_d8_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME engine3_phase_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S RTLNAME int4_decoder_token_controller_fifo_w12_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c_U}
    }
  }
  {SRCNAME swiftkv_update_values_and_quantize_Pipeline_attention_normalize_lane_loop MODELNAME swiftkv_update_values_and_quantize_Pipeline_attention_normalize_lane_loop RTLNAME int4_decoder_token_controller_swiftkv_update_values_and_quantize_Pipeline_attention_normalize_lane_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_mul_32s_32s_49_5_1 RTLNAME int4_decoder_token_controller_mul_32s_32s_49_5_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_sparsemux_9_2_32_1_1 RTLNAME int4_decoder_token_controller_sparsemux_9_2_32_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
    }
  }
  {SRCNAME swiftkv_update_values_and_quantize_Pipeline_attention_quantize_reverse_loop MODELNAME swiftkv_update_values_and_quantize_Pipeline_attention_quantize_reverse_loop RTLNAME int4_decoder_token_controller_swiftkv_update_values_and_quantize_Pipeline_attention_quantize_reverse_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fadd_32ns_32ns_32_7_full_dsp_1 RTLNAME int4_decoder_token_controller_fadd_32ns_32ns_32_7_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 6 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_fcmp_32ns_32ns_1_2_no_dsp_1 RTLNAME int4_decoder_token_controller_fcmp_32ns_32ns_1_2_no_dsp_1 BINDTYPE op TYPE fcmp IMPL auto LATENCY 1 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME swiftkv_update_values_and_quantize MODELNAME swiftkv_update_values_and_quantize RTLNAME int4_decoder_token_controller_swiftkv_update_values_and_quantize
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fmul_32ns_32ns_32_4_max_dsp_1 RTLNAME int4_decoder_token_controller_fmul_32ns_32ns_32_4_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_fdiv_32ns_32ns_32_12_no_dsp_1 RTLNAME int4_decoder_token_controller_fdiv_32ns_32ns_32_12_no_dsp_1 BINDTYPE op TYPE fdiv IMPL fabric LATENCY 11 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_swiftkv_update_values_and_quantize_weighted_value_engine0_RAM_2P_BRAM_1R1W RTLNAME int4_decoder_token_controller_swiftkv_update_values_and_quantize_weighted_value_engine0_RAM_2P_BRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_swiftkv_update_values_and_quantize_attention_group_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_swiftkv_update_values_and_quantize_attention_group_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME swiftkv_attention_head MODELNAME swiftkv_attention_head RTLNAME int4_decoder_token_controller_swiftkv_attention_head
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w512_d3_A RTLNAME int4_decoder_token_controller_fifo_w512_d3_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME current_record_0_val1_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d3_A RTLNAME int4_decoder_token_controller_fifo_w512_d3_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME current_record_1_val2_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d3_A RTLNAME int4_decoder_token_controller_fifo_w512_d3_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME current_record_2_val3_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d3_A RTLNAME int4_decoder_token_controller_fifo_w512_d3_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME current_record_3_val4_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d3_A RTLNAME int4_decoder_token_controller_fifo_w512_d3_A BINDTYPE storage TYPE fifo IMPL memory ALLOW_PRAGMA 1 INSTNAME current_record_4_val5_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d64_B RTLNAME int4_decoder_token_controller_fifo_w512_d64_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME cached_kv_word_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w12_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c14_U}
      {MODELNAME int4_decoder_token_controller_fifo_w40_d32_S RTLNAME int4_decoder_token_controller_fifo_w40_d32_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME key_metadata_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w40_d32_S RTLNAME int4_decoder_token_controller_fifo_w40_d32_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME value_metadata_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d32_U RTLNAME int4_decoder_token_controller_fifo_w512_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME key0_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d32_U RTLNAME int4_decoder_token_controller_fifo_w512_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME key1_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_U RTLNAME int4_decoder_token_controller_fifo_w128_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME value0_engine0_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_U RTLNAME int4_decoder_token_controller_fifo_w128_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME value0_engine1_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_U RTLNAME int4_decoder_token_controller_fifo_w128_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME value0_engine2_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_U RTLNAME int4_decoder_token_controller_fifo_w128_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME value0_engine3_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_U RTLNAME int4_decoder_token_controller_fifo_w128_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME value1_engine0_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_U RTLNAME int4_decoder_token_controller_fifo_w128_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME value1_engine1_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_U RTLNAME int4_decoder_token_controller_fifo_w128_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME value1_engine2_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_U RTLNAME int4_decoder_token_controller_fifo_w128_d32_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME value1_engine3_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S RTLNAME int4_decoder_token_controller_fifo_w32_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME score_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w12_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c13_U}
      {MODELNAME int4_decoder_token_controller_fifo_w19_d16_S RTLNAME int4_decoder_token_controller_fifo_w19_d16_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME control_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S RTLNAME int4_decoder_token_controller_fifo_w32_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME inverse_normalization_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w12_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME position_val_c_U}
    }
  }
  {SRCNAME swiftkv_run_bank MODELNAME swiftkv_run_bank RTLNAME int4_decoder_token_controller_swiftkv_run_bank
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_swiftkv_run_bank_local_cosine_RAM_1P_LUTRAM_1R1W RTLNAME int4_decoder_token_controller_swiftkv_run_bank_local_cosine_RAM_1P_LUTRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL lutram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_swiftkv_run_bank_query_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_swiftkv_run_bank_query_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_swiftkv_run_bank_q_words_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_swiftkv_run_bank_q_words_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME swiftkv_run_pe<0> MODELNAME swiftkv_run_pe_0_s RTLNAME int4_decoder_token_controller_swiftkv_run_pe_0_s}
  {SRCNAME swiftkv_run_pe<1> MODELNAME swiftkv_run_pe_1_s RTLNAME int4_decoder_token_controller_swiftkv_run_pe_1_s}
  {SRCNAME swiftkv_run_pe<2> MODELNAME swiftkv_run_pe_2_s RTLNAME int4_decoder_token_controller_swiftkv_run_pe_2_s}
  {SRCNAME swiftkv_run_pe<3> MODELNAME swiftkv_run_pe_3_s RTLNAME int4_decoder_token_controller_swiftkv_run_pe_3_s}
  {SRCNAME swiftkv_gather_attention_streams MODELNAME swiftkv_gather_attention_streams RTLNAME int4_decoder_token_controller_swiftkv_gather_attention_streams}
  {SRCNAME swiftkv_run_four_pes MODELNAME swiftkv_run_four_pes RTLNAME int4_decoder_token_controller_swiftkv_run_four_pes
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w18_d2_S RTLNAME int4_decoder_token_controller_fifo_w18_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME swiftkv_command_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w18_d2_S RTLNAME int4_decoder_token_controller_fifo_w18_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME swiftkv_command_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w18_d2_S RTLNAME int4_decoder_token_controller_fifo_w18_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME swiftkv_command_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w18_d2_S RTLNAME int4_decoder_token_controller_fifo_w18_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME swiftkv_command_pe3_U}
      {MODELNAME int4_decoder_token_controller_fifo_w19_d4_S RTLNAME int4_decoder_token_controller_fifo_w19_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME cos_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w19_d4_S RTLNAME int4_decoder_token_controller_fifo_w19_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME cos_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w19_d4_S RTLNAME int4_decoder_token_controller_fifo_w19_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME cos_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w19_d4_S RTLNAME int4_decoder_token_controller_fifo_w19_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME cos_pe3_U}
      {MODELNAME int4_decoder_token_controller_fifo_w19_d4_S RTLNAME int4_decoder_token_controller_fifo_w19_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sin_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w19_d4_S RTLNAME int4_decoder_token_controller_fifo_w19_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sin_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w19_d4_S RTLNAME int4_decoder_token_controller_fifo_w19_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sin_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w19_d4_S RTLNAME int4_decoder_token_controller_fifo_w19_d4_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME sin_pe3_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B RTLNAME int4_decoder_token_controller_fifo_w480_d4_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B RTLNAME int4_decoder_token_controller_fifo_w480_d4_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B RTLNAME int4_decoder_token_controller_fifo_w480_d4_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B RTLNAME int4_decoder_token_controller_fifo_w480_d4_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe3_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe3_U}
    }
  }
  {SRCNAME entry_proc58 MODELNAME entry_proc58 RTLNAME int4_decoder_token_controller_entry_proc58}
  {SRCNAME int4_dispatch_linear_registered_Block_entry1_proc24 MODELNAME int4_dispatch_linear_registered_Block_entry1_proc24 RTLNAME int4_decoder_token_controller_int4_dispatch_linear_registered_Block_entry1_proc24}
  {SRCNAME int4_execute_dispatch_linear_Pipeline_seed_linear_stage_with_residual_loop MODELNAME int4_execute_dispatch_linear_Pipeline_seed_linear_stage_with_residual_loop RTLNAME int4_decoder_token_controller_int4_execute_dispatch_linear_Pipeline_seed_linear_stage_with_residual_loop}
  {SRCNAME int4_swiglu_quantize_pe0_Pipeline_swiglu_word_loop_swiglu_lane_loop MODELNAME int4_swiglu_quantize_pe0_Pipeline_swiglu_word_loop_swiglu_lane_loop RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe0_Pipeline_swiglu_word_loop_swiglu_lane_loop
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fexp_32ns_32ns_32_14_full_dsp_1 RTLNAME int4_decoder_token_controller_fexp_32ns_32ns_32_14_full_dsp_1 BINDTYPE op TYPE fexp IMPL fulldsp LATENCY 13 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_sparsemux_33_4_32_1_1 RTLNAME int4_decoder_token_controller_sparsemux_33_4_32_1_1 BINDTYPE op TYPE sparsemux IMPL auto}
    }
  }
  {SRCNAME int4_swiglu_quantize_pe0_Pipeline_swiglu_quantize_reverse_loop MODELNAME int4_swiglu_quantize_pe0_Pipeline_swiglu_quantize_reverse_loop RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe0_Pipeline_swiglu_quantize_reverse_loop}
  {SRCNAME int4_swiglu_quantize_pe0 MODELNAME int4_swiglu_quantize_pe0 RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe0
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_int4_swiglu_quantize_pe0_swiglu_group_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe0_swiglu_group_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME int4_swiglu_quantize_pe1_Pipeline_swiglu_word_loop_swiglu_lane_loop MODELNAME int4_swiglu_quantize_pe1_Pipeline_swiglu_word_loop_swiglu_lane_loop RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe1_Pipeline_swiglu_word_loop_swiglu_lane_loop}
  {SRCNAME int4_swiglu_quantize_pe1_Pipeline_swiglu_quantize_reverse_loop MODELNAME int4_swiglu_quantize_pe1_Pipeline_swiglu_quantize_reverse_loop RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe1_Pipeline_swiglu_quantize_reverse_loop}
  {SRCNAME int4_swiglu_quantize_pe1 MODELNAME int4_swiglu_quantize_pe1 RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe1}
  {SRCNAME int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop MODELNAME int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop}
  {SRCNAME int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop MODELNAME int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop}
  {SRCNAME int4_swiglu_quantize_pe2 MODELNAME int4_swiglu_quantize_pe2 RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe2}
  {SRCNAME int4_swiglu_quantize_pe3_Pipeline_swiglu_word_loop_swiglu_lane_loop MODELNAME int4_swiglu_quantize_pe3_Pipeline_swiglu_word_loop_swiglu_lane_loop RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe3_Pipeline_swiglu_word_loop_swiglu_lane_loop}
  {SRCNAME int4_swiglu_quantize_pe3_Pipeline_swiglu_quantize_reverse_loop MODELNAME int4_swiglu_quantize_pe3_Pipeline_swiglu_quantize_reverse_loop RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe3_Pipeline_swiglu_quantize_reverse_loop}
  {SRCNAME int4_swiglu_quantize_pe3 MODELNAME int4_swiglu_quantize_pe3 RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_pe3}
  {SRCNAME int4_swiglu_gather_streams_Pipeline_swiglu_stream_group_loop MODELNAME int4_swiglu_gather_streams_Pipeline_swiglu_stream_group_loop RTLNAME int4_decoder_token_controller_int4_swiglu_gather_streams_Pipeline_swiglu_stream_group_loop}
  {SRCNAME int4_swiglu_gather_streams MODELNAME int4_swiglu_gather_streams RTLNAME int4_decoder_token_controller_int4_swiglu_gather_streams}
  {SRCNAME int4_swiglu_quantize_four_pes_stream MODELNAME int4_swiglu_quantize_four_pes_stream RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_four_pes_stream
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B_x RTLNAME int4_decoder_token_controller_fifo_w480_d4_B_x BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x0 RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B_x RTLNAME int4_decoder_token_controller_fifo_w480_d4_B_x BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x0 RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B_x RTLNAME int4_decoder_token_controller_fifo_w480_d4_B_x BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x0 RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B_x RTLNAME int4_decoder_token_controller_fifo_w480_d4_B_x BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe3_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x0 RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe3_U}
    }
  }
  {SRCNAME int4_swiglu_quantize_stream_4pe MODELNAME int4_swiglu_quantize_stream_4pe RTLNAME int4_decoder_token_controller_int4_swiglu_quantize_stream_4pe}
  {SRCNAME int4_rms_sumsq_pe_Pipeline_sumsq_word_loop_sumsq_lane_loop MODELNAME int4_rms_sumsq_pe_Pipeline_sumsq_word_loop_sumsq_lane_loop RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_Pipeline_sumsq_word_loop_sumsq_lane_loop}
  {SRCNAME int4_rms_sumsq_pe_Pipeline_merge_sumsq_lane_loop MODELNAME int4_rms_sumsq_pe_Pipeline_merge_sumsq_lane_loop RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_Pipeline_merge_sumsq_lane_loop}
  {SRCNAME int4_rms_sumsq_pe MODELNAME int4_rms_sumsq_pe RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fadd_32ns_32ns_32_5_no_dsp_1 RTLNAME int4_decoder_token_controller_fadd_32ns_32ns_32_5_no_dsp_1 BINDTYPE op TYPE fadd IMPL fabric LATENCY 4 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME int4_rms_sumsq_pe.10_Pipeline_sumsq_word_loop_sumsq_lane_loop MODELNAME int4_rms_sumsq_pe_10_Pipeline_sumsq_word_loop_sumsq_lane_loop RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_10_Pipeline_sumsq_word_loop_sumsq_lane_loop}
  {SRCNAME int4_rms_sumsq_pe.10_Pipeline_merge_sumsq_lane_loop MODELNAME int4_rms_sumsq_pe_10_Pipeline_merge_sumsq_lane_loop RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_10_Pipeline_merge_sumsq_lane_loop}
  {SRCNAME int4_rms_sumsq_pe.10 MODELNAME int4_rms_sumsq_pe_10 RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_10}
  {SRCNAME int4_rms_sumsq_pe.11_Pipeline_sumsq_word_loop_sumsq_lane_loop MODELNAME int4_rms_sumsq_pe_11_Pipeline_sumsq_word_loop_sumsq_lane_loop RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_11_Pipeline_sumsq_word_loop_sumsq_lane_loop}
  {SRCNAME int4_rms_sumsq_pe.11_Pipeline_merge_sumsq_lane_loop MODELNAME int4_rms_sumsq_pe_11_Pipeline_merge_sumsq_lane_loop RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_11_Pipeline_merge_sumsq_lane_loop}
  {SRCNAME int4_rms_sumsq_pe.11 MODELNAME int4_rms_sumsq_pe_11 RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_11}
  {SRCNAME int4_rms_sumsq_pe.12_Pipeline_sumsq_word_loop_sumsq_lane_loop MODELNAME int4_rms_sumsq_pe_12_Pipeline_sumsq_word_loop_sumsq_lane_loop RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_12_Pipeline_sumsq_word_loop_sumsq_lane_loop}
  {SRCNAME int4_rms_sumsq_pe.12_Pipeline_merge_sumsq_lane_loop MODELNAME int4_rms_sumsq_pe_12_Pipeline_merge_sumsq_lane_loop RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_12_Pipeline_merge_sumsq_lane_loop}
  {SRCNAME int4_rms_sumsq_pe.12 MODELNAME int4_rms_sumsq_pe_12 RTLNAME int4_decoder_token_controller_int4_rms_sumsq_pe_12}
  {SRCNAME int4_rms_merge_and_rsqrt MODELNAME int4_rms_merge_and_rsqrt RTLNAME int4_decoder_token_controller_int4_rms_merge_and_rsqrt
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_frsqrt_32ns_32ns_32_17_full_dsp_1 RTLNAME int4_decoder_token_controller_frsqrt_32ns_32ns_32_17_full_dsp_1 BINDTYPE op TYPE frsqrt IMPL fulldsp LATENCY 16 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME int4_rms_sumsq_four_pes MODELNAME int4_rms_sumsq_four_pes RTLNAME int4_decoder_token_controller_int4_rms_sumsq_four_pes
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME partial_0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME partial_1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME partial_2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME partial_3_U}
    }
  }
  {SRCNAME int4_rms_normalize_quantize_pe_Pipeline_normalize_word_loop_normalize_lane_loop MODELNAME int4_rms_normalize_quantize_pe_Pipeline_normalize_word_loop_normalize_lane_loop RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_Pipeline_normalize_word_loop_normalize_lane_loop}
  {SRCNAME int4_rms_normalize_quantize_pe_Pipeline_quantize_reverse_loop MODELNAME int4_rms_normalize_quantize_pe_Pipeline_quantize_reverse_loop RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_Pipeline_quantize_reverse_loop}
  {SRCNAME int4_rms_normalize_quantize_pe MODELNAME int4_rms_normalize_quantize_pe RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe}
  {SRCNAME int4_rms_normalize_quantize_pe.13_Pipeline_normalize_word_loop_normalize_lane_lo MODELNAME int4_rms_normalize_quantize_pe_13_Pipeline_normalize_word_loop_normalize_lane_lo RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_13_Pipeline_normalize_word_loop_normalize_lane_lo}
  {SRCNAME int4_rms_normalize_quantize_pe.13_Pipeline_quantize_reverse_loop MODELNAME int4_rms_normalize_quantize_pe_13_Pipeline_quantize_reverse_loop RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_13_Pipeline_quantize_reverse_loop}
  {SRCNAME int4_rms_normalize_quantize_pe.13 MODELNAME int4_rms_normalize_quantize_pe_13 RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_13}
  {SRCNAME int4_rms_normalize_quantize_pe.14_Pipeline_normalize_word_loop_normalize_lane_lo MODELNAME int4_rms_normalize_quantize_pe_14_Pipeline_normalize_word_loop_normalize_lane_lo RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_14_Pipeline_normalize_word_loop_normalize_lane_lo}
  {SRCNAME int4_rms_normalize_quantize_pe.14_Pipeline_quantize_reverse_loop MODELNAME int4_rms_normalize_quantize_pe_14_Pipeline_quantize_reverse_loop RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_14_Pipeline_quantize_reverse_loop}
  {SRCNAME int4_rms_normalize_quantize_pe.14 MODELNAME int4_rms_normalize_quantize_pe_14 RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_14}
  {SRCNAME int4_rms_normalize_quantize_pe.15_Pipeline_normalize_word_loop_normalize_lane_lo MODELNAME int4_rms_normalize_quantize_pe_15_Pipeline_normalize_word_loop_normalize_lane_lo RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_15_Pipeline_normalize_word_loop_normalize_lane_lo}
  {SRCNAME int4_rms_normalize_quantize_pe.15_Pipeline_quantize_reverse_loop MODELNAME int4_rms_normalize_quantize_pe_15_Pipeline_quantize_reverse_loop RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_15_Pipeline_quantize_reverse_loop}
  {SRCNAME int4_rms_normalize_quantize_pe.15 MODELNAME int4_rms_normalize_quantize_pe_15 RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_pe_15}
  {SRCNAME int4_rms_gather_streams MODELNAME int4_rms_gather_streams RTLNAME int4_decoder_token_controller_int4_rms_gather_streams}
  {SRCNAME int4_rms_normalize_quantize_four_pes_stream MODELNAME int4_rms_normalize_quantize_four_pes_stream RTLNAME int4_decoder_token_controller_int4_rms_normalize_quantize_four_pes_stream
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B_x0 RTLNAME int4_decoder_token_controller_fifo_w480_d4_B_x0 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x1 RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B_x0 RTLNAME int4_decoder_token_controller_fifo_w480_d4_B_x0 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x1 RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B_x0 RTLNAME int4_decoder_token_controller_fifo_w480_d4_B_x0 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x1 RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B_x0 RTLNAME int4_decoder_token_controller_fifo_w480_d4_B_x0 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe3_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x1 RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_pe3_U}
    }
  }
  {SRCNAME int4_rmsnorm_quantize_stream_4pe MODELNAME int4_rmsnorm_quantize_stream_4pe RTLNAME int4_decoder_token_controller_int4_rmsnorm_quantize_stream_4pe}
  {SRCNAME int4_preprocess_activation_stream MODELNAME int4_preprocess_activation_stream RTLNAME int4_decoder_token_controller_int4_preprocess_activation_stream}
  {SRCNAME int4_run_preprocess_and_linear_Block_entry13_proc MODELNAME int4_run_preprocess_and_linear_Block_entry13_proc RTLNAME int4_decoder_token_controller_int4_run_preprocess_and_linear_Block_entry13_proc}
  {SRCNAME int4_broadcast_linear_commands MODELNAME int4_broadcast_linear_commands RTLNAME int4_decoder_token_controller_int4_broadcast_linear_commands}
  {SRCNAME int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop MODELNAME int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop RTLNAME int4_decoder_token_controller_int4_broadcast_activation_Pipeline_broadcast_activation_seed_loop}
  {SRCNAME int4_broadcast_activation MODELNAME int4_broadcast_activation RTLNAME int4_decoder_token_controller_int4_broadcast_activation}
  {SRCNAME entry_proc56 MODELNAME entry_proc56 RTLNAME int4_decoder_token_controller_entry_proc56}
  {SRCNAME int4_run_pe_dataflow<0>_Block_entry2_proc20 MODELNAME int4_run_pe_dataflow_0_Block_entry2_proc20 RTLNAME int4_decoder_token_controller_int4_run_pe_dataflow_0_Block_entry2_proc20
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_mul_6ns_6ns_12_1_1 RTLNAME int4_decoder_token_controller_mul_6ns_6ns_12_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME int4_stream_pe_inputs MODELNAME int4_stream_pe_inputs RTLNAME int4_decoder_token_controller_int4_stream_pe_inputs}
  {SRCNAME int4_cache_and_replay_activation<0>_Pipeline_cache_local_activation_loop MODELNAME int4_cache_and_replay_activation_0_Pipeline_cache_local_activation_loop RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_0_Pipeline_cache_local_activation_loop}
  {SRCNAME int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl.3 MODELNAME int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl_3 RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl_3}
  {SRCNAME int4_cache_and_replay_activation<0> MODELNAME int4_cache_and_replay_activation_0_s RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_0_s
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_mul_6ns_9ns_15_1_1 RTLNAME int4_decoder_token_controller_mul_6ns_9ns_15_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_int4_cache_and_replay_activation_0_s_activation_cache_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_0_s_activation_cache_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_int4_cache_and_replay_activation_0_s_scale_cache_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_0_s_scale_cache_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME int4_stream_integer_blocks_Pipeline_integer_local_tile_loop_integer_col_tile_loo MODELNAME int4_stream_integer_blocks_Pipeline_integer_local_tile_loop_integer_col_tile_loo RTLNAME int4_decoder_token_controller_int4_stream_integer_blocks_Pipeline_integer_local_tile_loop_integer_col_tile_loo
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_add_27ns_27s_27_2_1 RTLNAME int4_decoder_token_controller_add_27ns_27s_27_2_1 BINDTYPE op TYPE add IMPL fabric LATENCY 1}
      {MODELNAME int4_decoder_token_controller_mul_27s_15s_42_5_1 RTLNAME int4_decoder_token_controller_mul_27s_15s_42_5_1 BINDTYPE op TYPE mul IMPL dsp LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_mac_muladd_27s_15s_42s_43_5_1 RTLNAME int4_decoder_token_controller_mac_muladd_27s_15s_42s_43_5_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_mac_muladd_27s_15s_43s_43_5_1 RTLNAME int4_decoder_token_controller_mac_muladd_27s_15s_43s_43_5_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_mac_muladd_27s_15s_43s_44_5_1 RTLNAME int4_decoder_token_controller_mac_muladd_27s_15s_43s_44_5_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_mac_muladd_27s_15s_44s_45_5_1 RTLNAME int4_decoder_token_controller_mac_muladd_27s_15s_44s_45_5_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_mac_muladd_27s_15s_45s_46_5_1 RTLNAME int4_decoder_token_controller_mac_muladd_27s_15s_45s_46_5_1 BINDTYPE op TYPE all IMPL dsp_slice LATENCY 4 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME int4_stream_integer_blocks MODELNAME int4_stream_integer_blocks RTLNAME int4_decoder_token_controller_int4_stream_integer_blocks
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_mul_6ns_14ns_20_1_1 RTLNAME int4_decoder_token_controller_mul_6ns_14ns_20_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME int4_dequantize_final_blocks_Pipeline_dequant_local_tile_loop_dequant_flat_block MODELNAME int4_dequantize_final_blocks_Pipeline_dequant_local_tile_loop_dequant_flat_block RTLNAME int4_decoder_token_controller_int4_dequantize_final_blocks_Pipeline_dequant_local_tile_loop_dequant_flat_block
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_sitofp_32s_32_5_no_dsp_1 RTLNAME int4_decoder_token_controller_sitofp_32s_32_5_no_dsp_1 BINDTYPE op TYPE sitofp IMPL auto LATENCY 4 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_int4_dequantize_final_blocks_Pipeline_dequant_local_tile_loop_dequant_flat_blcud RTLNAME int4_decoder_token_controller_int4_dequantize_final_blocks_Pipeline_dequant_local_tile_loop_dequant_flat_blcud BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME int4_dequantize_final_blocks MODELNAME int4_dequantize_final_blocks RTLNAME int4_decoder_token_controller_int4_dequantize_final_blocks}
  {SRCNAME int4_pack_dequantized_outputs_Pipeline_pack_dequantized_value_loop MODELNAME int4_pack_dequantized_outputs_Pipeline_pack_dequantized_value_loop RTLNAME int4_decoder_token_controller_int4_pack_dequantized_outputs_Pipeline_pack_dequantized_value_loop}
  {SRCNAME int4_pack_dequantized_outputs MODELNAME int4_pack_dequantized_outputs RTLNAME int4_decoder_token_controller_int4_pack_dequantized_outputs}
  {SRCNAME int4_write_outputs.9_Pipeline_write_output_direct_loop MODELNAME int4_write_outputs_9_Pipeline_write_output_direct_loop RTLNAME int4_decoder_token_controller_int4_write_outputs_9_Pipeline_write_output_direct_loop}
  {SRCNAME int4_write_outputs.9_Pipeline_fused_residual_add_loop MODELNAME int4_write_outputs_9_Pipeline_fused_residual_add_loop RTLNAME int4_decoder_token_controller_int4_write_outputs_9_Pipeline_fused_residual_add_loop}
  {SRCNAME int4_write_outputs.9 MODELNAME int4_write_outputs_9 RTLNAME int4_decoder_token_controller_int4_write_outputs_9}
  {SRCNAME int4_run_pe_dataflow<0> MODELNAME int4_run_pe_dataflow_0_s RTLNAME int4_decoder_token_controller_int4_run_pe_dataflow_0_s
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w11_d5_S RTLNAME int4_decoder_token_controller_fifo_w11_d5_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME idx1_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w12_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mul_ln867_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d5_S RTLNAME int4_decoder_token_controller_fifo_w1_d5_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME output_fxp_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d6_S RTLNAME int4_decoder_token_controller_fifo_w1_d6_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME fuse_residual_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S RTLNAME int4_decoder_token_controller_fifo_w6_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c17_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S RTLNAME int4_decoder_token_controller_fifo_w6_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c21_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d16384_U RTLNAME int4_decoder_token_controller_fifo_w512_d16384_U BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME weight_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d2_B RTLNAME int4_decoder_token_controller_fifo_w480_d2_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME replay_activation_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME replay_scale_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S RTLNAME int4_decoder_token_controller_fifo_w6_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c16_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S RTLNAME int4_decoder_token_controller_fifo_w6_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c20_U}
      {MODELNAME int4_decoder_token_controller_fifo_w92_d64_S RTLNAME int4_decoder_token_controller_fifo_w92_d64_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME group_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S RTLNAME int4_decoder_token_controller_fifo_w6_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S RTLNAME int4_decoder_token_controller_fifo_w6_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c19_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_B RTLNAME int4_decoder_token_controller_fifo_w128_d32_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME final_block_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S RTLNAME int4_decoder_token_controller_fifo_w6_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c18_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d16_B RTLNAME int4_decoder_token_controller_fifo_w512_d16_B BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME output_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S RTLNAME int4_decoder_token_controller_fifo_w6_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c_U}
    }
  }
  {SRCNAME entry_proc55 MODELNAME entry_proc55 RTLNAME int4_decoder_token_controller_entry_proc55}
  {SRCNAME int4_run_pe_dataflow<1>_Block_entry2_proc21 MODELNAME int4_run_pe_dataflow_1_Block_entry2_proc21 RTLNAME int4_decoder_token_controller_int4_run_pe_dataflow_1_Block_entry2_proc21}
  {SRCNAME int4_stream_pe_inputs.16 MODELNAME int4_stream_pe_inputs_16 RTLNAME int4_decoder_token_controller_int4_stream_pe_inputs_16}
  {SRCNAME int4_cache_and_replay_activation<1>_Pipeline_cache_local_activation_loop MODELNAME int4_cache_and_replay_activation_1_Pipeline_cache_local_activation_loop RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_1_Pipeline_cache_local_activation_loop}
  {SRCNAME int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl.2 MODELNAME int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl_2 RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl_2}
  {SRCNAME int4_cache_and_replay_activation<1> MODELNAME int4_cache_and_replay_activation_1_s RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_1_s}
  {SRCNAME int4_stream_integer_blocks.5_Pipeline_integer_local_tile_loop_integer_col_tile_l MODELNAME int4_stream_integer_blocks_5_Pipeline_integer_local_tile_loop_integer_col_tile_l RTLNAME int4_decoder_token_controller_int4_stream_integer_blocks_5_Pipeline_integer_local_tile_loop_integer_col_tile_l}
  {SRCNAME int4_stream_integer_blocks.5 MODELNAME int4_stream_integer_blocks_5 RTLNAME int4_decoder_token_controller_int4_stream_integer_blocks_5}
  {SRCNAME int4_dequantize_final_blocks.17_Pipeline_dequant_local_tile_loop_dequant_flat_bl MODELNAME int4_dequantize_final_blocks_17_Pipeline_dequant_local_tile_loop_dequant_flat_bl RTLNAME int4_decoder_token_controller_int4_dequantize_final_blocks_17_Pipeline_dequant_local_tile_loop_dequant_flat_bl}
  {SRCNAME int4_dequantize_final_blocks.17 MODELNAME int4_dequantize_final_blocks_17 RTLNAME int4_decoder_token_controller_int4_dequantize_final_blocks_17}
  {SRCNAME int4_pack_dequantized_outputs.6_Pipeline_pack_dequantized_value_loop MODELNAME int4_pack_dequantized_outputs_6_Pipeline_pack_dequantized_value_loop RTLNAME int4_decoder_token_controller_int4_pack_dequantized_outputs_6_Pipeline_pack_dequantized_value_loop}
  {SRCNAME int4_pack_dequantized_outputs.6 MODELNAME int4_pack_dequantized_outputs_6 RTLNAME int4_decoder_token_controller_int4_pack_dequantized_outputs_6}
  {SRCNAME int4_write_outputs.8_Pipeline_write_output_direct_loop MODELNAME int4_write_outputs_8_Pipeline_write_output_direct_loop RTLNAME int4_decoder_token_controller_int4_write_outputs_8_Pipeline_write_output_direct_loop}
  {SRCNAME int4_write_outputs.8_Pipeline_fused_residual_add_loop MODELNAME int4_write_outputs_8_Pipeline_fused_residual_add_loop RTLNAME int4_decoder_token_controller_int4_write_outputs_8_Pipeline_fused_residual_add_loop}
  {SRCNAME int4_write_outputs.8 MODELNAME int4_write_outputs_8 RTLNAME int4_decoder_token_controller_int4_write_outputs_8}
  {SRCNAME int4_run_pe_dataflow<1> MODELNAME int4_run_pe_dataflow_1_s RTLNAME int4_decoder_token_controller_int4_run_pe_dataflow_1_s
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w11_d5_S_x RTLNAME int4_decoder_token_controller_fifo_w11_d5_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME idx1_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w12_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mul_ln867_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d5_S_x RTLNAME int4_decoder_token_controller_fifo_w1_d5_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME output_fxp_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d6_S_x RTLNAME int4_decoder_token_controller_fifo_w1_d6_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME fuse_residual_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c17_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c21_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d16384_U_x RTLNAME int4_decoder_token_controller_fifo_w512_d16384_U_x BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME weight_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d2_B_x RTLNAME int4_decoder_token_controller_fifo_w480_d2_B_x BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME replay_activation_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME replay_scale_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c16_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c20_U}
      {MODELNAME int4_decoder_token_controller_fifo_w92_d64_S_x RTLNAME int4_decoder_token_controller_fifo_w92_d64_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME group_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c19_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_B_x RTLNAME int4_decoder_token_controller_fifo_w128_d32_B_x BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME final_block_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c18_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d16_B_x RTLNAME int4_decoder_token_controller_fifo_w512_d16_B_x BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME output_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c_U}
    }
  }
  {SRCNAME entry_proc54 MODELNAME entry_proc54 RTLNAME int4_decoder_token_controller_entry_proc54}
  {SRCNAME int4_run_pe_dataflow<2>_Block_entry2_proc22 MODELNAME int4_run_pe_dataflow_2_Block_entry2_proc22 RTLNAME int4_decoder_token_controller_int4_run_pe_dataflow_2_Block_entry2_proc22}
  {SRCNAME int4_stream_pe_inputs.18 MODELNAME int4_stream_pe_inputs_18 RTLNAME int4_decoder_token_controller_int4_stream_pe_inputs_18}
  {SRCNAME int4_cache_and_replay_activation<2>_Pipeline_cache_local_activation_loop MODELNAME int4_cache_and_replay_activation_2_Pipeline_cache_local_activation_loop RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_2_Pipeline_cache_local_activation_loop}
  {SRCNAME int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl.1 MODELNAME int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl_1 RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl_1}
  {SRCNAME int4_cache_and_replay_activation<2> MODELNAME int4_cache_and_replay_activation_2_s RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_2_s}
  {SRCNAME int4_stream_integer_blocks.3_Pipeline_integer_local_tile_loop_integer_col_tile_l MODELNAME int4_stream_integer_blocks_3_Pipeline_integer_local_tile_loop_integer_col_tile_l RTLNAME int4_decoder_token_controller_int4_stream_integer_blocks_3_Pipeline_integer_local_tile_loop_integer_col_tile_l}
  {SRCNAME int4_stream_integer_blocks.3 MODELNAME int4_stream_integer_blocks_3 RTLNAME int4_decoder_token_controller_int4_stream_integer_blocks_3}
  {SRCNAME int4_dequantize_final_blocks.19_Pipeline_dequant_local_tile_loop_dequant_flat_bl MODELNAME int4_dequantize_final_blocks_19_Pipeline_dequant_local_tile_loop_dequant_flat_bl RTLNAME int4_decoder_token_controller_int4_dequantize_final_blocks_19_Pipeline_dequant_local_tile_loop_dequant_flat_bl}
  {SRCNAME int4_dequantize_final_blocks.19 MODELNAME int4_dequantize_final_blocks_19 RTLNAME int4_decoder_token_controller_int4_dequantize_final_blocks_19}
  {SRCNAME int4_pack_dequantized_outputs.4_Pipeline_pack_dequantized_value_loop MODELNAME int4_pack_dequantized_outputs_4_Pipeline_pack_dequantized_value_loop RTLNAME int4_decoder_token_controller_int4_pack_dequantized_outputs_4_Pipeline_pack_dequantized_value_loop}
  {SRCNAME int4_pack_dequantized_outputs.4 MODELNAME int4_pack_dequantized_outputs_4 RTLNAME int4_decoder_token_controller_int4_pack_dequantized_outputs_4}
  {SRCNAME int4_write_outputs.7_Pipeline_write_output_direct_loop MODELNAME int4_write_outputs_7_Pipeline_write_output_direct_loop RTLNAME int4_decoder_token_controller_int4_write_outputs_7_Pipeline_write_output_direct_loop}
  {SRCNAME int4_write_outputs.7_Pipeline_fused_residual_add_loop MODELNAME int4_write_outputs_7_Pipeline_fused_residual_add_loop RTLNAME int4_decoder_token_controller_int4_write_outputs_7_Pipeline_fused_residual_add_loop}
  {SRCNAME int4_write_outputs.7 MODELNAME int4_write_outputs_7 RTLNAME int4_decoder_token_controller_int4_write_outputs_7}
  {SRCNAME int4_run_pe_dataflow<2> MODELNAME int4_run_pe_dataflow_2_s RTLNAME int4_decoder_token_controller_int4_run_pe_dataflow_2_s
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w11_d5_S_x0 RTLNAME int4_decoder_token_controller_fifo_w11_d5_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME idx1_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S_x2 RTLNAME int4_decoder_token_controller_fifo_w12_d2_S_x2 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mul_ln867_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d5_S_x0 RTLNAME int4_decoder_token_controller_fifo_w1_d5_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME output_fxp_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d6_S_x0 RTLNAME int4_decoder_token_controller_fifo_w1_d6_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME fuse_residual_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c17_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c21_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d16384_U_x0 RTLNAME int4_decoder_token_controller_fifo_w512_d16384_U_x0 BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME weight_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d2_B_x0 RTLNAME int4_decoder_token_controller_fifo_w480_d2_B_x0 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME replay_activation_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x2 RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x2 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME replay_scale_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c16_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c20_U}
      {MODELNAME int4_decoder_token_controller_fifo_w92_d64_S_x0 RTLNAME int4_decoder_token_controller_fifo_w92_d64_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME group_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c19_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_B_x0 RTLNAME int4_decoder_token_controller_fifo_w128_d32_B_x0 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME final_block_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c18_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d16_B_x0 RTLNAME int4_decoder_token_controller_fifo_w512_d16_B_x0 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME output_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x0 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c_U}
    }
  }
  {SRCNAME entry_proc MODELNAME entry_proc RTLNAME int4_decoder_token_controller_entry_proc}
  {SRCNAME int4_run_pe_dataflow<3>_Block_entry2_proc23 MODELNAME int4_run_pe_dataflow_3_Block_entry2_proc23 RTLNAME int4_decoder_token_controller_int4_run_pe_dataflow_3_Block_entry2_proc23}
  {SRCNAME int4_stream_pe_inputs.20 MODELNAME int4_stream_pe_inputs_20 RTLNAME int4_decoder_token_controller_int4_stream_pe_inputs_20}
  {SRCNAME int4_cache_and_replay_activation<3>_Pipeline_cache_local_activation_loop MODELNAME int4_cache_and_replay_activation_3_Pipeline_cache_local_activation_loop RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_3_Pipeline_cache_local_activation_loop}
  {SRCNAME int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl MODELNAME int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_Pipeline_replay_local_activation_tile_loop_repl}
  {SRCNAME int4_cache_and_replay_activation<3> MODELNAME int4_cache_and_replay_activation_3_s RTLNAME int4_decoder_token_controller_int4_cache_and_replay_activation_3_s}
  {SRCNAME int4_stream_integer_blocks.1_Pipeline_integer_local_tile_loop_integer_col_tile_l MODELNAME int4_stream_integer_blocks_1_Pipeline_integer_local_tile_loop_integer_col_tile_l RTLNAME int4_decoder_token_controller_int4_stream_integer_blocks_1_Pipeline_integer_local_tile_loop_integer_col_tile_l}
  {SRCNAME int4_stream_integer_blocks.1 MODELNAME int4_stream_integer_blocks_1 RTLNAME int4_decoder_token_controller_int4_stream_integer_blocks_1}
  {SRCNAME int4_dequantize_final_blocks.21_Pipeline_dequant_local_tile_loop_dequant_flat_bl MODELNAME int4_dequantize_final_blocks_21_Pipeline_dequant_local_tile_loop_dequant_flat_bl RTLNAME int4_decoder_token_controller_int4_dequantize_final_blocks_21_Pipeline_dequant_local_tile_loop_dequant_flat_bl}
  {SRCNAME int4_dequantize_final_blocks.21 MODELNAME int4_dequantize_final_blocks_21 RTLNAME int4_decoder_token_controller_int4_dequantize_final_blocks_21}
  {SRCNAME int4_pack_dequantized_outputs.2_Pipeline_pack_dequantized_value_loop MODELNAME int4_pack_dequantized_outputs_2_Pipeline_pack_dequantized_value_loop RTLNAME int4_decoder_token_controller_int4_pack_dequantized_outputs_2_Pipeline_pack_dequantized_value_loop}
  {SRCNAME int4_pack_dequantized_outputs.2 MODELNAME int4_pack_dequantized_outputs_2 RTLNAME int4_decoder_token_controller_int4_pack_dequantized_outputs_2}
  {SRCNAME int4_write_outputs_Pipeline_write_output_direct_loop MODELNAME int4_write_outputs_Pipeline_write_output_direct_loop RTLNAME int4_decoder_token_controller_int4_write_outputs_Pipeline_write_output_direct_loop}
  {SRCNAME int4_write_outputs_Pipeline_fused_residual_add_loop MODELNAME int4_write_outputs_Pipeline_fused_residual_add_loop RTLNAME int4_decoder_token_controller_int4_write_outputs_Pipeline_fused_residual_add_loop}
  {SRCNAME int4_write_outputs MODELNAME int4_write_outputs RTLNAME int4_decoder_token_controller_int4_write_outputs}
  {SRCNAME int4_run_pe_dataflow<3> MODELNAME int4_run_pe_dataflow_3_s RTLNAME int4_decoder_token_controller_int4_run_pe_dataflow_3_s
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w11_d5_S_x1 RTLNAME int4_decoder_token_controller_fifo_w11_d5_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME idx1_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w12_d2_S_x3 RTLNAME int4_decoder_token_controller_fifo_w12_d2_S_x3 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME mul_ln867_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d5_S_x1 RTLNAME int4_decoder_token_controller_fifo_w1_d5_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME output_fxp_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d6_S_x1 RTLNAME int4_decoder_token_controller_fifo_w1_d6_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME fuse_residual_loc_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c17_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c21_channel_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d16384_U_x1 RTLNAME int4_decoder_token_controller_fifo_w512_d16384_U_x1 BINDTYPE storage TYPE fifo IMPL uram ALLOW_PRAGMA 1 INSTNAME weight_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d2_B_x1 RTLNAME int4_decoder_token_controller_fifo_w480_d2_B_x1 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME replay_activation_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x3 RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x3 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME replay_scale_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c16_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c20_U}
      {MODELNAME int4_decoder_token_controller_fifo_w92_d64_S_x1 RTLNAME int4_decoder_token_controller_fifo_w92_d64_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME group_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME input_tiles_loc_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c19_U}
      {MODELNAME int4_decoder_token_controller_fifo_w128_d32_B_x1 RTLNAME int4_decoder_token_controller_fifo_w128_d32_B_x1 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME final_block_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c18_U}
      {MODELNAME int4_decoder_token_controller_fifo_w512_d16_B_x1 RTLNAME int4_decoder_token_controller_fifo_w512_d16_B_x1 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME output_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 RTLNAME int4_decoder_token_controller_fifo_w6_d2_S_x1 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME local_tiles_loc_c_U}
    }
  }
  {SRCNAME int4_run_four_pes MODELNAME int4_run_four_pes RTLNAME int4_decoder_token_controller_int4_run_four_pes
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w14_d2_S RTLNAME int4_decoder_token_controller_fifo_w14_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME linear_command_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w14_d2_S RTLNAME int4_decoder_token_controller_fifo_w14_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME linear_command_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w14_d2_S RTLNAME int4_decoder_token_controller_fifo_w14_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME linear_command_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w14_d2_S RTLNAME int4_decoder_token_controller_fifo_w14_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME linear_command_pe3_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d2_B_x2 RTLNAME int4_decoder_token_controller_fifo_w480_d2_B_x2 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d2_B_x2 RTLNAME int4_decoder_token_controller_fifo_w480_d2_B_x2 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d2_B_x2 RTLNAME int4_decoder_token_controller_fifo_w480_d2_B_x2 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w480_d2_B_x2 RTLNAME int4_decoder_token_controller_fifo_w480_d2_B_x2 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_pe3_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x4 RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x4 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME activation_scale_pe0_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x4 RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x4 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME activation_scale_pe1_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x4 RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x4 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME activation_scale_pe2_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d2_S_x4 RTLNAME int4_decoder_token_controller_fifo_w32_d2_S_x4 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME activation_scale_pe3_U}
    }
  }
  {SRCNAME int4_linear_4pe_from_stream MODELNAME int4_linear_4pe_from_stream RTLNAME int4_decoder_token_controller_int4_linear_4pe_from_stream}
  {SRCNAME int4_run_preprocess_and_linear MODELNAME int4_run_preprocess_and_linear RTLNAME int4_decoder_token_controller_int4_run_preprocess_and_linear
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w480_d4_B_x1 RTLNAME int4_decoder_token_controller_fifo_w480_d4_B_x1 BINDTYPE storage TYPE fifo IMPL bram ALLOW_PRAGMA 1 INSTNAME quantized_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w32_d4_S_x2 RTLNAME int4_decoder_token_controller_fifo_w32_d4_S_x2 BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME scale_stream_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d2_S RTLNAME int4_decoder_token_controller_fifo_w1_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME icmp_ln113_loc_i_channel_U}
    }
  }
  {SRCNAME int4_route_linear_projection<7>_Pipeline_route_linear_projection_loop MODELNAME int4_route_linear_projection_7_Pipeline_route_linear_projection_loop RTLNAME int4_decoder_token_controller_int4_route_linear_projection_7_Pipeline_route_linear_projection_loop}
  {SRCNAME int4_route_linear_projection<7> MODELNAME int4_route_linear_projection_7_s RTLNAME int4_decoder_token_controller_int4_route_linear_projection_7_s}
  {SRCNAME int4_route_linear_projection<5> MODELNAME int4_route_linear_projection_5_s RTLNAME int4_decoder_token_controller_int4_route_linear_projection_5_s}
  {SRCNAME int4_route_linear_projection<4> MODELNAME int4_route_linear_projection_4_s RTLNAME int4_decoder_token_controller_int4_route_linear_projection_4_s}
  {SRCNAME int4_route_linear_projection<2> MODELNAME int4_route_linear_projection_2_s RTLNAME int4_decoder_token_controller_int4_route_linear_projection_2_s}
  {SRCNAME int4_route_linear_projection<1> MODELNAME int4_route_linear_projection_1_s RTLNAME int4_decoder_token_controller_int4_route_linear_projection_1_s}
  {SRCNAME int4_route_linear_projection<6> MODELNAME int4_route_linear_projection_6_s RTLNAME int4_decoder_token_controller_int4_route_linear_projection_6_s}
  {SRCNAME int4_route_linear_projection<0> MODELNAME int4_route_linear_projection_0_s RTLNAME int4_decoder_token_controller_int4_route_linear_projection_0_s}
  {SRCNAME int4_execute_dispatch_linear MODELNAME int4_execute_dispatch_linear RTLNAME int4_decoder_token_controller_int4_execute_dispatch_linear}
  {SRCNAME int4_dispatch_linear_registered MODELNAME int4_dispatch_linear_registered RTLNAME int4_decoder_token_controller_int4_dispatch_linear_registered
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_fifo_w64_d3_S RTLNAME int4_decoder_token_controller_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME weight_bank0_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w64_d3_S RTLNAME int4_decoder_token_controller_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME weight_bank1_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w64_d3_S RTLNAME int4_decoder_token_controller_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME weight_bank2_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w64_d3_S RTLNAME int4_decoder_token_controller_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME weight_bank3_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w64_d3_S RTLNAME int4_decoder_token_controller_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME logits_pe0_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w64_d3_S RTLNAME int4_decoder_token_controller_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME logits_pe1_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w64_d3_S RTLNAME int4_decoder_token_controller_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME logits_pe2_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w64_d3_S RTLNAME int4_decoder_token_controller_fifo_w64_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME logits_pe3_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w1_d3_S RTLNAME int4_decoder_token_controller_fifo_w1_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME controller_run_linear_in_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w3_d3_S RTLNAME int4_decoder_token_controller_fifo_w3_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME controller_linear_mode_in_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w6_d3_S RTLNAME int4_decoder_token_controller_fifo_w6_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME controller_layer_index_in_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w13_d3_S RTLNAME int4_decoder_token_controller_fifo_w13_d3_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME idx_c_U}
      {MODELNAME int4_decoder_token_controller_fifo_w2_d2_S RTLNAME int4_decoder_token_controller_fifo_w2_d2_S BINDTYPE storage TYPE fifo IMPL srl ALLOW_PRAGMA 1 INSTNAME command_stream_U}
    }
  }
  {SRCNAME int4_store_residual_4ddr_Pipeline_store_residual_word_loop MODELNAME int4_store_residual_4ddr_Pipeline_store_residual_word_loop RTLNAME int4_decoder_token_controller_int4_store_residual_4ddr_Pipeline_store_residual_word_loop}
  {SRCNAME int4_store_residual_4ddr MODELNAME int4_store_residual_4ddr RTLNAME int4_decoder_token_controller_int4_store_residual_4ddr}
  {SRCNAME int4_decoder_token_controller MODELNAME int4_decoder_token_controller RTLNAME int4_decoder_token_controller IS_TOP 1
    SUBMODULES {
      {MODELNAME int4_decoder_token_controller_rope_lut_RAM_1P_URAM_2R1W RTLNAME int4_decoder_token_controller_rope_lut_RAM_1P_URAM_2R1W BINDTYPE storage TYPE ram_1p IMPL uram LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_model_scale_cache0_RAM_1P_URAM_1R1W RTLNAME int4_decoder_token_controller_model_scale_cache0_RAM_1P_URAM_1R1W BINDTYPE storage TYPE ram_1p IMPL uram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_model_norm_cache0_RAM_1P_URAM_2R1W RTLNAME int4_decoder_token_controller_model_norm_cache0_RAM_1P_URAM_2R1W BINDTYPE storage TYPE ram_1p IMPL uram LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_residual_buffer0_RAM_2P_BRAM_1R1W RTLNAME int4_decoder_token_controller_residual_buffer0_RAM_2P_BRAM_1R1W BINDTYPE storage TYPE ram_2p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_linear_stage0_RAM_2P_URAM_1R1W RTLNAME int4_decoder_token_controller_linear_stage0_RAM_2P_URAM_1R1W BINDTYPE storage TYPE ram_2p IMPL uram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_q_pe0_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_q_pe0_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_gate_pe0_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_gate_pe0_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_activation_q_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_activation_q_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_activation_scale_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_activation_scale_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_current_cos_RAM_1P_BRAM_1R1W RTLNAME int4_decoder_token_controller_current_cos_RAM_1P_BRAM_1R1W BINDTYPE storage TYPE ram_1p IMPL bram LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME int4_decoder_token_controller_gmem0_m_axi RTLNAME int4_decoder_token_controller_gmem0_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME int4_decoder_token_controller_gmem1_m_axi RTLNAME int4_decoder_token_controller_gmem1_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME int4_decoder_token_controller_gmem2_m_axi RTLNAME int4_decoder_token_controller_gmem2_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME int4_decoder_token_controller_gmem3_m_axi RTLNAME int4_decoder_token_controller_gmem3_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME int4_decoder_token_controller_control_s_axi RTLNAME int4_decoder_token_controller_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
