// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module int4_decoder_token_controller_int4_route_linear_projection_5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        linear_stage0_address0,
        linear_stage0_ce0,
        linear_stage0_q0,
        linear_stage1_address0,
        linear_stage1_ce0,
        linear_stage1_q0,
        linear_stage2_address0,
        linear_stage2_ce0,
        linear_stage2_q0,
        linear_stage3_address0,
        linear_stage3_ce0,
        linear_stage3_q0,
        output0_address0,
        output0_ce0,
        output0_we0,
        output0_d0,
        output1_address0,
        output1_ce0,
        output1_we0,
        output1_d0,
        output2_address0,
        output2_ce0,
        output2_we0,
        output2_d0,
        output3_address0,
        output3_ce0,
        output3_we0,
        output3_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] linear_stage0_address0;
output   linear_stage0_ce0;
input  [511:0] linear_stage0_q0;
output  [8:0] linear_stage1_address0;
output   linear_stage1_ce0;
input  [511:0] linear_stage1_q0;
output  [8:0] linear_stage2_address0;
output   linear_stage2_ce0;
input  [511:0] linear_stage2_q0;
output  [8:0] linear_stage3_address0;
output   linear_stage3_ce0;
input  [511:0] linear_stage3_q0;
output  [7:0] output0_address0;
output   output0_ce0;
output   output0_we0;
output  [511:0] output0_d0;
output  [7:0] output1_address0;
output   output1_ce0;
output   output1_we0;
output  [511:0] output1_d0;
output  [7:0] output2_address0;
output   output2_ce0;
output   output2_we0;
output  [511:0] output2_d0;
output  [7:0] output3_address0;
output   output3_ce0;
output   output3_we0;
output  [511:0] output3_d0;

reg ap_idle;
reg linear_stage0_ce0;
reg linear_stage1_ce0;
reg linear_stage2_ce0;
reg linear_stage3_ce0;
reg output0_ce0;
reg output0_we0;
reg output1_ce0;
reg output1_we0;
reg output2_ce0;
reg output2_we0;
reg output3_ce0;
reg output3_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln157_fu_166_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln157_fu_178_p1;
reg   [63:0] zext_ln157_reg_202;
reg   [63:0] zext_ln157_reg_202_pp0_iter1_reg;
reg   [511:0] linear_stage0_load_reg_230;
reg   [511:0] linear_stage1_load_reg_235;
reg   [511:0] linear_stage2_load_reg_240;
reg   [511:0] linear_stage3_load_reg_245;
wire    ap_block_pp0_stage0;
reg   [7:0] word_fu_50;
wire   [7:0] add_ln157_fu_172_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_word_19;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 word_fu_50 = 8'd0;
#0 ap_done_reg = 1'b0;
end

int4_decoder_token_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln157_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            word_fu_50 <= add_ln157_fu_172_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            word_fu_50 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        linear_stage0_load_reg_230 <= linear_stage0_q0;
        linear_stage1_load_reg_235 <= linear_stage1_q0;
        linear_stage2_load_reg_240 <= linear_stage2_q0;
        linear_stage3_load_reg_245 <= linear_stage3_q0;
        zext_ln157_reg_202[7 : 0] <= zext_ln157_fu_178_p1[7 : 0];
        zext_ln157_reg_202_pp0_iter1_reg[7 : 0] <= zext_ln157_reg_202[7 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln157_fu_166_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_word_19 = 8'd0;
    end else begin
        ap_sig_allocacmp_word_19 = word_fu_50;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linear_stage0_ce0 = 1'b1;
    end else begin
        linear_stage0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linear_stage1_ce0 = 1'b1;
    end else begin
        linear_stage1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linear_stage2_ce0 = 1'b1;
    end else begin
        linear_stage2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linear_stage3_ce0 = 1'b1;
    end else begin
        linear_stage3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output0_ce0 = 1'b1;
    end else begin
        output0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output0_we0 = 1'b1;
    end else begin
        output0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output1_ce0 = 1'b1;
    end else begin
        output1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output1_we0 = 1'b1;
    end else begin
        output1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output2_ce0 = 1'b1;
    end else begin
        output2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output2_we0 = 1'b1;
    end else begin
        output2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output3_ce0 = 1'b1;
    end else begin
        output3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        output3_we0 = 1'b1;
    end else begin
        output3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln157_fu_172_p2 = (ap_sig_allocacmp_word_19 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln157_fu_166_p2 = ((ap_sig_allocacmp_word_19 == 8'd176) ? 1'b1 : 1'b0);

assign linear_stage0_address0 = zext_ln157_fu_178_p1;

assign linear_stage1_address0 = zext_ln157_fu_178_p1;

assign linear_stage2_address0 = zext_ln157_fu_178_p1;

assign linear_stage3_address0 = zext_ln157_fu_178_p1;

assign output0_address0 = zext_ln157_reg_202_pp0_iter1_reg;

assign output0_d0 = linear_stage0_load_reg_230;

assign output1_address0 = zext_ln157_reg_202_pp0_iter1_reg;

assign output1_d0 = linear_stage1_load_reg_235;

assign output2_address0 = zext_ln157_reg_202_pp0_iter1_reg;

assign output2_d0 = linear_stage2_load_reg_240;

assign output3_address0 = zext_ln157_reg_202_pp0_iter1_reg;

assign output3_d0 = linear_stage3_load_reg_245;

assign zext_ln157_fu_178_p1 = ap_sig_allocacmp_word_19;

always @ (posedge ap_clk) begin
    zext_ln157_reg_202[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln157_reg_202_pp0_iter1_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //int4_decoder_token_controller_int4_route_linear_projection_5_s
