// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module int4_decoder_token_controller_swiftkv_quantize_kv_record_Pipeline_find_kv_group_max_block_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        empty_612,
        k_raw_3534,
        k_raw_3942,
        k_raw_4350,
        empty_613,
        k_raw_5164,
        k_raw_5572,
        k_raw_5980,
        k_raw_3228,
        k_raw_3636,
        k_raw_4044,
        k_raw_4452,
        k_raw_4858,
        k_raw_5266,
        k_raw_5674,
        k_raw_6082,
        k_raw_3330,
        k_raw_3738,
        k_raw_4146,
        k_raw_4554,
        k_raw_4960,
        k_raw_5368,
        k_raw_5776,
        k_raw_6184,
        k_raw_3432,
        k_raw_3840,
        k_raw_4248,
        k_raw_4656,
        k_raw_5062,
        k_raw_5470,
        k_raw_5878,
        k_raw_6286,
        empty_614,
        v_raw_3535,
        v_raw_3943,
        v_raw_4351,
        empty,
        v_raw_5165,
        v_raw_5573,
        v_raw_5981,
        v_raw_3229,
        v_raw_3637,
        v_raw_4045,
        v_raw_4453,
        v_raw_4859,
        v_raw_5267,
        v_raw_5675,
        v_raw_6083,
        v_raw_3331,
        v_raw_3739,
        v_raw_4147,
        v_raw_4555,
        v_raw_4961,
        v_raw_5369,
        v_raw_5777,
        v_raw_6185,
        v_raw_3433,
        v_raw_3841,
        v_raw_4249,
        v_raw_4657,
        v_raw_5063,
        v_raw_5471,
        v_raw_5879,
        v_raw_6287,
        maximum_v_out,
        maximum_v_out_ap_vld,
        maximum_k_out,
        maximum_k_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] empty_612;
input  [31:0] k_raw_3534;
input  [31:0] k_raw_3942;
input  [31:0] k_raw_4350;
input  [31:0] empty_613;
input  [31:0] k_raw_5164;
input  [31:0] k_raw_5572;
input  [31:0] k_raw_5980;
input  [31:0] k_raw_3228;
input  [31:0] k_raw_3636;
input  [31:0] k_raw_4044;
input  [31:0] k_raw_4452;
input  [31:0] k_raw_4858;
input  [31:0] k_raw_5266;
input  [31:0] k_raw_5674;
input  [31:0] k_raw_6082;
input  [31:0] k_raw_3330;
input  [31:0] k_raw_3738;
input  [31:0] k_raw_4146;
input  [31:0] k_raw_4554;
input  [31:0] k_raw_4960;
input  [31:0] k_raw_5368;
input  [31:0] k_raw_5776;
input  [31:0] k_raw_6184;
input  [31:0] k_raw_3432;
input  [31:0] k_raw_3840;
input  [31:0] k_raw_4248;
input  [31:0] k_raw_4656;
input  [31:0] k_raw_5062;
input  [31:0] k_raw_5470;
input  [31:0] k_raw_5878;
input  [31:0] k_raw_6286;
input  [31:0] empty_614;
input  [31:0] v_raw_3535;
input  [31:0] v_raw_3943;
input  [31:0] v_raw_4351;
input  [31:0] empty;
input  [31:0] v_raw_5165;
input  [31:0] v_raw_5573;
input  [31:0] v_raw_5981;
input  [31:0] v_raw_3229;
input  [31:0] v_raw_3637;
input  [31:0] v_raw_4045;
input  [31:0] v_raw_4453;
input  [31:0] v_raw_4859;
input  [31:0] v_raw_5267;
input  [31:0] v_raw_5675;
input  [31:0] v_raw_6083;
input  [31:0] v_raw_3331;
input  [31:0] v_raw_3739;
input  [31:0] v_raw_4147;
input  [31:0] v_raw_4555;
input  [31:0] v_raw_4961;
input  [31:0] v_raw_5369;
input  [31:0] v_raw_5777;
input  [31:0] v_raw_6185;
input  [31:0] v_raw_3433;
input  [31:0] v_raw_3841;
input  [31:0] v_raw_4249;
input  [31:0] v_raw_4657;
input  [31:0] v_raw_5063;
input  [31:0] v_raw_5471;
input  [31:0] v_raw_5879;
input  [31:0] v_raw_6287;
output  [31:0] maximum_v_out;
output   maximum_v_out_ap_vld;
output  [31:0] maximum_k_out;
output   maximum_k_out_ap_vld;

reg ap_idle;
reg maximum_v_out_ap_vld;
reg maximum_k_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln444_fu_612_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln444_reg_1292;
wire   [31:0] magnitude_k_fu_682_p3;
reg   [31:0] magnitude_k_reg_1296;
wire   [31:0] magnitude_k_1_fu_744_p3;
reg   [31:0] magnitude_k_1_reg_1302;
wire   [31:0] magnitude_k_2_fu_806_p3;
reg   [31:0] magnitude_k_2_reg_1308;
wire   [31:0] magnitude_k_3_fu_868_p3;
reg   [31:0] magnitude_k_3_reg_1314;
wire   [31:0] magnitude_v_fu_930_p3;
reg   [31:0] magnitude_v_reg_1320;
wire   [31:0] magnitude_v_1_fu_992_p3;
reg   [31:0] magnitude_v_1_reg_1326;
wire   [31:0] magnitude_v_2_fu_1054_p3;
reg   [31:0] magnitude_v_2_reg_1332;
wire   [31:0] magnitude_v_3_fu_1116_p3;
reg   [31:0] magnitude_v_3_reg_1338;
wire   [31:0] block_max_k_fu_1167_p3;
reg   [31:0] block_max_k_reg_1344;
wire   [31:0] block_max_v_fu_1213_p3;
reg   [31:0] block_max_v_reg_1350;
reg   [31:0] maximum_k_fu_184;
wire   [31:0] maximum_k_1_fu_1232_p3;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [31:0] maximum_v_fu_188;
wire   [31:0] maximum_v_2_fu_1244_p3;
reg   [3:0] block_fu_192;
wire   [3:0] add_ln445_fu_618_p2;
reg   [3:0] ap_sig_allocacmp_block_2;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] raw_fu_628_p17;
wire   [2:0] trunc_ln447_fu_624_p1;
wire   [31:0] raw_fu_628_p19;
wire   [0:0] tmp_142_fu_668_p3;
wire   [31:0] sub_ln316_fu_676_p2;
wire   [31:0] raw_2_fu_690_p17;
wire   [31:0] raw_2_fu_690_p19;
wire   [0:0] tmp_143_fu_730_p3;
wire   [31:0] sub_ln316_1_fu_738_p2;
wire   [31:0] raw_4_fu_752_p17;
wire   [31:0] raw_4_fu_752_p19;
wire   [0:0] tmp_144_fu_792_p3;
wire   [31:0] sub_ln316_2_fu_800_p2;
wire   [31:0] raw_6_fu_814_p17;
wire   [31:0] raw_6_fu_814_p19;
wire   [0:0] tmp_145_fu_854_p3;
wire   [31:0] sub_ln316_3_fu_862_p2;
wire   [31:0] raw_1_fu_876_p17;
wire   [31:0] raw_1_fu_876_p19;
wire   [0:0] tmp_146_fu_916_p3;
wire   [31:0] sub_ln316_4_fu_924_p2;
wire   [31:0] raw_3_fu_938_p17;
wire   [31:0] raw_3_fu_938_p19;
wire   [0:0] tmp_147_fu_978_p3;
wire   [31:0] sub_ln316_5_fu_986_p2;
wire   [31:0] raw_5_fu_1000_p17;
wire   [31:0] raw_5_fu_1000_p19;
wire   [0:0] tmp_148_fu_1040_p3;
wire   [31:0] sub_ln316_6_fu_1048_p2;
wire   [31:0] raw_7_fu_1062_p17;
wire   [31:0] raw_7_fu_1062_p19;
wire   [0:0] tmp_149_fu_1102_p3;
wire   [31:0] sub_ln316_7_fu_1110_p2;
wire   [0:0] icmp_ln461_fu_1129_p2;
wire   [0:0] xor_ln461_fu_1133_p2;
wire   [0:0] icmp_ln464_fu_1145_p2;
wire   [0:0] xor_ln464_fu_1149_p2;
wire   [31:0] max_k_01_fu_1139_p3;
wire   [31:0] max_k_23_fu_1155_p3;
wire   [0:0] icmp_ln467_fu_1161_p2;
wire   [0:0] icmp_ln469_fu_1175_p2;
wire   [0:0] xor_ln469_fu_1179_p2;
wire   [0:0] icmp_ln472_fu_1191_p2;
wire   [0:0] xor_ln472_fu_1195_p2;
wire   [31:0] max_v_01_fu_1185_p3;
wire   [31:0] max_v_23_fu_1201_p3;
wire   [0:0] icmp_ln475_fu_1207_p2;
wire   [0:0] icmp_ln476_fu_1227_p2;
wire   [0:0] icmp_ln479_fu_1239_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [2:0] raw_fu_628_p1;
wire   [2:0] raw_fu_628_p3;
wire   [2:0] raw_fu_628_p5;
wire   [2:0] raw_fu_628_p7;
wire  signed [2:0] raw_fu_628_p9;
wire  signed [2:0] raw_fu_628_p11;
wire  signed [2:0] raw_fu_628_p13;
wire  signed [2:0] raw_fu_628_p15;
wire   [2:0] raw_2_fu_690_p1;
wire   [2:0] raw_2_fu_690_p3;
wire   [2:0] raw_2_fu_690_p5;
wire   [2:0] raw_2_fu_690_p7;
wire  signed [2:0] raw_2_fu_690_p9;
wire  signed [2:0] raw_2_fu_690_p11;
wire  signed [2:0] raw_2_fu_690_p13;
wire  signed [2:0] raw_2_fu_690_p15;
wire   [2:0] raw_4_fu_752_p1;
wire   [2:0] raw_4_fu_752_p3;
wire   [2:0] raw_4_fu_752_p5;
wire   [2:0] raw_4_fu_752_p7;
wire  signed [2:0] raw_4_fu_752_p9;
wire  signed [2:0] raw_4_fu_752_p11;
wire  signed [2:0] raw_4_fu_752_p13;
wire  signed [2:0] raw_4_fu_752_p15;
wire   [2:0] raw_6_fu_814_p1;
wire   [2:0] raw_6_fu_814_p3;
wire   [2:0] raw_6_fu_814_p5;
wire   [2:0] raw_6_fu_814_p7;
wire  signed [2:0] raw_6_fu_814_p9;
wire  signed [2:0] raw_6_fu_814_p11;
wire  signed [2:0] raw_6_fu_814_p13;
wire  signed [2:0] raw_6_fu_814_p15;
wire   [2:0] raw_1_fu_876_p1;
wire   [2:0] raw_1_fu_876_p3;
wire   [2:0] raw_1_fu_876_p5;
wire   [2:0] raw_1_fu_876_p7;
wire  signed [2:0] raw_1_fu_876_p9;
wire  signed [2:0] raw_1_fu_876_p11;
wire  signed [2:0] raw_1_fu_876_p13;
wire  signed [2:0] raw_1_fu_876_p15;
wire   [2:0] raw_3_fu_938_p1;
wire   [2:0] raw_3_fu_938_p3;
wire   [2:0] raw_3_fu_938_p5;
wire   [2:0] raw_3_fu_938_p7;
wire  signed [2:0] raw_3_fu_938_p9;
wire  signed [2:0] raw_3_fu_938_p11;
wire  signed [2:0] raw_3_fu_938_p13;
wire  signed [2:0] raw_3_fu_938_p15;
wire   [2:0] raw_5_fu_1000_p1;
wire   [2:0] raw_5_fu_1000_p3;
wire   [2:0] raw_5_fu_1000_p5;
wire   [2:0] raw_5_fu_1000_p7;
wire  signed [2:0] raw_5_fu_1000_p9;
wire  signed [2:0] raw_5_fu_1000_p11;
wire  signed [2:0] raw_5_fu_1000_p13;
wire  signed [2:0] raw_5_fu_1000_p15;
wire   [2:0] raw_7_fu_1062_p1;
wire   [2:0] raw_7_fu_1062_p3;
wire   [2:0] raw_7_fu_1062_p5;
wire   [2:0] raw_7_fu_1062_p7;
wire  signed [2:0] raw_7_fu_1062_p9;
wire  signed [2:0] raw_7_fu_1062_p11;
wire  signed [2:0] raw_7_fu_1062_p13;
wire  signed [2:0] raw_7_fu_1062_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 maximum_k_fu_184 = 32'd0;
#0 maximum_v_fu_188 = 32'd0;
#0 block_fu_192 = 4'd0;
#0 ap_done_reg = 1'b0;
end

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U122(
    .din0(empty_612),
    .din1(k_raw_3534),
    .din2(k_raw_3942),
    .din3(k_raw_4350),
    .din4(empty_613),
    .din5(k_raw_5164),
    .din6(k_raw_5572),
    .din7(k_raw_5980),
    .def(raw_fu_628_p17),
    .sel(trunc_ln447_fu_624_p1),
    .dout(raw_fu_628_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U123(
    .din0(k_raw_3228),
    .din1(k_raw_3636),
    .din2(k_raw_4044),
    .din3(k_raw_4452),
    .din4(k_raw_4858),
    .din5(k_raw_5266),
    .din6(k_raw_5674),
    .din7(k_raw_6082),
    .def(raw_2_fu_690_p17),
    .sel(trunc_ln447_fu_624_p1),
    .dout(raw_2_fu_690_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U124(
    .din0(k_raw_3330),
    .din1(k_raw_3738),
    .din2(k_raw_4146),
    .din3(k_raw_4554),
    .din4(k_raw_4960),
    .din5(k_raw_5368),
    .din6(k_raw_5776),
    .din7(k_raw_6184),
    .def(raw_4_fu_752_p17),
    .sel(trunc_ln447_fu_624_p1),
    .dout(raw_4_fu_752_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U125(
    .din0(k_raw_3432),
    .din1(k_raw_3840),
    .din2(k_raw_4248),
    .din3(k_raw_4656),
    .din4(k_raw_5062),
    .din5(k_raw_5470),
    .din6(k_raw_5878),
    .din7(k_raw_6286),
    .def(raw_6_fu_814_p17),
    .sel(trunc_ln447_fu_624_p1),
    .dout(raw_6_fu_814_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U126(
    .din0(empty_614),
    .din1(v_raw_3535),
    .din2(v_raw_3943),
    .din3(v_raw_4351),
    .din4(empty),
    .din5(v_raw_5165),
    .din6(v_raw_5573),
    .din7(v_raw_5981),
    .def(raw_1_fu_876_p17),
    .sel(trunc_ln447_fu_624_p1),
    .dout(raw_1_fu_876_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U127(
    .din0(v_raw_3229),
    .din1(v_raw_3637),
    .din2(v_raw_4045),
    .din3(v_raw_4453),
    .din4(v_raw_4859),
    .din5(v_raw_5267),
    .din6(v_raw_5675),
    .din7(v_raw_6083),
    .def(raw_3_fu_938_p17),
    .sel(trunc_ln447_fu_624_p1),
    .dout(raw_3_fu_938_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U128(
    .din0(v_raw_3331),
    .din1(v_raw_3739),
    .din2(v_raw_4147),
    .din3(v_raw_4555),
    .din4(v_raw_4961),
    .din5(v_raw_5369),
    .din6(v_raw_5777),
    .din7(v_raw_6185),
    .def(raw_5_fu_1000_p17),
    .sel(trunc_ln447_fu_624_p1),
    .dout(raw_5_fu_1000_p19)
);

int4_decoder_token_controller_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U129(
    .din0(v_raw_3433),
    .din1(v_raw_3841),
    .din2(v_raw_4249),
    .din3(v_raw_4657),
    .din4(v_raw_5063),
    .din5(v_raw_5471),
    .din6(v_raw_5879),
    .din7(v_raw_6287),
    .def(raw_7_fu_1062_p17),
    .sel(trunc_ln447_fu_624_p1),
    .dout(raw_7_fu_1062_p19)
);

int4_decoder_token_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln444_fu_612_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            block_fu_192 <= add_ln445_fu_618_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            block_fu_192 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            maximum_k_fu_184 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            maximum_k_fu_184 <= maximum_k_1_fu_1232_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            maximum_v_fu_188 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            maximum_v_fu_188 <= maximum_v_2_fu_1244_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        block_max_k_reg_1344 <= block_max_k_fu_1167_p3;
        block_max_v_reg_1350 <= block_max_v_fu_1213_p3;
        icmp_ln444_reg_1292 <= icmp_ln444_fu_612_p2;
        magnitude_k_1_reg_1302 <= magnitude_k_1_fu_744_p3;
        magnitude_k_2_reg_1308 <= magnitude_k_2_fu_806_p3;
        magnitude_k_3_reg_1314 <= magnitude_k_3_fu_868_p3;
        magnitude_k_reg_1296 <= magnitude_k_fu_682_p3;
        magnitude_v_1_reg_1326 <= magnitude_v_1_fu_992_p3;
        magnitude_v_2_reg_1332 <= magnitude_v_2_fu_1054_p3;
        magnitude_v_3_reg_1338 <= magnitude_v_3_fu_1116_p3;
        magnitude_v_reg_1320 <= magnitude_v_fu_930_p3;
    end
end

always @ (*) begin
    if (((icmp_ln444_fu_612_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_block_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_block_2 = block_fu_192;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln444_reg_1292 == 1'd1))) begin
        maximum_k_out_ap_vld = 1'b1;
    end else begin
        maximum_k_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln444_reg_1292 == 1'd1))) begin
        maximum_v_out_ap_vld = 1'b1;
    end else begin
        maximum_v_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln445_fu_618_p2 = (ap_sig_allocacmp_block_2 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign block_max_k_fu_1167_p3 = ((icmp_ln467_fu_1161_p2[0:0] == 1'b1) ? max_k_01_fu_1139_p3 : max_k_23_fu_1155_p3);

assign block_max_v_fu_1213_p3 = ((icmp_ln475_fu_1207_p2[0:0] == 1'b1) ? max_v_01_fu_1185_p3 : max_v_23_fu_1201_p3);

assign icmp_ln444_fu_612_p2 = ((ap_sig_allocacmp_block_2 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln461_fu_1129_p2 = ((magnitude_k_1_reg_1302 < magnitude_k_reg_1296) ? 1'b1 : 1'b0);

assign icmp_ln464_fu_1145_p2 = ((magnitude_k_3_reg_1314 < magnitude_k_2_reg_1308) ? 1'b1 : 1'b0);

assign icmp_ln467_fu_1161_p2 = ((max_k_01_fu_1139_p3 > max_k_23_fu_1155_p3) ? 1'b1 : 1'b0);

assign icmp_ln469_fu_1175_p2 = ((magnitude_v_1_reg_1326 < magnitude_v_reg_1320) ? 1'b1 : 1'b0);

assign icmp_ln472_fu_1191_p2 = ((magnitude_v_3_reg_1338 < magnitude_v_2_reg_1332) ? 1'b1 : 1'b0);

assign icmp_ln475_fu_1207_p2 = ((max_v_01_fu_1185_p3 > max_v_23_fu_1201_p3) ? 1'b1 : 1'b0);

assign icmp_ln476_fu_1227_p2 = ((block_max_k_reg_1344 > maximum_k_fu_184) ? 1'b1 : 1'b0);

assign icmp_ln479_fu_1239_p2 = ((block_max_v_reg_1350 > maximum_v_fu_188) ? 1'b1 : 1'b0);

assign magnitude_k_1_fu_744_p3 = ((tmp_143_fu_730_p3[0:0] == 1'b1) ? sub_ln316_1_fu_738_p2 : raw_2_fu_690_p19);

assign magnitude_k_2_fu_806_p3 = ((tmp_144_fu_792_p3[0:0] == 1'b1) ? sub_ln316_2_fu_800_p2 : raw_4_fu_752_p19);

assign magnitude_k_3_fu_868_p3 = ((tmp_145_fu_854_p3[0:0] == 1'b1) ? sub_ln316_3_fu_862_p2 : raw_6_fu_814_p19);

assign magnitude_k_fu_682_p3 = ((tmp_142_fu_668_p3[0:0] == 1'b1) ? sub_ln316_fu_676_p2 : raw_fu_628_p19);

assign magnitude_v_1_fu_992_p3 = ((tmp_147_fu_978_p3[0:0] == 1'b1) ? sub_ln316_5_fu_986_p2 : raw_3_fu_938_p19);

assign magnitude_v_2_fu_1054_p3 = ((tmp_148_fu_1040_p3[0:0] == 1'b1) ? sub_ln316_6_fu_1048_p2 : raw_5_fu_1000_p19);

assign magnitude_v_3_fu_1116_p3 = ((tmp_149_fu_1102_p3[0:0] == 1'b1) ? sub_ln316_7_fu_1110_p2 : raw_7_fu_1062_p19);

assign magnitude_v_fu_930_p3 = ((tmp_146_fu_916_p3[0:0] == 1'b1) ? sub_ln316_4_fu_924_p2 : raw_1_fu_876_p19);

assign max_k_01_fu_1139_p3 = ((xor_ln461_fu_1133_p2[0:0] == 1'b1) ? magnitude_k_1_reg_1302 : magnitude_k_reg_1296);

assign max_k_23_fu_1155_p3 = ((xor_ln464_fu_1149_p2[0:0] == 1'b1) ? magnitude_k_3_reg_1314 : magnitude_k_2_reg_1308);

assign max_v_01_fu_1185_p3 = ((xor_ln469_fu_1179_p2[0:0] == 1'b1) ? magnitude_v_1_reg_1326 : magnitude_v_reg_1320);

assign max_v_23_fu_1201_p3 = ((xor_ln472_fu_1195_p2[0:0] == 1'b1) ? magnitude_v_3_reg_1338 : magnitude_v_2_reg_1332);

assign maximum_k_1_fu_1232_p3 = ((icmp_ln476_fu_1227_p2[0:0] == 1'b1) ? block_max_k_reg_1344 : maximum_k_fu_184);

assign maximum_k_out = maximum_k_fu_184;

assign maximum_v_2_fu_1244_p3 = ((icmp_ln479_fu_1239_p2[0:0] == 1'b1) ? block_max_v_reg_1350 : maximum_v_fu_188);

assign maximum_v_out = maximum_v_fu_188;

assign raw_1_fu_876_p17 = 'bx;

assign raw_2_fu_690_p17 = 'bx;

assign raw_3_fu_938_p17 = 'bx;

assign raw_4_fu_752_p17 = 'bx;

assign raw_5_fu_1000_p17 = 'bx;

assign raw_6_fu_814_p17 = 'bx;

assign raw_7_fu_1062_p17 = 'bx;

assign raw_fu_628_p17 = 'bx;

assign sub_ln316_1_fu_738_p2 = (32'd0 - raw_2_fu_690_p19);

assign sub_ln316_2_fu_800_p2 = (32'd0 - raw_4_fu_752_p19);

assign sub_ln316_3_fu_862_p2 = (32'd0 - raw_6_fu_814_p19);

assign sub_ln316_4_fu_924_p2 = (32'd0 - raw_1_fu_876_p19);

assign sub_ln316_5_fu_986_p2 = (32'd0 - raw_3_fu_938_p19);

assign sub_ln316_6_fu_1048_p2 = (32'd0 - raw_5_fu_1000_p19);

assign sub_ln316_7_fu_1110_p2 = (32'd0 - raw_7_fu_1062_p19);

assign sub_ln316_fu_676_p2 = (32'd0 - raw_fu_628_p19);

assign tmp_142_fu_668_p3 = raw_fu_628_p19[32'd31];

assign tmp_143_fu_730_p3 = raw_2_fu_690_p19[32'd31];

assign tmp_144_fu_792_p3 = raw_4_fu_752_p19[32'd31];

assign tmp_145_fu_854_p3 = raw_6_fu_814_p19[32'd31];

assign tmp_146_fu_916_p3 = raw_1_fu_876_p19[32'd31];

assign tmp_147_fu_978_p3 = raw_3_fu_938_p19[32'd31];

assign tmp_148_fu_1040_p3 = raw_5_fu_1000_p19[32'd31];

assign tmp_149_fu_1102_p3 = raw_7_fu_1062_p19[32'd31];

assign trunc_ln447_fu_624_p1 = ap_sig_allocacmp_block_2[2:0];

assign xor_ln461_fu_1133_p2 = (icmp_ln461_fu_1129_p2 ^ 1'd1);

assign xor_ln464_fu_1149_p2 = (icmp_ln464_fu_1145_p2 ^ 1'd1);

assign xor_ln469_fu_1179_p2 = (icmp_ln469_fu_1175_p2 ^ 1'd1);

assign xor_ln472_fu_1195_p2 = (icmp_ln472_fu_1191_p2 ^ 1'd1);

endmodule //int4_decoder_token_controller_swiftkv_quantize_kv_record_Pipeline_find_kv_group_max_block_loop
