// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module int4_decoder_token_controller_swiftkv_run_four_pes (
        q_pe0_address0,
        q_pe0_ce0,
        q_pe0_d0,
        q_pe0_q0,
        q_pe0_we0,
        q_pe1_address0,
        q_pe1_ce0,
        q_pe1_d0,
        q_pe1_q0,
        q_pe1_we0,
        q_pe2_address0,
        q_pe2_ce0,
        q_pe2_d0,
        q_pe2_q0,
        q_pe2_we0,
        q_pe3_address0,
        q_pe3_ce0,
        q_pe3_d0,
        q_pe3_q0,
        q_pe3_we0,
        k_pe0_address0,
        k_pe0_ce0,
        k_pe0_d0,
        k_pe0_q0,
        k_pe0_we0,
        k_pe1_address0,
        k_pe1_ce0,
        k_pe1_d0,
        k_pe1_q0,
        k_pe1_we0,
        k_pe2_address0,
        k_pe2_ce0,
        k_pe2_d0,
        k_pe2_q0,
        k_pe2_we0,
        k_pe3_address0,
        k_pe3_ce0,
        k_pe3_d0,
        k_pe3_q0,
        k_pe3_we0,
        v_pe0_address0,
        v_pe0_ce0,
        v_pe0_d0,
        v_pe0_q0,
        v_pe0_we0,
        v_pe1_address0,
        v_pe1_ce0,
        v_pe1_d0,
        v_pe1_q0,
        v_pe1_we0,
        v_pe2_address0,
        v_pe2_ce0,
        v_pe2_d0,
        v_pe2_q0,
        v_pe2_we0,
        v_pe3_address0,
        v_pe3_ce0,
        v_pe3_d0,
        v_pe3_q0,
        v_pe3_we0,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        kv_cache_pe0,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        kv_cache_pe1,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RFIFONUM,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        kv_cache_pe2,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RFIFONUM,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        kv_cache_pe3,
        current_cos_address0,
        current_cos_ce0,
        current_cos_d0,
        current_cos_q0,
        current_cos_we0,
        current_sin_address0,
        current_sin_ce0,
        current_sin_d0,
        current_sin_q0,
        current_sin_we0,
        activation_q_address0,
        activation_q_ce0,
        activation_q_d0,
        activation_q_q0,
        activation_q_we0,
        activation_scale_address0,
        activation_scale_ce0,
        activation_scale_d0,
        activation_scale_q0,
        activation_scale_we0,
        controller_layer_index_val,
        controller_position_val,
        ap_clk,
        ap_rst,
        controller_layer_index_val_ap_vld,
        controller_position_val_ap_vld,
        ap_start,
        kv_cache_pe0_ap_vld,
        ap_done,
        kv_cache_pe1_ap_vld,
        kv_cache_pe2_ap_vld,
        kv_cache_pe3_ap_vld,
        ap_ready,
        ap_idle,
        ap_continue
);


output  [5:0] q_pe0_address0;
output   q_pe0_ce0;
output  [511:0] q_pe0_d0;
input  [511:0] q_pe0_q0;
output   q_pe0_we0;
output  [5:0] q_pe1_address0;
output   q_pe1_ce0;
output  [511:0] q_pe1_d0;
input  [511:0] q_pe1_q0;
output   q_pe1_we0;
output  [5:0] q_pe2_address0;
output   q_pe2_ce0;
output  [511:0] q_pe2_d0;
input  [511:0] q_pe2_q0;
output   q_pe2_we0;
output  [5:0] q_pe3_address0;
output   q_pe3_ce0;
output  [511:0] q_pe3_d0;
input  [511:0] q_pe3_q0;
output   q_pe3_we0;
output  [5:0] k_pe0_address0;
output   k_pe0_ce0;
output  [511:0] k_pe0_d0;
input  [511:0] k_pe0_q0;
output   k_pe0_we0;
output  [5:0] k_pe1_address0;
output   k_pe1_ce0;
output  [511:0] k_pe1_d0;
input  [511:0] k_pe1_q0;
output   k_pe1_we0;
output  [5:0] k_pe2_address0;
output   k_pe2_ce0;
output  [511:0] k_pe2_d0;
input  [511:0] k_pe2_q0;
output   k_pe2_we0;
output  [5:0] k_pe3_address0;
output   k_pe3_ce0;
output  [511:0] k_pe3_d0;
input  [511:0] k_pe3_q0;
output   k_pe3_we0;
output  [5:0] v_pe0_address0;
output   v_pe0_ce0;
output  [511:0] v_pe0_d0;
input  [511:0] v_pe0_q0;
output   v_pe0_we0;
output  [5:0] v_pe1_address0;
output   v_pe1_ce0;
output  [511:0] v_pe1_d0;
input  [511:0] v_pe1_q0;
output   v_pe1_we0;
output  [5:0] v_pe2_address0;
output   v_pe2_ce0;
output  [511:0] v_pe2_d0;
input  [511:0] v_pe2_q0;
output   v_pe2_we0;
output  [5:0] v_pe3_address0;
output   v_pe3_ce0;
output  [511:0] v_pe3_d0;
input  [511:0] v_pe3_q0;
output   v_pe3_we0;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [511:0] m_axi_gmem0_WDATA;
output  [63:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [511:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [11:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] kv_cache_pe0;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [511:0] m_axi_gmem1_WDATA;
output  [63:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [511:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [11:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] kv_cache_pe1;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [63:0] m_axi_gmem2_AWADDR;
output  [0:0] m_axi_gmem2_AWID;
output  [31:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [0:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [511:0] m_axi_gmem2_WDATA;
output  [63:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [0:0] m_axi_gmem2_WID;
output  [0:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [63:0] m_axi_gmem2_ARADDR;
output  [0:0] m_axi_gmem2_ARID;
output  [31:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [0:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [511:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [0:0] m_axi_gmem2_RID;
input  [11:0] m_axi_gmem2_RFIFONUM;
input  [0:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [0:0] m_axi_gmem2_BID;
input  [0:0] m_axi_gmem2_BUSER;
input  [63:0] kv_cache_pe2;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [63:0] m_axi_gmem3_AWADDR;
output  [0:0] m_axi_gmem3_AWID;
output  [31:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [0:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [511:0] m_axi_gmem3_WDATA;
output  [63:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [0:0] m_axi_gmem3_WID;
output  [0:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [63:0] m_axi_gmem3_ARADDR;
output  [0:0] m_axi_gmem3_ARID;
output  [31:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [0:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [511:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [0:0] m_axi_gmem3_RID;
input  [11:0] m_axi_gmem3_RFIFONUM;
input  [0:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [0:0] m_axi_gmem3_BID;
input  [0:0] m_axi_gmem3_BUSER;
input  [63:0] kv_cache_pe3;
output  [5:0] current_cos_address0;
output   current_cos_ce0;
output  [18:0] current_cos_d0;
input  [18:0] current_cos_q0;
output   current_cos_we0;
output  [5:0] current_sin_address0;
output   current_sin_ce0;
output  [18:0] current_sin_d0;
input  [18:0] current_sin_q0;
output   current_sin_we0;
output  [8:0] activation_q_address0;
output   activation_q_ce0;
output  [479:0] activation_q_d0;
input  [479:0] activation_q_q0;
output   activation_q_we0;
output  [4:0] activation_scale_address0;
output   activation_scale_ce0;
output  [511:0] activation_scale_d0;
input  [511:0] activation_scale_q0;
output   activation_scale_we0;
input  [5:0] controller_layer_index_val;
input  [11:0] controller_position_val;
input   ap_clk;
input   ap_rst;
input   controller_layer_index_val_ap_vld;
input   controller_position_val_ap_vld;
input   ap_start;
input   kv_cache_pe0_ap_vld;
output   ap_done;
input   kv_cache_pe1_ap_vld;
input   kv_cache_pe2_ap_vld;
input   kv_cache_pe3_ap_vld;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    swiftkv_broadcast_pe_commands_U0_ap_start;
wire    swiftkv_broadcast_pe_commands_U0_ap_done;
wire    swiftkv_broadcast_pe_commands_U0_ap_continue;
wire    swiftkv_broadcast_pe_commands_U0_ap_idle;
wire    swiftkv_broadcast_pe_commands_U0_ap_ready;
wire   [17:0] swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe0_din;
wire    swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe0_write;
wire   [17:0] swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe1_din;
wire    swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe1_write;
wire   [17:0] swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe2_din;
wire    swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe2_write;
wire   [17:0] swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe3_din;
wire    swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe3_write;
wire    swiftkv_broadcast_rope_U0_ap_start;
wire    swiftkv_broadcast_rope_U0_ap_done;
wire    swiftkv_broadcast_rope_U0_ap_continue;
wire    swiftkv_broadcast_rope_U0_ap_idle;
wire    swiftkv_broadcast_rope_U0_ap_ready;
wire   [18:0] swiftkv_broadcast_rope_U0_cos_pe0_din;
wire    swiftkv_broadcast_rope_U0_cos_pe0_write;
wire   [18:0] swiftkv_broadcast_rope_U0_cos_pe1_din;
wire    swiftkv_broadcast_rope_U0_cos_pe1_write;
wire   [18:0] swiftkv_broadcast_rope_U0_cos_pe2_din;
wire    swiftkv_broadcast_rope_U0_cos_pe2_write;
wire   [18:0] swiftkv_broadcast_rope_U0_cos_pe3_din;
wire    swiftkv_broadcast_rope_U0_cos_pe3_write;
wire   [18:0] swiftkv_broadcast_rope_U0_sin_pe0_din;
wire    swiftkv_broadcast_rope_U0_sin_pe0_write;
wire   [18:0] swiftkv_broadcast_rope_U0_sin_pe1_din;
wire    swiftkv_broadcast_rope_U0_sin_pe1_write;
wire   [18:0] swiftkv_broadcast_rope_U0_sin_pe2_din;
wire    swiftkv_broadcast_rope_U0_sin_pe2_write;
wire   [18:0] swiftkv_broadcast_rope_U0_sin_pe3_din;
wire    swiftkv_broadcast_rope_U0_sin_pe3_write;
wire   [5:0] swiftkv_broadcast_rope_U0_current_cos_address0;
wire    swiftkv_broadcast_rope_U0_current_cos_ce0;
wire   [5:0] swiftkv_broadcast_rope_U0_current_sin_address0;
wire    swiftkv_broadcast_rope_U0_current_sin_ce0;
wire    swiftkv_run_pe_0_U0_ap_start;
wire    swiftkv_run_pe_0_U0_ap_done;
wire    swiftkv_run_pe_0_U0_ap_continue;
wire    swiftkv_run_pe_0_U0_ap_idle;
wire    swiftkv_run_pe_0_U0_ap_ready;
wire   [5:0] swiftkv_run_pe_0_U0_q_address0;
wire    swiftkv_run_pe_0_U0_q_ce0;
wire   [5:0] swiftkv_run_pe_0_U0_k_address0;
wire    swiftkv_run_pe_0_U0_k_ce0;
wire   [5:0] swiftkv_run_pe_0_U0_v_address0;
wire    swiftkv_run_pe_0_U0_v_ce0;
wire    swiftkv_run_pe_0_U0_m_axi_gmem0_AWVALID;
wire   [63:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWADDR;
wire   [0:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWID;
wire   [31:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWLEN;
wire   [2:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWBURST;
wire   [1:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWPROT;
wire   [3:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWQOS;
wire   [3:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWREGION;
wire   [0:0] swiftkv_run_pe_0_U0_m_axi_gmem0_AWUSER;
wire    swiftkv_run_pe_0_U0_m_axi_gmem0_WVALID;
wire   [511:0] swiftkv_run_pe_0_U0_m_axi_gmem0_WDATA;
wire   [63:0] swiftkv_run_pe_0_U0_m_axi_gmem0_WSTRB;
wire    swiftkv_run_pe_0_U0_m_axi_gmem0_WLAST;
wire   [0:0] swiftkv_run_pe_0_U0_m_axi_gmem0_WID;
wire   [0:0] swiftkv_run_pe_0_U0_m_axi_gmem0_WUSER;
wire    swiftkv_run_pe_0_U0_m_axi_gmem0_ARVALID;
wire   [63:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARADDR;
wire   [0:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARID;
wire   [31:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARLEN;
wire   [2:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARBURST;
wire   [1:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARPROT;
wire   [3:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARQOS;
wire   [3:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARREGION;
wire   [0:0] swiftkv_run_pe_0_U0_m_axi_gmem0_ARUSER;
wire    swiftkv_run_pe_0_U0_m_axi_gmem0_RREADY;
wire    swiftkv_run_pe_0_U0_m_axi_gmem0_BREADY;
wire    swiftkv_run_pe_0_U0_cos_pe0_read;
wire    swiftkv_run_pe_0_U0_sin_pe0_read;
wire   [479:0] swiftkv_run_pe_0_U0_quantized_pe0_din;
wire    swiftkv_run_pe_0_U0_quantized_pe0_write;
wire   [31:0] swiftkv_run_pe_0_U0_scale_pe0_din;
wire    swiftkv_run_pe_0_U0_scale_pe0_write;
wire    swiftkv_run_pe_0_U0_swiftkv_command_pe0_read;
wire    ap_sync_continue;
wire    swiftkv_run_pe_1_U0_ap_start;
wire    swiftkv_run_pe_1_U0_ap_done;
wire    swiftkv_run_pe_1_U0_ap_continue;
wire    swiftkv_run_pe_1_U0_ap_idle;
wire    swiftkv_run_pe_1_U0_ap_ready;
wire   [5:0] swiftkv_run_pe_1_U0_q_address0;
wire    swiftkv_run_pe_1_U0_q_ce0;
wire   [5:0] swiftkv_run_pe_1_U0_k_address0;
wire    swiftkv_run_pe_1_U0_k_ce0;
wire   [5:0] swiftkv_run_pe_1_U0_v_address0;
wire    swiftkv_run_pe_1_U0_v_ce0;
wire    swiftkv_run_pe_1_U0_m_axi_gmem1_AWVALID;
wire   [63:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWADDR;
wire   [0:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWID;
wire   [31:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWLEN;
wire   [2:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWBURST;
wire   [1:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWPROT;
wire   [3:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWQOS;
wire   [3:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWREGION;
wire   [0:0] swiftkv_run_pe_1_U0_m_axi_gmem1_AWUSER;
wire    swiftkv_run_pe_1_U0_m_axi_gmem1_WVALID;
wire   [511:0] swiftkv_run_pe_1_U0_m_axi_gmem1_WDATA;
wire   [63:0] swiftkv_run_pe_1_U0_m_axi_gmem1_WSTRB;
wire    swiftkv_run_pe_1_U0_m_axi_gmem1_WLAST;
wire   [0:0] swiftkv_run_pe_1_U0_m_axi_gmem1_WID;
wire   [0:0] swiftkv_run_pe_1_U0_m_axi_gmem1_WUSER;
wire    swiftkv_run_pe_1_U0_m_axi_gmem1_ARVALID;
wire   [63:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARADDR;
wire   [0:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARID;
wire   [31:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARLEN;
wire   [2:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARBURST;
wire   [1:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARPROT;
wire   [3:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARQOS;
wire   [3:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARREGION;
wire   [0:0] swiftkv_run_pe_1_U0_m_axi_gmem1_ARUSER;
wire    swiftkv_run_pe_1_U0_m_axi_gmem1_RREADY;
wire    swiftkv_run_pe_1_U0_m_axi_gmem1_BREADY;
wire    swiftkv_run_pe_1_U0_cos_pe1_read;
wire    swiftkv_run_pe_1_U0_sin_pe1_read;
wire   [479:0] swiftkv_run_pe_1_U0_quantized_pe1_din;
wire    swiftkv_run_pe_1_U0_quantized_pe1_write;
wire   [31:0] swiftkv_run_pe_1_U0_scale_pe1_din;
wire    swiftkv_run_pe_1_U0_scale_pe1_write;
wire    swiftkv_run_pe_1_U0_swiftkv_command_pe1_read;
wire    swiftkv_run_pe_2_U0_ap_start;
wire    swiftkv_run_pe_2_U0_ap_done;
wire    swiftkv_run_pe_2_U0_ap_continue;
wire    swiftkv_run_pe_2_U0_ap_idle;
wire    swiftkv_run_pe_2_U0_ap_ready;
wire   [5:0] swiftkv_run_pe_2_U0_q_address0;
wire    swiftkv_run_pe_2_U0_q_ce0;
wire   [5:0] swiftkv_run_pe_2_U0_k_address0;
wire    swiftkv_run_pe_2_U0_k_ce0;
wire   [5:0] swiftkv_run_pe_2_U0_v_address0;
wire    swiftkv_run_pe_2_U0_v_ce0;
wire    swiftkv_run_pe_2_U0_m_axi_gmem2_AWVALID;
wire   [63:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWADDR;
wire   [0:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWID;
wire   [31:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWLEN;
wire   [2:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWBURST;
wire   [1:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWPROT;
wire   [3:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWQOS;
wire   [3:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWREGION;
wire   [0:0] swiftkv_run_pe_2_U0_m_axi_gmem2_AWUSER;
wire    swiftkv_run_pe_2_U0_m_axi_gmem2_WVALID;
wire   [511:0] swiftkv_run_pe_2_U0_m_axi_gmem2_WDATA;
wire   [63:0] swiftkv_run_pe_2_U0_m_axi_gmem2_WSTRB;
wire    swiftkv_run_pe_2_U0_m_axi_gmem2_WLAST;
wire   [0:0] swiftkv_run_pe_2_U0_m_axi_gmem2_WID;
wire   [0:0] swiftkv_run_pe_2_U0_m_axi_gmem2_WUSER;
wire    swiftkv_run_pe_2_U0_m_axi_gmem2_ARVALID;
wire   [63:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARADDR;
wire   [0:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARID;
wire   [31:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARLEN;
wire   [2:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARBURST;
wire   [1:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARPROT;
wire   [3:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARQOS;
wire   [3:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARREGION;
wire   [0:0] swiftkv_run_pe_2_U0_m_axi_gmem2_ARUSER;
wire    swiftkv_run_pe_2_U0_m_axi_gmem2_RREADY;
wire    swiftkv_run_pe_2_U0_m_axi_gmem2_BREADY;
wire    swiftkv_run_pe_2_U0_cos_pe2_read;
wire    swiftkv_run_pe_2_U0_sin_pe2_read;
wire   [479:0] swiftkv_run_pe_2_U0_quantized_pe2_din;
wire    swiftkv_run_pe_2_U0_quantized_pe2_write;
wire   [31:0] swiftkv_run_pe_2_U0_scale_pe2_din;
wire    swiftkv_run_pe_2_U0_scale_pe2_write;
wire    swiftkv_run_pe_2_U0_swiftkv_command_pe2_read;
wire    swiftkv_run_pe_3_U0_ap_start;
wire    swiftkv_run_pe_3_U0_ap_done;
wire    swiftkv_run_pe_3_U0_ap_continue;
wire    swiftkv_run_pe_3_U0_ap_idle;
wire    swiftkv_run_pe_3_U0_ap_ready;
wire   [5:0] swiftkv_run_pe_3_U0_q_address0;
wire    swiftkv_run_pe_3_U0_q_ce0;
wire   [5:0] swiftkv_run_pe_3_U0_k_address0;
wire    swiftkv_run_pe_3_U0_k_ce0;
wire   [5:0] swiftkv_run_pe_3_U0_v_address0;
wire    swiftkv_run_pe_3_U0_v_ce0;
wire    swiftkv_run_pe_3_U0_m_axi_gmem3_AWVALID;
wire   [63:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWADDR;
wire   [0:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWID;
wire   [31:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWLEN;
wire   [2:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWSIZE;
wire   [1:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWBURST;
wire   [1:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWLOCK;
wire   [3:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWCACHE;
wire   [2:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWPROT;
wire   [3:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWQOS;
wire   [3:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWREGION;
wire   [0:0] swiftkv_run_pe_3_U0_m_axi_gmem3_AWUSER;
wire    swiftkv_run_pe_3_U0_m_axi_gmem3_WVALID;
wire   [511:0] swiftkv_run_pe_3_U0_m_axi_gmem3_WDATA;
wire   [63:0] swiftkv_run_pe_3_U0_m_axi_gmem3_WSTRB;
wire    swiftkv_run_pe_3_U0_m_axi_gmem3_WLAST;
wire   [0:0] swiftkv_run_pe_3_U0_m_axi_gmem3_WID;
wire   [0:0] swiftkv_run_pe_3_U0_m_axi_gmem3_WUSER;
wire    swiftkv_run_pe_3_U0_m_axi_gmem3_ARVALID;
wire   [63:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARADDR;
wire   [0:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARID;
wire   [31:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARLEN;
wire   [2:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARSIZE;
wire   [1:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARBURST;
wire   [1:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARLOCK;
wire   [3:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARCACHE;
wire   [2:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARPROT;
wire   [3:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARQOS;
wire   [3:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARREGION;
wire   [0:0] swiftkv_run_pe_3_U0_m_axi_gmem3_ARUSER;
wire    swiftkv_run_pe_3_U0_m_axi_gmem3_RREADY;
wire    swiftkv_run_pe_3_U0_m_axi_gmem3_BREADY;
wire    swiftkv_run_pe_3_U0_cos_pe3_read;
wire    swiftkv_run_pe_3_U0_sin_pe3_read;
wire   [479:0] swiftkv_run_pe_3_U0_quantized_pe3_din;
wire    swiftkv_run_pe_3_U0_quantized_pe3_write;
wire   [31:0] swiftkv_run_pe_3_U0_scale_pe3_din;
wire    swiftkv_run_pe_3_U0_scale_pe3_write;
wire    swiftkv_run_pe_3_U0_swiftkv_command_pe3_read;
wire    swiftkv_gather_attention_streams_U0_ap_start;
wire    swiftkv_gather_attention_streams_U0_ap_done;
wire    swiftkv_gather_attention_streams_U0_ap_continue;
wire    swiftkv_gather_attention_streams_U0_ap_idle;
wire    swiftkv_gather_attention_streams_U0_ap_ready;
wire    swiftkv_gather_attention_streams_U0_quantized_pe2_read;
wire    swiftkv_gather_attention_streams_U0_scale_pe2_read;
wire    swiftkv_gather_attention_streams_U0_quantized_pe1_read;
wire    swiftkv_gather_attention_streams_U0_scale_pe1_read;
wire    swiftkv_gather_attention_streams_U0_quantized_pe0_read;
wire    swiftkv_gather_attention_streams_U0_scale_pe0_read;
wire    swiftkv_gather_attention_streams_U0_quantized_pe3_read;
wire    swiftkv_gather_attention_streams_U0_scale_pe3_read;
wire   [8:0] swiftkv_gather_attention_streams_U0_activation_q_address0;
wire    swiftkv_gather_attention_streams_U0_activation_q_ce0;
wire    swiftkv_gather_attention_streams_U0_activation_q_we0;
wire   [479:0] swiftkv_gather_attention_streams_U0_activation_q_d0;
wire   [4:0] swiftkv_gather_attention_streams_U0_activation_scale_address0;
wire    swiftkv_gather_attention_streams_U0_activation_scale_ce0;
wire    swiftkv_gather_attention_streams_U0_activation_scale_we0;
wire   [511:0] swiftkv_gather_attention_streams_U0_activation_scale_d0;
reg    ap_sync_reg_swiftkv_gather_attention_streams_U0_ap_start;
wire    swiftkv_command_pe0_full_n;
wire   [17:0] swiftkv_command_pe0_dout;
wire   [2:0] swiftkv_command_pe0_num_data_valid;
wire   [2:0] swiftkv_command_pe0_fifo_cap;
wire    swiftkv_command_pe0_empty_n;
wire    swiftkv_command_pe1_full_n;
wire   [17:0] swiftkv_command_pe1_dout;
wire   [2:0] swiftkv_command_pe1_num_data_valid;
wire   [2:0] swiftkv_command_pe1_fifo_cap;
wire    swiftkv_command_pe1_empty_n;
wire    swiftkv_command_pe2_full_n;
wire   [17:0] swiftkv_command_pe2_dout;
wire   [2:0] swiftkv_command_pe2_num_data_valid;
wire   [2:0] swiftkv_command_pe2_fifo_cap;
wire    swiftkv_command_pe2_empty_n;
wire    swiftkv_command_pe3_full_n;
wire   [17:0] swiftkv_command_pe3_dout;
wire   [2:0] swiftkv_command_pe3_num_data_valid;
wire   [2:0] swiftkv_command_pe3_fifo_cap;
wire    swiftkv_command_pe3_empty_n;
wire    cos_pe0_full_n;
wire   [18:0] cos_pe0_dout;
wire   [2:0] cos_pe0_num_data_valid;
wire   [2:0] cos_pe0_fifo_cap;
wire    cos_pe0_empty_n;
wire    cos_pe1_full_n;
wire   [18:0] cos_pe1_dout;
wire   [2:0] cos_pe1_num_data_valid;
wire   [2:0] cos_pe1_fifo_cap;
wire    cos_pe1_empty_n;
wire    cos_pe2_full_n;
wire   [18:0] cos_pe2_dout;
wire   [2:0] cos_pe2_num_data_valid;
wire   [2:0] cos_pe2_fifo_cap;
wire    cos_pe2_empty_n;
wire    cos_pe3_full_n;
wire   [18:0] cos_pe3_dout;
wire   [2:0] cos_pe3_num_data_valid;
wire   [2:0] cos_pe3_fifo_cap;
wire    cos_pe3_empty_n;
wire    sin_pe0_full_n;
wire   [18:0] sin_pe0_dout;
wire   [2:0] sin_pe0_num_data_valid;
wire   [2:0] sin_pe0_fifo_cap;
wire    sin_pe0_empty_n;
wire    sin_pe1_full_n;
wire   [18:0] sin_pe1_dout;
wire   [2:0] sin_pe1_num_data_valid;
wire   [2:0] sin_pe1_fifo_cap;
wire    sin_pe1_empty_n;
wire    sin_pe2_full_n;
wire   [18:0] sin_pe2_dout;
wire   [2:0] sin_pe2_num_data_valid;
wire   [2:0] sin_pe2_fifo_cap;
wire    sin_pe2_empty_n;
wire    sin_pe3_full_n;
wire   [18:0] sin_pe3_dout;
wire   [2:0] sin_pe3_num_data_valid;
wire   [2:0] sin_pe3_fifo_cap;
wire    sin_pe3_empty_n;
wire    quantized_pe0_full_n;
wire   [479:0] quantized_pe0_dout;
wire   [2:0] quantized_pe0_num_data_valid;
wire   [2:0] quantized_pe0_fifo_cap;
wire    quantized_pe0_empty_n;
wire    scale_pe0_full_n;
wire   [31:0] scale_pe0_dout;
wire   [2:0] scale_pe0_num_data_valid;
wire   [2:0] scale_pe0_fifo_cap;
wire    scale_pe0_empty_n;
wire    quantized_pe1_full_n;
wire   [479:0] quantized_pe1_dout;
wire   [2:0] quantized_pe1_num_data_valid;
wire   [2:0] quantized_pe1_fifo_cap;
wire    quantized_pe1_empty_n;
wire    scale_pe1_full_n;
wire   [31:0] scale_pe1_dout;
wire   [2:0] scale_pe1_num_data_valid;
wire   [2:0] scale_pe1_fifo_cap;
wire    scale_pe1_empty_n;
wire    quantized_pe2_full_n;
wire   [479:0] quantized_pe2_dout;
wire   [2:0] quantized_pe2_num_data_valid;
wire   [2:0] quantized_pe2_fifo_cap;
wire    quantized_pe2_empty_n;
wire    scale_pe2_full_n;
wire   [31:0] scale_pe2_dout;
wire   [2:0] scale_pe2_num_data_valid;
wire   [2:0] scale_pe2_fifo_cap;
wire    scale_pe2_empty_n;
wire    quantized_pe3_full_n;
wire   [479:0] quantized_pe3_dout;
wire   [2:0] quantized_pe3_num_data_valid;
wire   [2:0] quantized_pe3_fifo_cap;
wire    quantized_pe3_empty_n;
wire    scale_pe3_full_n;
wire   [31:0] scale_pe3_dout;
wire   [2:0] scale_pe3_num_data_valid;
wire   [2:0] scale_pe3_fifo_cap;
wire    scale_pe3_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_swiftkv_broadcast_pe_commands_U0_ap_ready;
wire    ap_sync_swiftkv_broadcast_pe_commands_U0_ap_ready;
reg    ap_sync_reg_swiftkv_broadcast_rope_U0_ap_ready;
wire    ap_sync_swiftkv_broadcast_rope_U0_ap_ready;
reg    ap_sync_reg_swiftkv_run_pe_0_U0_ap_ready;
wire    ap_sync_swiftkv_run_pe_0_U0_ap_ready;
reg    ap_sync_reg_swiftkv_run_pe_1_U0_ap_ready;
wire    ap_sync_swiftkv_run_pe_1_U0_ap_ready;
reg    ap_sync_reg_swiftkv_run_pe_2_U0_ap_ready;
wire    ap_sync_swiftkv_run_pe_2_U0_ap_ready;
reg    ap_sync_reg_swiftkv_run_pe_3_U0_ap_ready;
wire    ap_sync_swiftkv_run_pe_3_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_swiftkv_gather_attention_streams_U0_ap_start = 1'b0;
#0 ap_sync_reg_swiftkv_broadcast_pe_commands_U0_ap_ready = 1'b0;
#0 ap_sync_reg_swiftkv_broadcast_rope_U0_ap_ready = 1'b0;
#0 ap_sync_reg_swiftkv_run_pe_0_U0_ap_ready = 1'b0;
#0 ap_sync_reg_swiftkv_run_pe_1_U0_ap_ready = 1'b0;
#0 ap_sync_reg_swiftkv_run_pe_2_U0_ap_ready = 1'b0;
#0 ap_sync_reg_swiftkv_run_pe_3_U0_ap_ready = 1'b0;
end

int4_decoder_token_controller_swiftkv_broadcast_pe_commands swiftkv_broadcast_pe_commands_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(swiftkv_broadcast_pe_commands_U0_ap_start),
    .ap_done(swiftkv_broadcast_pe_commands_U0_ap_done),
    .ap_continue(swiftkv_broadcast_pe_commands_U0_ap_continue),
    .ap_idle(swiftkv_broadcast_pe_commands_U0_ap_idle),
    .ap_ready(swiftkv_broadcast_pe_commands_U0_ap_ready),
    .swiftkv_command_pe0_din(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe0_din),
    .swiftkv_command_pe0_num_data_valid(swiftkv_command_pe0_num_data_valid),
    .swiftkv_command_pe0_fifo_cap(swiftkv_command_pe0_fifo_cap),
    .swiftkv_command_pe0_full_n(swiftkv_command_pe0_full_n),
    .swiftkv_command_pe0_write(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe0_write),
    .swiftkv_command_pe1_din(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe1_din),
    .swiftkv_command_pe1_num_data_valid(swiftkv_command_pe1_num_data_valid),
    .swiftkv_command_pe1_fifo_cap(swiftkv_command_pe1_fifo_cap),
    .swiftkv_command_pe1_full_n(swiftkv_command_pe1_full_n),
    .swiftkv_command_pe1_write(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe1_write),
    .swiftkv_command_pe2_din(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe2_din),
    .swiftkv_command_pe2_num_data_valid(swiftkv_command_pe2_num_data_valid),
    .swiftkv_command_pe2_fifo_cap(swiftkv_command_pe2_fifo_cap),
    .swiftkv_command_pe2_full_n(swiftkv_command_pe2_full_n),
    .swiftkv_command_pe2_write(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe2_write),
    .swiftkv_command_pe3_din(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe3_din),
    .swiftkv_command_pe3_num_data_valid(swiftkv_command_pe3_num_data_valid),
    .swiftkv_command_pe3_fifo_cap(swiftkv_command_pe3_fifo_cap),
    .swiftkv_command_pe3_full_n(swiftkv_command_pe3_full_n),
    .swiftkv_command_pe3_write(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe3_write),
    .layer_index(controller_layer_index_val),
    .position(controller_position_val)
);

int4_decoder_token_controller_swiftkv_broadcast_rope swiftkv_broadcast_rope_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(swiftkv_broadcast_rope_U0_ap_start),
    .ap_done(swiftkv_broadcast_rope_U0_ap_done),
    .ap_continue(swiftkv_broadcast_rope_U0_ap_continue),
    .ap_idle(swiftkv_broadcast_rope_U0_ap_idle),
    .ap_ready(swiftkv_broadcast_rope_U0_ap_ready),
    .cos_pe0_din(swiftkv_broadcast_rope_U0_cos_pe0_din),
    .cos_pe0_num_data_valid(cos_pe0_num_data_valid),
    .cos_pe0_fifo_cap(cos_pe0_fifo_cap),
    .cos_pe0_full_n(cos_pe0_full_n),
    .cos_pe0_write(swiftkv_broadcast_rope_U0_cos_pe0_write),
    .cos_pe1_din(swiftkv_broadcast_rope_U0_cos_pe1_din),
    .cos_pe1_num_data_valid(cos_pe1_num_data_valid),
    .cos_pe1_fifo_cap(cos_pe1_fifo_cap),
    .cos_pe1_full_n(cos_pe1_full_n),
    .cos_pe1_write(swiftkv_broadcast_rope_U0_cos_pe1_write),
    .cos_pe2_din(swiftkv_broadcast_rope_U0_cos_pe2_din),
    .cos_pe2_num_data_valid(cos_pe2_num_data_valid),
    .cos_pe2_fifo_cap(cos_pe2_fifo_cap),
    .cos_pe2_full_n(cos_pe2_full_n),
    .cos_pe2_write(swiftkv_broadcast_rope_U0_cos_pe2_write),
    .cos_pe3_din(swiftkv_broadcast_rope_U0_cos_pe3_din),
    .cos_pe3_num_data_valid(cos_pe3_num_data_valid),
    .cos_pe3_fifo_cap(cos_pe3_fifo_cap),
    .cos_pe3_full_n(cos_pe3_full_n),
    .cos_pe3_write(swiftkv_broadcast_rope_U0_cos_pe3_write),
    .sin_pe0_din(swiftkv_broadcast_rope_U0_sin_pe0_din),
    .sin_pe0_num_data_valid(sin_pe0_num_data_valid),
    .sin_pe0_fifo_cap(sin_pe0_fifo_cap),
    .sin_pe0_full_n(sin_pe0_full_n),
    .sin_pe0_write(swiftkv_broadcast_rope_U0_sin_pe0_write),
    .sin_pe1_din(swiftkv_broadcast_rope_U0_sin_pe1_din),
    .sin_pe1_num_data_valid(sin_pe1_num_data_valid),
    .sin_pe1_fifo_cap(sin_pe1_fifo_cap),
    .sin_pe1_full_n(sin_pe1_full_n),
    .sin_pe1_write(swiftkv_broadcast_rope_U0_sin_pe1_write),
    .sin_pe2_din(swiftkv_broadcast_rope_U0_sin_pe2_din),
    .sin_pe2_num_data_valid(sin_pe2_num_data_valid),
    .sin_pe2_fifo_cap(sin_pe2_fifo_cap),
    .sin_pe2_full_n(sin_pe2_full_n),
    .sin_pe2_write(swiftkv_broadcast_rope_U0_sin_pe2_write),
    .sin_pe3_din(swiftkv_broadcast_rope_U0_sin_pe3_din),
    .sin_pe3_num_data_valid(sin_pe3_num_data_valid),
    .sin_pe3_fifo_cap(sin_pe3_fifo_cap),
    .sin_pe3_full_n(sin_pe3_full_n),
    .sin_pe3_write(swiftkv_broadcast_rope_U0_sin_pe3_write),
    .current_cos_address0(swiftkv_broadcast_rope_U0_current_cos_address0),
    .current_cos_ce0(swiftkv_broadcast_rope_U0_current_cos_ce0),
    .current_cos_q0(current_cos_q0),
    .current_sin_address0(swiftkv_broadcast_rope_U0_current_sin_address0),
    .current_sin_ce0(swiftkv_broadcast_rope_U0_current_sin_ce0),
    .current_sin_q0(current_sin_q0)
);

int4_decoder_token_controller_swiftkv_run_pe_0_s swiftkv_run_pe_0_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(swiftkv_run_pe_0_U0_ap_start),
    .ap_done(swiftkv_run_pe_0_U0_ap_done),
    .ap_continue(swiftkv_run_pe_0_U0_ap_continue),
    .ap_idle(swiftkv_run_pe_0_U0_ap_idle),
    .ap_ready(swiftkv_run_pe_0_U0_ap_ready),
    .q_address0(swiftkv_run_pe_0_U0_q_address0),
    .q_ce0(swiftkv_run_pe_0_U0_q_ce0),
    .q_q0(q_pe0_q0),
    .k_address0(swiftkv_run_pe_0_U0_k_address0),
    .k_ce0(swiftkv_run_pe_0_U0_k_ce0),
    .k_q0(k_pe0_q0),
    .v_address0(swiftkv_run_pe_0_U0_v_address0),
    .v_ce0(swiftkv_run_pe_0_U0_v_ce0),
    .v_q0(v_pe0_q0),
    .m_axi_gmem0_AWVALID(swiftkv_run_pe_0_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(m_axi_gmem0_AWREADY),
    .m_axi_gmem0_AWADDR(swiftkv_run_pe_0_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(swiftkv_run_pe_0_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(swiftkv_run_pe_0_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(swiftkv_run_pe_0_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(swiftkv_run_pe_0_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(swiftkv_run_pe_0_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(swiftkv_run_pe_0_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(swiftkv_run_pe_0_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(swiftkv_run_pe_0_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(swiftkv_run_pe_0_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(swiftkv_run_pe_0_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(swiftkv_run_pe_0_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(m_axi_gmem0_WREADY),
    .m_axi_gmem0_WDATA(swiftkv_run_pe_0_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(swiftkv_run_pe_0_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(swiftkv_run_pe_0_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(swiftkv_run_pe_0_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(swiftkv_run_pe_0_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(swiftkv_run_pe_0_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(swiftkv_run_pe_0_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(swiftkv_run_pe_0_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(swiftkv_run_pe_0_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(swiftkv_run_pe_0_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(swiftkv_run_pe_0_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(swiftkv_run_pe_0_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(swiftkv_run_pe_0_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(swiftkv_run_pe_0_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(swiftkv_run_pe_0_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(swiftkv_run_pe_0_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(swiftkv_run_pe_0_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(swiftkv_run_pe_0_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(m_axi_gmem0_BVALID),
    .m_axi_gmem0_BREADY(swiftkv_run_pe_0_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(m_axi_gmem0_BRESP),
    .m_axi_gmem0_BID(m_axi_gmem0_BID),
    .m_axi_gmem0_BUSER(m_axi_gmem0_BUSER),
    .kv_cache(kv_cache_pe0),
    .cos_pe0_dout(cos_pe0_dout),
    .cos_pe0_num_data_valid(cos_pe0_num_data_valid),
    .cos_pe0_fifo_cap(cos_pe0_fifo_cap),
    .cos_pe0_empty_n(cos_pe0_empty_n),
    .cos_pe0_read(swiftkv_run_pe_0_U0_cos_pe0_read),
    .sin_pe0_dout(sin_pe0_dout),
    .sin_pe0_num_data_valid(sin_pe0_num_data_valid),
    .sin_pe0_fifo_cap(sin_pe0_fifo_cap),
    .sin_pe0_empty_n(sin_pe0_empty_n),
    .sin_pe0_read(swiftkv_run_pe_0_U0_sin_pe0_read),
    .quantized_pe0_din(swiftkv_run_pe_0_U0_quantized_pe0_din),
    .quantized_pe0_num_data_valid(quantized_pe0_num_data_valid),
    .quantized_pe0_fifo_cap(quantized_pe0_fifo_cap),
    .quantized_pe0_full_n(quantized_pe0_full_n),
    .quantized_pe0_write(swiftkv_run_pe_0_U0_quantized_pe0_write),
    .scale_pe0_din(swiftkv_run_pe_0_U0_scale_pe0_din),
    .scale_pe0_num_data_valid(scale_pe0_num_data_valid),
    .scale_pe0_fifo_cap(scale_pe0_fifo_cap),
    .scale_pe0_full_n(scale_pe0_full_n),
    .scale_pe0_write(swiftkv_run_pe_0_U0_scale_pe0_write),
    .swiftkv_command_pe0_dout(swiftkv_command_pe0_dout),
    .swiftkv_command_pe0_num_data_valid(swiftkv_command_pe0_num_data_valid),
    .swiftkv_command_pe0_fifo_cap(swiftkv_command_pe0_fifo_cap),
    .swiftkv_command_pe0_empty_n(swiftkv_command_pe0_empty_n),
    .swiftkv_command_pe0_read(swiftkv_run_pe_0_U0_swiftkv_command_pe0_read)
);

int4_decoder_token_controller_swiftkv_run_pe_1_s swiftkv_run_pe_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(swiftkv_run_pe_1_U0_ap_start),
    .ap_done(swiftkv_run_pe_1_U0_ap_done),
    .ap_continue(swiftkv_run_pe_1_U0_ap_continue),
    .ap_idle(swiftkv_run_pe_1_U0_ap_idle),
    .ap_ready(swiftkv_run_pe_1_U0_ap_ready),
    .q_address0(swiftkv_run_pe_1_U0_q_address0),
    .q_ce0(swiftkv_run_pe_1_U0_q_ce0),
    .q_q0(q_pe1_q0),
    .k_address0(swiftkv_run_pe_1_U0_k_address0),
    .k_ce0(swiftkv_run_pe_1_U0_k_ce0),
    .k_q0(k_pe1_q0),
    .v_address0(swiftkv_run_pe_1_U0_v_address0),
    .v_ce0(swiftkv_run_pe_1_U0_v_ce0),
    .v_q0(v_pe1_q0),
    .m_axi_gmem1_AWVALID(swiftkv_run_pe_1_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(m_axi_gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(swiftkv_run_pe_1_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(swiftkv_run_pe_1_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(swiftkv_run_pe_1_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(swiftkv_run_pe_1_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(swiftkv_run_pe_1_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(swiftkv_run_pe_1_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(swiftkv_run_pe_1_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(swiftkv_run_pe_1_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(swiftkv_run_pe_1_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(swiftkv_run_pe_1_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(swiftkv_run_pe_1_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(swiftkv_run_pe_1_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(m_axi_gmem1_WREADY),
    .m_axi_gmem1_WDATA(swiftkv_run_pe_1_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(swiftkv_run_pe_1_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(swiftkv_run_pe_1_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(swiftkv_run_pe_1_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(swiftkv_run_pe_1_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(swiftkv_run_pe_1_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(swiftkv_run_pe_1_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(swiftkv_run_pe_1_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(swiftkv_run_pe_1_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(swiftkv_run_pe_1_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(swiftkv_run_pe_1_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(swiftkv_run_pe_1_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(swiftkv_run_pe_1_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(swiftkv_run_pe_1_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(swiftkv_run_pe_1_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(swiftkv_run_pe_1_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(swiftkv_run_pe_1_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(swiftkv_run_pe_1_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RFIFONUM(m_axi_gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(m_axi_gmem1_BVALID),
    .m_axi_gmem1_BREADY(swiftkv_run_pe_1_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(m_axi_gmem1_BRESP),
    .m_axi_gmem1_BID(m_axi_gmem1_BID),
    .m_axi_gmem1_BUSER(m_axi_gmem1_BUSER),
    .kv_cache(kv_cache_pe1),
    .cos_pe1_dout(cos_pe1_dout),
    .cos_pe1_num_data_valid(cos_pe1_num_data_valid),
    .cos_pe1_fifo_cap(cos_pe1_fifo_cap),
    .cos_pe1_empty_n(cos_pe1_empty_n),
    .cos_pe1_read(swiftkv_run_pe_1_U0_cos_pe1_read),
    .sin_pe1_dout(sin_pe1_dout),
    .sin_pe1_num_data_valid(sin_pe1_num_data_valid),
    .sin_pe1_fifo_cap(sin_pe1_fifo_cap),
    .sin_pe1_empty_n(sin_pe1_empty_n),
    .sin_pe1_read(swiftkv_run_pe_1_U0_sin_pe1_read),
    .quantized_pe1_din(swiftkv_run_pe_1_U0_quantized_pe1_din),
    .quantized_pe1_num_data_valid(quantized_pe1_num_data_valid),
    .quantized_pe1_fifo_cap(quantized_pe1_fifo_cap),
    .quantized_pe1_full_n(quantized_pe1_full_n),
    .quantized_pe1_write(swiftkv_run_pe_1_U0_quantized_pe1_write),
    .scale_pe1_din(swiftkv_run_pe_1_U0_scale_pe1_din),
    .scale_pe1_num_data_valid(scale_pe1_num_data_valid),
    .scale_pe1_fifo_cap(scale_pe1_fifo_cap),
    .scale_pe1_full_n(scale_pe1_full_n),
    .scale_pe1_write(swiftkv_run_pe_1_U0_scale_pe1_write),
    .swiftkv_command_pe1_dout(swiftkv_command_pe1_dout),
    .swiftkv_command_pe1_num_data_valid(swiftkv_command_pe1_num_data_valid),
    .swiftkv_command_pe1_fifo_cap(swiftkv_command_pe1_fifo_cap),
    .swiftkv_command_pe1_empty_n(swiftkv_command_pe1_empty_n),
    .swiftkv_command_pe1_read(swiftkv_run_pe_1_U0_swiftkv_command_pe1_read)
);

int4_decoder_token_controller_swiftkv_run_pe_2_s swiftkv_run_pe_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(swiftkv_run_pe_2_U0_ap_start),
    .ap_done(swiftkv_run_pe_2_U0_ap_done),
    .ap_continue(swiftkv_run_pe_2_U0_ap_continue),
    .ap_idle(swiftkv_run_pe_2_U0_ap_idle),
    .ap_ready(swiftkv_run_pe_2_U0_ap_ready),
    .q_address0(swiftkv_run_pe_2_U0_q_address0),
    .q_ce0(swiftkv_run_pe_2_U0_q_ce0),
    .q_q0(q_pe2_q0),
    .k_address0(swiftkv_run_pe_2_U0_k_address0),
    .k_ce0(swiftkv_run_pe_2_U0_k_ce0),
    .k_q0(k_pe2_q0),
    .v_address0(swiftkv_run_pe_2_U0_v_address0),
    .v_ce0(swiftkv_run_pe_2_U0_v_ce0),
    .v_q0(v_pe2_q0),
    .m_axi_gmem2_AWVALID(swiftkv_run_pe_2_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(m_axi_gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(swiftkv_run_pe_2_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(swiftkv_run_pe_2_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(swiftkv_run_pe_2_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(swiftkv_run_pe_2_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(swiftkv_run_pe_2_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(swiftkv_run_pe_2_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(swiftkv_run_pe_2_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(swiftkv_run_pe_2_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(swiftkv_run_pe_2_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(swiftkv_run_pe_2_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(swiftkv_run_pe_2_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(swiftkv_run_pe_2_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(m_axi_gmem2_WREADY),
    .m_axi_gmem2_WDATA(swiftkv_run_pe_2_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(swiftkv_run_pe_2_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(swiftkv_run_pe_2_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(swiftkv_run_pe_2_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(swiftkv_run_pe_2_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(swiftkv_run_pe_2_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(m_axi_gmem2_ARREADY),
    .m_axi_gmem2_ARADDR(swiftkv_run_pe_2_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(swiftkv_run_pe_2_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(swiftkv_run_pe_2_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(swiftkv_run_pe_2_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(swiftkv_run_pe_2_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(swiftkv_run_pe_2_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(swiftkv_run_pe_2_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(swiftkv_run_pe_2_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(swiftkv_run_pe_2_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(swiftkv_run_pe_2_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(swiftkv_run_pe_2_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(m_axi_gmem2_RVALID),
    .m_axi_gmem2_RREADY(swiftkv_run_pe_2_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(m_axi_gmem2_RDATA),
    .m_axi_gmem2_RLAST(m_axi_gmem2_RLAST),
    .m_axi_gmem2_RID(m_axi_gmem2_RID),
    .m_axi_gmem2_RFIFONUM(m_axi_gmem2_RFIFONUM),
    .m_axi_gmem2_RUSER(m_axi_gmem2_RUSER),
    .m_axi_gmem2_RRESP(m_axi_gmem2_RRESP),
    .m_axi_gmem2_BVALID(m_axi_gmem2_BVALID),
    .m_axi_gmem2_BREADY(swiftkv_run_pe_2_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(m_axi_gmem2_BRESP),
    .m_axi_gmem2_BID(m_axi_gmem2_BID),
    .m_axi_gmem2_BUSER(m_axi_gmem2_BUSER),
    .kv_cache(kv_cache_pe2),
    .cos_pe2_dout(cos_pe2_dout),
    .cos_pe2_num_data_valid(cos_pe2_num_data_valid),
    .cos_pe2_fifo_cap(cos_pe2_fifo_cap),
    .cos_pe2_empty_n(cos_pe2_empty_n),
    .cos_pe2_read(swiftkv_run_pe_2_U0_cos_pe2_read),
    .sin_pe2_dout(sin_pe2_dout),
    .sin_pe2_num_data_valid(sin_pe2_num_data_valid),
    .sin_pe2_fifo_cap(sin_pe2_fifo_cap),
    .sin_pe2_empty_n(sin_pe2_empty_n),
    .sin_pe2_read(swiftkv_run_pe_2_U0_sin_pe2_read),
    .quantized_pe2_din(swiftkv_run_pe_2_U0_quantized_pe2_din),
    .quantized_pe2_num_data_valid(quantized_pe2_num_data_valid),
    .quantized_pe2_fifo_cap(quantized_pe2_fifo_cap),
    .quantized_pe2_full_n(quantized_pe2_full_n),
    .quantized_pe2_write(swiftkv_run_pe_2_U0_quantized_pe2_write),
    .scale_pe2_din(swiftkv_run_pe_2_U0_scale_pe2_din),
    .scale_pe2_num_data_valid(scale_pe2_num_data_valid),
    .scale_pe2_fifo_cap(scale_pe2_fifo_cap),
    .scale_pe2_full_n(scale_pe2_full_n),
    .scale_pe2_write(swiftkv_run_pe_2_U0_scale_pe2_write),
    .swiftkv_command_pe2_dout(swiftkv_command_pe2_dout),
    .swiftkv_command_pe2_num_data_valid(swiftkv_command_pe2_num_data_valid),
    .swiftkv_command_pe2_fifo_cap(swiftkv_command_pe2_fifo_cap),
    .swiftkv_command_pe2_empty_n(swiftkv_command_pe2_empty_n),
    .swiftkv_command_pe2_read(swiftkv_run_pe_2_U0_swiftkv_command_pe2_read)
);

int4_decoder_token_controller_swiftkv_run_pe_3_s swiftkv_run_pe_3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(swiftkv_run_pe_3_U0_ap_start),
    .ap_done(swiftkv_run_pe_3_U0_ap_done),
    .ap_continue(swiftkv_run_pe_3_U0_ap_continue),
    .ap_idle(swiftkv_run_pe_3_U0_ap_idle),
    .ap_ready(swiftkv_run_pe_3_U0_ap_ready),
    .q_address0(swiftkv_run_pe_3_U0_q_address0),
    .q_ce0(swiftkv_run_pe_3_U0_q_ce0),
    .q_q0(q_pe3_q0),
    .k_address0(swiftkv_run_pe_3_U0_k_address0),
    .k_ce0(swiftkv_run_pe_3_U0_k_ce0),
    .k_q0(k_pe3_q0),
    .v_address0(swiftkv_run_pe_3_U0_v_address0),
    .v_ce0(swiftkv_run_pe_3_U0_v_ce0),
    .v_q0(v_pe3_q0),
    .m_axi_gmem3_AWVALID(swiftkv_run_pe_3_U0_m_axi_gmem3_AWVALID),
    .m_axi_gmem3_AWREADY(m_axi_gmem3_AWREADY),
    .m_axi_gmem3_AWADDR(swiftkv_run_pe_3_U0_m_axi_gmem3_AWADDR),
    .m_axi_gmem3_AWID(swiftkv_run_pe_3_U0_m_axi_gmem3_AWID),
    .m_axi_gmem3_AWLEN(swiftkv_run_pe_3_U0_m_axi_gmem3_AWLEN),
    .m_axi_gmem3_AWSIZE(swiftkv_run_pe_3_U0_m_axi_gmem3_AWSIZE),
    .m_axi_gmem3_AWBURST(swiftkv_run_pe_3_U0_m_axi_gmem3_AWBURST),
    .m_axi_gmem3_AWLOCK(swiftkv_run_pe_3_U0_m_axi_gmem3_AWLOCK),
    .m_axi_gmem3_AWCACHE(swiftkv_run_pe_3_U0_m_axi_gmem3_AWCACHE),
    .m_axi_gmem3_AWPROT(swiftkv_run_pe_3_U0_m_axi_gmem3_AWPROT),
    .m_axi_gmem3_AWQOS(swiftkv_run_pe_3_U0_m_axi_gmem3_AWQOS),
    .m_axi_gmem3_AWREGION(swiftkv_run_pe_3_U0_m_axi_gmem3_AWREGION),
    .m_axi_gmem3_AWUSER(swiftkv_run_pe_3_U0_m_axi_gmem3_AWUSER),
    .m_axi_gmem3_WVALID(swiftkv_run_pe_3_U0_m_axi_gmem3_WVALID),
    .m_axi_gmem3_WREADY(m_axi_gmem3_WREADY),
    .m_axi_gmem3_WDATA(swiftkv_run_pe_3_U0_m_axi_gmem3_WDATA),
    .m_axi_gmem3_WSTRB(swiftkv_run_pe_3_U0_m_axi_gmem3_WSTRB),
    .m_axi_gmem3_WLAST(swiftkv_run_pe_3_U0_m_axi_gmem3_WLAST),
    .m_axi_gmem3_WID(swiftkv_run_pe_3_U0_m_axi_gmem3_WID),
    .m_axi_gmem3_WUSER(swiftkv_run_pe_3_U0_m_axi_gmem3_WUSER),
    .m_axi_gmem3_ARVALID(swiftkv_run_pe_3_U0_m_axi_gmem3_ARVALID),
    .m_axi_gmem3_ARREADY(m_axi_gmem3_ARREADY),
    .m_axi_gmem3_ARADDR(swiftkv_run_pe_3_U0_m_axi_gmem3_ARADDR),
    .m_axi_gmem3_ARID(swiftkv_run_pe_3_U0_m_axi_gmem3_ARID),
    .m_axi_gmem3_ARLEN(swiftkv_run_pe_3_U0_m_axi_gmem3_ARLEN),
    .m_axi_gmem3_ARSIZE(swiftkv_run_pe_3_U0_m_axi_gmem3_ARSIZE),
    .m_axi_gmem3_ARBURST(swiftkv_run_pe_3_U0_m_axi_gmem3_ARBURST),
    .m_axi_gmem3_ARLOCK(swiftkv_run_pe_3_U0_m_axi_gmem3_ARLOCK),
    .m_axi_gmem3_ARCACHE(swiftkv_run_pe_3_U0_m_axi_gmem3_ARCACHE),
    .m_axi_gmem3_ARPROT(swiftkv_run_pe_3_U0_m_axi_gmem3_ARPROT),
    .m_axi_gmem3_ARQOS(swiftkv_run_pe_3_U0_m_axi_gmem3_ARQOS),
    .m_axi_gmem3_ARREGION(swiftkv_run_pe_3_U0_m_axi_gmem3_ARREGION),
    .m_axi_gmem3_ARUSER(swiftkv_run_pe_3_U0_m_axi_gmem3_ARUSER),
    .m_axi_gmem3_RVALID(m_axi_gmem3_RVALID),
    .m_axi_gmem3_RREADY(swiftkv_run_pe_3_U0_m_axi_gmem3_RREADY),
    .m_axi_gmem3_RDATA(m_axi_gmem3_RDATA),
    .m_axi_gmem3_RLAST(m_axi_gmem3_RLAST),
    .m_axi_gmem3_RID(m_axi_gmem3_RID),
    .m_axi_gmem3_RFIFONUM(m_axi_gmem3_RFIFONUM),
    .m_axi_gmem3_RUSER(m_axi_gmem3_RUSER),
    .m_axi_gmem3_RRESP(m_axi_gmem3_RRESP),
    .m_axi_gmem3_BVALID(m_axi_gmem3_BVALID),
    .m_axi_gmem3_BREADY(swiftkv_run_pe_3_U0_m_axi_gmem3_BREADY),
    .m_axi_gmem3_BRESP(m_axi_gmem3_BRESP),
    .m_axi_gmem3_BID(m_axi_gmem3_BID),
    .m_axi_gmem3_BUSER(m_axi_gmem3_BUSER),
    .kv_cache(kv_cache_pe3),
    .cos_pe3_dout(cos_pe3_dout),
    .cos_pe3_num_data_valid(cos_pe3_num_data_valid),
    .cos_pe3_fifo_cap(cos_pe3_fifo_cap),
    .cos_pe3_empty_n(cos_pe3_empty_n),
    .cos_pe3_read(swiftkv_run_pe_3_U0_cos_pe3_read),
    .sin_pe3_dout(sin_pe3_dout),
    .sin_pe3_num_data_valid(sin_pe3_num_data_valid),
    .sin_pe3_fifo_cap(sin_pe3_fifo_cap),
    .sin_pe3_empty_n(sin_pe3_empty_n),
    .sin_pe3_read(swiftkv_run_pe_3_U0_sin_pe3_read),
    .quantized_pe3_din(swiftkv_run_pe_3_U0_quantized_pe3_din),
    .quantized_pe3_num_data_valid(quantized_pe3_num_data_valid),
    .quantized_pe3_fifo_cap(quantized_pe3_fifo_cap),
    .quantized_pe3_full_n(quantized_pe3_full_n),
    .quantized_pe3_write(swiftkv_run_pe_3_U0_quantized_pe3_write),
    .scale_pe3_din(swiftkv_run_pe_3_U0_scale_pe3_din),
    .scale_pe3_num_data_valid(scale_pe3_num_data_valid),
    .scale_pe3_fifo_cap(scale_pe3_fifo_cap),
    .scale_pe3_full_n(scale_pe3_full_n),
    .scale_pe3_write(swiftkv_run_pe_3_U0_scale_pe3_write),
    .swiftkv_command_pe3_dout(swiftkv_command_pe3_dout),
    .swiftkv_command_pe3_num_data_valid(swiftkv_command_pe3_num_data_valid),
    .swiftkv_command_pe3_fifo_cap(swiftkv_command_pe3_fifo_cap),
    .swiftkv_command_pe3_empty_n(swiftkv_command_pe3_empty_n),
    .swiftkv_command_pe3_read(swiftkv_run_pe_3_U0_swiftkv_command_pe3_read)
);

int4_decoder_token_controller_swiftkv_gather_attention_streams swiftkv_gather_attention_streams_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(swiftkv_gather_attention_streams_U0_ap_start),
    .ap_done(swiftkv_gather_attention_streams_U0_ap_done),
    .ap_continue(swiftkv_gather_attention_streams_U0_ap_continue),
    .ap_idle(swiftkv_gather_attention_streams_U0_ap_idle),
    .ap_ready(swiftkv_gather_attention_streams_U0_ap_ready),
    .quantized_pe2_dout(quantized_pe2_dout),
    .quantized_pe2_num_data_valid(quantized_pe2_num_data_valid),
    .quantized_pe2_fifo_cap(quantized_pe2_fifo_cap),
    .quantized_pe2_empty_n(quantized_pe2_empty_n),
    .quantized_pe2_read(swiftkv_gather_attention_streams_U0_quantized_pe2_read),
    .scale_pe2_dout(scale_pe2_dout),
    .scale_pe2_num_data_valid(scale_pe2_num_data_valid),
    .scale_pe2_fifo_cap(scale_pe2_fifo_cap),
    .scale_pe2_empty_n(scale_pe2_empty_n),
    .scale_pe2_read(swiftkv_gather_attention_streams_U0_scale_pe2_read),
    .quantized_pe1_dout(quantized_pe1_dout),
    .quantized_pe1_num_data_valid(quantized_pe1_num_data_valid),
    .quantized_pe1_fifo_cap(quantized_pe1_fifo_cap),
    .quantized_pe1_empty_n(quantized_pe1_empty_n),
    .quantized_pe1_read(swiftkv_gather_attention_streams_U0_quantized_pe1_read),
    .scale_pe1_dout(scale_pe1_dout),
    .scale_pe1_num_data_valid(scale_pe1_num_data_valid),
    .scale_pe1_fifo_cap(scale_pe1_fifo_cap),
    .scale_pe1_empty_n(scale_pe1_empty_n),
    .scale_pe1_read(swiftkv_gather_attention_streams_U0_scale_pe1_read),
    .quantized_pe0_dout(quantized_pe0_dout),
    .quantized_pe0_num_data_valid(quantized_pe0_num_data_valid),
    .quantized_pe0_fifo_cap(quantized_pe0_fifo_cap),
    .quantized_pe0_empty_n(quantized_pe0_empty_n),
    .quantized_pe0_read(swiftkv_gather_attention_streams_U0_quantized_pe0_read),
    .scale_pe0_dout(scale_pe0_dout),
    .scale_pe0_num_data_valid(scale_pe0_num_data_valid),
    .scale_pe0_fifo_cap(scale_pe0_fifo_cap),
    .scale_pe0_empty_n(scale_pe0_empty_n),
    .scale_pe0_read(swiftkv_gather_attention_streams_U0_scale_pe0_read),
    .quantized_pe3_dout(quantized_pe3_dout),
    .quantized_pe3_num_data_valid(quantized_pe3_num_data_valid),
    .quantized_pe3_fifo_cap(quantized_pe3_fifo_cap),
    .quantized_pe3_empty_n(quantized_pe3_empty_n),
    .quantized_pe3_read(swiftkv_gather_attention_streams_U0_quantized_pe3_read),
    .scale_pe3_dout(scale_pe3_dout),
    .scale_pe3_num_data_valid(scale_pe3_num_data_valid),
    .scale_pe3_fifo_cap(scale_pe3_fifo_cap),
    .scale_pe3_empty_n(scale_pe3_empty_n),
    .scale_pe3_read(swiftkv_gather_attention_streams_U0_scale_pe3_read),
    .activation_q_address0(swiftkv_gather_attention_streams_U0_activation_q_address0),
    .activation_q_ce0(swiftkv_gather_attention_streams_U0_activation_q_ce0),
    .activation_q_we0(swiftkv_gather_attention_streams_U0_activation_q_we0),
    .activation_q_d0(swiftkv_gather_attention_streams_U0_activation_q_d0),
    .activation_scale_address0(swiftkv_gather_attention_streams_U0_activation_scale_address0),
    .activation_scale_ce0(swiftkv_gather_attention_streams_U0_activation_scale_ce0),
    .activation_scale_we0(swiftkv_gather_attention_streams_U0_activation_scale_we0),
    .activation_scale_d0(swiftkv_gather_attention_streams_U0_activation_scale_d0)
);

int4_decoder_token_controller_fifo_w18_d2_S swiftkv_command_pe0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe0_din),
    .if_full_n(swiftkv_command_pe0_full_n),
    .if_write(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe0_write),
    .if_dout(swiftkv_command_pe0_dout),
    .if_num_data_valid(swiftkv_command_pe0_num_data_valid),
    .if_fifo_cap(swiftkv_command_pe0_fifo_cap),
    .if_empty_n(swiftkv_command_pe0_empty_n),
    .if_read(swiftkv_run_pe_0_U0_swiftkv_command_pe0_read)
);

int4_decoder_token_controller_fifo_w18_d2_S swiftkv_command_pe1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe1_din),
    .if_full_n(swiftkv_command_pe1_full_n),
    .if_write(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe1_write),
    .if_dout(swiftkv_command_pe1_dout),
    .if_num_data_valid(swiftkv_command_pe1_num_data_valid),
    .if_fifo_cap(swiftkv_command_pe1_fifo_cap),
    .if_empty_n(swiftkv_command_pe1_empty_n),
    .if_read(swiftkv_run_pe_1_U0_swiftkv_command_pe1_read)
);

int4_decoder_token_controller_fifo_w18_d2_S swiftkv_command_pe2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe2_din),
    .if_full_n(swiftkv_command_pe2_full_n),
    .if_write(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe2_write),
    .if_dout(swiftkv_command_pe2_dout),
    .if_num_data_valid(swiftkv_command_pe2_num_data_valid),
    .if_fifo_cap(swiftkv_command_pe2_fifo_cap),
    .if_empty_n(swiftkv_command_pe2_empty_n),
    .if_read(swiftkv_run_pe_2_U0_swiftkv_command_pe2_read)
);

int4_decoder_token_controller_fifo_w18_d2_S swiftkv_command_pe3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe3_din),
    .if_full_n(swiftkv_command_pe3_full_n),
    .if_write(swiftkv_broadcast_pe_commands_U0_swiftkv_command_pe3_write),
    .if_dout(swiftkv_command_pe3_dout),
    .if_num_data_valid(swiftkv_command_pe3_num_data_valid),
    .if_fifo_cap(swiftkv_command_pe3_fifo_cap),
    .if_empty_n(swiftkv_command_pe3_empty_n),
    .if_read(swiftkv_run_pe_3_U0_swiftkv_command_pe3_read)
);

int4_decoder_token_controller_fifo_w19_d4_S cos_pe0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_rope_U0_cos_pe0_din),
    .if_full_n(cos_pe0_full_n),
    .if_write(swiftkv_broadcast_rope_U0_cos_pe0_write),
    .if_dout(cos_pe0_dout),
    .if_num_data_valid(cos_pe0_num_data_valid),
    .if_fifo_cap(cos_pe0_fifo_cap),
    .if_empty_n(cos_pe0_empty_n),
    .if_read(swiftkv_run_pe_0_U0_cos_pe0_read)
);

int4_decoder_token_controller_fifo_w19_d4_S cos_pe1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_rope_U0_cos_pe1_din),
    .if_full_n(cos_pe1_full_n),
    .if_write(swiftkv_broadcast_rope_U0_cos_pe1_write),
    .if_dout(cos_pe1_dout),
    .if_num_data_valid(cos_pe1_num_data_valid),
    .if_fifo_cap(cos_pe1_fifo_cap),
    .if_empty_n(cos_pe1_empty_n),
    .if_read(swiftkv_run_pe_1_U0_cos_pe1_read)
);

int4_decoder_token_controller_fifo_w19_d4_S cos_pe2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_rope_U0_cos_pe2_din),
    .if_full_n(cos_pe2_full_n),
    .if_write(swiftkv_broadcast_rope_U0_cos_pe2_write),
    .if_dout(cos_pe2_dout),
    .if_num_data_valid(cos_pe2_num_data_valid),
    .if_fifo_cap(cos_pe2_fifo_cap),
    .if_empty_n(cos_pe2_empty_n),
    .if_read(swiftkv_run_pe_2_U0_cos_pe2_read)
);

int4_decoder_token_controller_fifo_w19_d4_S cos_pe3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_rope_U0_cos_pe3_din),
    .if_full_n(cos_pe3_full_n),
    .if_write(swiftkv_broadcast_rope_U0_cos_pe3_write),
    .if_dout(cos_pe3_dout),
    .if_num_data_valid(cos_pe3_num_data_valid),
    .if_fifo_cap(cos_pe3_fifo_cap),
    .if_empty_n(cos_pe3_empty_n),
    .if_read(swiftkv_run_pe_3_U0_cos_pe3_read)
);

int4_decoder_token_controller_fifo_w19_d4_S sin_pe0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_rope_U0_sin_pe0_din),
    .if_full_n(sin_pe0_full_n),
    .if_write(swiftkv_broadcast_rope_U0_sin_pe0_write),
    .if_dout(sin_pe0_dout),
    .if_num_data_valid(sin_pe0_num_data_valid),
    .if_fifo_cap(sin_pe0_fifo_cap),
    .if_empty_n(sin_pe0_empty_n),
    .if_read(swiftkv_run_pe_0_U0_sin_pe0_read)
);

int4_decoder_token_controller_fifo_w19_d4_S sin_pe1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_rope_U0_sin_pe1_din),
    .if_full_n(sin_pe1_full_n),
    .if_write(swiftkv_broadcast_rope_U0_sin_pe1_write),
    .if_dout(sin_pe1_dout),
    .if_num_data_valid(sin_pe1_num_data_valid),
    .if_fifo_cap(sin_pe1_fifo_cap),
    .if_empty_n(sin_pe1_empty_n),
    .if_read(swiftkv_run_pe_1_U0_sin_pe1_read)
);

int4_decoder_token_controller_fifo_w19_d4_S sin_pe2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_rope_U0_sin_pe2_din),
    .if_full_n(sin_pe2_full_n),
    .if_write(swiftkv_broadcast_rope_U0_sin_pe2_write),
    .if_dout(sin_pe2_dout),
    .if_num_data_valid(sin_pe2_num_data_valid),
    .if_fifo_cap(sin_pe2_fifo_cap),
    .if_empty_n(sin_pe2_empty_n),
    .if_read(swiftkv_run_pe_2_U0_sin_pe2_read)
);

int4_decoder_token_controller_fifo_w19_d4_S sin_pe3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_broadcast_rope_U0_sin_pe3_din),
    .if_full_n(sin_pe3_full_n),
    .if_write(swiftkv_broadcast_rope_U0_sin_pe3_write),
    .if_dout(sin_pe3_dout),
    .if_num_data_valid(sin_pe3_num_data_valid),
    .if_fifo_cap(sin_pe3_fifo_cap),
    .if_empty_n(sin_pe3_empty_n),
    .if_read(swiftkv_run_pe_3_U0_sin_pe3_read)
);

int4_decoder_token_controller_fifo_w480_d4_B quantized_pe0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_run_pe_0_U0_quantized_pe0_din),
    .if_full_n(quantized_pe0_full_n),
    .if_write(swiftkv_run_pe_0_U0_quantized_pe0_write),
    .if_dout(quantized_pe0_dout),
    .if_num_data_valid(quantized_pe0_num_data_valid),
    .if_fifo_cap(quantized_pe0_fifo_cap),
    .if_empty_n(quantized_pe0_empty_n),
    .if_read(swiftkv_gather_attention_streams_U0_quantized_pe0_read)
);

int4_decoder_token_controller_fifo_w32_d4_S_x scale_pe0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_run_pe_0_U0_scale_pe0_din),
    .if_full_n(scale_pe0_full_n),
    .if_write(swiftkv_run_pe_0_U0_scale_pe0_write),
    .if_dout(scale_pe0_dout),
    .if_num_data_valid(scale_pe0_num_data_valid),
    .if_fifo_cap(scale_pe0_fifo_cap),
    .if_empty_n(scale_pe0_empty_n),
    .if_read(swiftkv_gather_attention_streams_U0_scale_pe0_read)
);

int4_decoder_token_controller_fifo_w480_d4_B quantized_pe1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_run_pe_1_U0_quantized_pe1_din),
    .if_full_n(quantized_pe1_full_n),
    .if_write(swiftkv_run_pe_1_U0_quantized_pe1_write),
    .if_dout(quantized_pe1_dout),
    .if_num_data_valid(quantized_pe1_num_data_valid),
    .if_fifo_cap(quantized_pe1_fifo_cap),
    .if_empty_n(quantized_pe1_empty_n),
    .if_read(swiftkv_gather_attention_streams_U0_quantized_pe1_read)
);

int4_decoder_token_controller_fifo_w32_d4_S_x scale_pe1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_run_pe_1_U0_scale_pe1_din),
    .if_full_n(scale_pe1_full_n),
    .if_write(swiftkv_run_pe_1_U0_scale_pe1_write),
    .if_dout(scale_pe1_dout),
    .if_num_data_valid(scale_pe1_num_data_valid),
    .if_fifo_cap(scale_pe1_fifo_cap),
    .if_empty_n(scale_pe1_empty_n),
    .if_read(swiftkv_gather_attention_streams_U0_scale_pe1_read)
);

int4_decoder_token_controller_fifo_w480_d4_B quantized_pe2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_run_pe_2_U0_quantized_pe2_din),
    .if_full_n(quantized_pe2_full_n),
    .if_write(swiftkv_run_pe_2_U0_quantized_pe2_write),
    .if_dout(quantized_pe2_dout),
    .if_num_data_valid(quantized_pe2_num_data_valid),
    .if_fifo_cap(quantized_pe2_fifo_cap),
    .if_empty_n(quantized_pe2_empty_n),
    .if_read(swiftkv_gather_attention_streams_U0_quantized_pe2_read)
);

int4_decoder_token_controller_fifo_w32_d4_S_x scale_pe2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_run_pe_2_U0_scale_pe2_din),
    .if_full_n(scale_pe2_full_n),
    .if_write(swiftkv_run_pe_2_U0_scale_pe2_write),
    .if_dout(scale_pe2_dout),
    .if_num_data_valid(scale_pe2_num_data_valid),
    .if_fifo_cap(scale_pe2_fifo_cap),
    .if_empty_n(scale_pe2_empty_n),
    .if_read(swiftkv_gather_attention_streams_U0_scale_pe2_read)
);

int4_decoder_token_controller_fifo_w480_d4_B quantized_pe3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_run_pe_3_U0_quantized_pe3_din),
    .if_full_n(quantized_pe3_full_n),
    .if_write(swiftkv_run_pe_3_U0_quantized_pe3_write),
    .if_dout(quantized_pe3_dout),
    .if_num_data_valid(quantized_pe3_num_data_valid),
    .if_fifo_cap(quantized_pe3_fifo_cap),
    .if_empty_n(quantized_pe3_empty_n),
    .if_read(swiftkv_gather_attention_streams_U0_quantized_pe3_read)
);

int4_decoder_token_controller_fifo_w32_d4_S_x scale_pe3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(swiftkv_run_pe_3_U0_scale_pe3_din),
    .if_full_n(scale_pe3_full_n),
    .if_write(swiftkv_run_pe_3_U0_scale_pe3_write),
    .if_dout(scale_pe3_dout),
    .if_num_data_valid(scale_pe3_num_data_valid),
    .if_fifo_cap(scale_pe3_fifo_cap),
    .if_empty_n(scale_pe3_empty_n),
    .if_read(swiftkv_gather_attention_streams_U0_scale_pe3_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_swiftkv_broadcast_pe_commands_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_swiftkv_broadcast_pe_commands_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_swiftkv_broadcast_pe_commands_U0_ap_ready <= ap_sync_swiftkv_broadcast_pe_commands_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_swiftkv_broadcast_rope_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_swiftkv_broadcast_rope_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_swiftkv_broadcast_rope_U0_ap_ready <= ap_sync_swiftkv_broadcast_rope_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_swiftkv_gather_attention_streams_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_swiftkv_gather_attention_streams_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_swiftkv_run_pe_0_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_swiftkv_run_pe_0_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_swiftkv_run_pe_0_U0_ap_ready <= ap_sync_swiftkv_run_pe_0_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_swiftkv_run_pe_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_swiftkv_run_pe_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_swiftkv_run_pe_1_U0_ap_ready <= ap_sync_swiftkv_run_pe_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_swiftkv_run_pe_2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_swiftkv_run_pe_2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_swiftkv_run_pe_2_U0_ap_ready <= ap_sync_swiftkv_run_pe_2_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_swiftkv_run_pe_3_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_swiftkv_run_pe_3_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_swiftkv_run_pe_3_U0_ap_ready <= ap_sync_swiftkv_run_pe_3_U0_ap_ready;
        end
    end
end

assign activation_q_address0 = swiftkv_gather_attention_streams_U0_activation_q_address0;

assign activation_q_ce0 = swiftkv_gather_attention_streams_U0_activation_q_ce0;

assign activation_q_d0 = swiftkv_gather_attention_streams_U0_activation_q_d0;

assign activation_q_we0 = swiftkv_gather_attention_streams_U0_activation_q_we0;

assign activation_scale_address0 = swiftkv_gather_attention_streams_U0_activation_scale_address0;

assign activation_scale_ce0 = swiftkv_gather_attention_streams_U0_activation_scale_ce0;

assign activation_scale_d0 = swiftkv_gather_attention_streams_U0_activation_scale_d0;

assign activation_scale_we0 = swiftkv_gather_attention_streams_U0_activation_scale_we0;

assign ap_done = ap_sync_done;

assign ap_idle = (swiftkv_run_pe_3_U0_ap_idle & swiftkv_run_pe_2_U0_ap_idle & swiftkv_run_pe_1_U0_ap_idle & swiftkv_run_pe_0_U0_ap_idle & swiftkv_gather_attention_streams_U0_ap_idle & swiftkv_broadcast_rope_U0_ap_idle & swiftkv_broadcast_pe_commands_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (swiftkv_run_pe_3_U0_ap_done & swiftkv_run_pe_2_U0_ap_done & swiftkv_run_pe_1_U0_ap_done & swiftkv_run_pe_0_U0_ap_done & swiftkv_gather_attention_streams_U0_ap_done);

assign ap_sync_ready = (ap_sync_swiftkv_run_pe_3_U0_ap_ready & ap_sync_swiftkv_run_pe_2_U0_ap_ready & ap_sync_swiftkv_run_pe_1_U0_ap_ready & ap_sync_swiftkv_run_pe_0_U0_ap_ready & ap_sync_swiftkv_broadcast_rope_U0_ap_ready & ap_sync_swiftkv_broadcast_pe_commands_U0_ap_ready);

assign ap_sync_swiftkv_broadcast_pe_commands_U0_ap_ready = (swiftkv_broadcast_pe_commands_U0_ap_ready | ap_sync_reg_swiftkv_broadcast_pe_commands_U0_ap_ready);

assign ap_sync_swiftkv_broadcast_rope_U0_ap_ready = (swiftkv_broadcast_rope_U0_ap_ready | ap_sync_reg_swiftkv_broadcast_rope_U0_ap_ready);

assign ap_sync_swiftkv_run_pe_0_U0_ap_ready = (swiftkv_run_pe_0_U0_ap_ready | ap_sync_reg_swiftkv_run_pe_0_U0_ap_ready);

assign ap_sync_swiftkv_run_pe_1_U0_ap_ready = (swiftkv_run_pe_1_U0_ap_ready | ap_sync_reg_swiftkv_run_pe_1_U0_ap_ready);

assign ap_sync_swiftkv_run_pe_2_U0_ap_ready = (swiftkv_run_pe_2_U0_ap_ready | ap_sync_reg_swiftkv_run_pe_2_U0_ap_ready);

assign ap_sync_swiftkv_run_pe_3_U0_ap_ready = (swiftkv_run_pe_3_U0_ap_ready | ap_sync_reg_swiftkv_run_pe_3_U0_ap_ready);

assign current_cos_address0 = swiftkv_broadcast_rope_U0_current_cos_address0;

assign current_cos_ce0 = swiftkv_broadcast_rope_U0_current_cos_ce0;

assign current_cos_d0 = 19'd0;

assign current_cos_we0 = 1'b0;

assign current_sin_address0 = swiftkv_broadcast_rope_U0_current_sin_address0;

assign current_sin_ce0 = swiftkv_broadcast_rope_U0_current_sin_ce0;

assign current_sin_d0 = 19'd0;

assign current_sin_we0 = 1'b0;

assign k_pe0_address0 = swiftkv_run_pe_0_U0_k_address0;

assign k_pe0_ce0 = swiftkv_run_pe_0_U0_k_ce0;

assign k_pe0_d0 = 512'd0;

assign k_pe0_we0 = 1'b0;

assign k_pe1_address0 = swiftkv_run_pe_1_U0_k_address0;

assign k_pe1_ce0 = swiftkv_run_pe_1_U0_k_ce0;

assign k_pe1_d0 = 512'd0;

assign k_pe1_we0 = 1'b0;

assign k_pe2_address0 = swiftkv_run_pe_2_U0_k_address0;

assign k_pe2_ce0 = swiftkv_run_pe_2_U0_k_ce0;

assign k_pe2_d0 = 512'd0;

assign k_pe2_we0 = 1'b0;

assign k_pe3_address0 = swiftkv_run_pe_3_U0_k_address0;

assign k_pe3_ce0 = swiftkv_run_pe_3_U0_k_ce0;

assign k_pe3_d0 = 512'd0;

assign k_pe3_we0 = 1'b0;

assign m_axi_gmem0_ARADDR = swiftkv_run_pe_0_U0_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = swiftkv_run_pe_0_U0_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = swiftkv_run_pe_0_U0_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = swiftkv_run_pe_0_U0_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = swiftkv_run_pe_0_U0_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = swiftkv_run_pe_0_U0_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = swiftkv_run_pe_0_U0_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = swiftkv_run_pe_0_U0_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = swiftkv_run_pe_0_U0_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = swiftkv_run_pe_0_U0_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = swiftkv_run_pe_0_U0_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_ARVALID = swiftkv_run_pe_0_U0_m_axi_gmem0_ARVALID;

assign m_axi_gmem0_AWADDR = swiftkv_run_pe_0_U0_m_axi_gmem0_AWADDR;

assign m_axi_gmem0_AWBURST = swiftkv_run_pe_0_U0_m_axi_gmem0_AWBURST;

assign m_axi_gmem0_AWCACHE = swiftkv_run_pe_0_U0_m_axi_gmem0_AWCACHE;

assign m_axi_gmem0_AWID = swiftkv_run_pe_0_U0_m_axi_gmem0_AWID;

assign m_axi_gmem0_AWLEN = swiftkv_run_pe_0_U0_m_axi_gmem0_AWLEN;

assign m_axi_gmem0_AWLOCK = swiftkv_run_pe_0_U0_m_axi_gmem0_AWLOCK;

assign m_axi_gmem0_AWPROT = swiftkv_run_pe_0_U0_m_axi_gmem0_AWPROT;

assign m_axi_gmem0_AWQOS = swiftkv_run_pe_0_U0_m_axi_gmem0_AWQOS;

assign m_axi_gmem0_AWREGION = swiftkv_run_pe_0_U0_m_axi_gmem0_AWREGION;

assign m_axi_gmem0_AWSIZE = swiftkv_run_pe_0_U0_m_axi_gmem0_AWSIZE;

assign m_axi_gmem0_AWUSER = swiftkv_run_pe_0_U0_m_axi_gmem0_AWUSER;

assign m_axi_gmem0_AWVALID = swiftkv_run_pe_0_U0_m_axi_gmem0_AWVALID;

assign m_axi_gmem0_BREADY = swiftkv_run_pe_0_U0_m_axi_gmem0_BREADY;

assign m_axi_gmem0_RREADY = swiftkv_run_pe_0_U0_m_axi_gmem0_RREADY;

assign m_axi_gmem0_WDATA = swiftkv_run_pe_0_U0_m_axi_gmem0_WDATA;

assign m_axi_gmem0_WID = swiftkv_run_pe_0_U0_m_axi_gmem0_WID;

assign m_axi_gmem0_WLAST = swiftkv_run_pe_0_U0_m_axi_gmem0_WLAST;

assign m_axi_gmem0_WSTRB = swiftkv_run_pe_0_U0_m_axi_gmem0_WSTRB;

assign m_axi_gmem0_WUSER = swiftkv_run_pe_0_U0_m_axi_gmem0_WUSER;

assign m_axi_gmem0_WVALID = swiftkv_run_pe_0_U0_m_axi_gmem0_WVALID;

assign m_axi_gmem1_ARADDR = swiftkv_run_pe_1_U0_m_axi_gmem1_ARADDR;

assign m_axi_gmem1_ARBURST = swiftkv_run_pe_1_U0_m_axi_gmem1_ARBURST;

assign m_axi_gmem1_ARCACHE = swiftkv_run_pe_1_U0_m_axi_gmem1_ARCACHE;

assign m_axi_gmem1_ARID = swiftkv_run_pe_1_U0_m_axi_gmem1_ARID;

assign m_axi_gmem1_ARLEN = swiftkv_run_pe_1_U0_m_axi_gmem1_ARLEN;

assign m_axi_gmem1_ARLOCK = swiftkv_run_pe_1_U0_m_axi_gmem1_ARLOCK;

assign m_axi_gmem1_ARPROT = swiftkv_run_pe_1_U0_m_axi_gmem1_ARPROT;

assign m_axi_gmem1_ARQOS = swiftkv_run_pe_1_U0_m_axi_gmem1_ARQOS;

assign m_axi_gmem1_ARREGION = swiftkv_run_pe_1_U0_m_axi_gmem1_ARREGION;

assign m_axi_gmem1_ARSIZE = swiftkv_run_pe_1_U0_m_axi_gmem1_ARSIZE;

assign m_axi_gmem1_ARUSER = swiftkv_run_pe_1_U0_m_axi_gmem1_ARUSER;

assign m_axi_gmem1_ARVALID = swiftkv_run_pe_1_U0_m_axi_gmem1_ARVALID;

assign m_axi_gmem1_AWADDR = swiftkv_run_pe_1_U0_m_axi_gmem1_AWADDR;

assign m_axi_gmem1_AWBURST = swiftkv_run_pe_1_U0_m_axi_gmem1_AWBURST;

assign m_axi_gmem1_AWCACHE = swiftkv_run_pe_1_U0_m_axi_gmem1_AWCACHE;

assign m_axi_gmem1_AWID = swiftkv_run_pe_1_U0_m_axi_gmem1_AWID;

assign m_axi_gmem1_AWLEN = swiftkv_run_pe_1_U0_m_axi_gmem1_AWLEN;

assign m_axi_gmem1_AWLOCK = swiftkv_run_pe_1_U0_m_axi_gmem1_AWLOCK;

assign m_axi_gmem1_AWPROT = swiftkv_run_pe_1_U0_m_axi_gmem1_AWPROT;

assign m_axi_gmem1_AWQOS = swiftkv_run_pe_1_U0_m_axi_gmem1_AWQOS;

assign m_axi_gmem1_AWREGION = swiftkv_run_pe_1_U0_m_axi_gmem1_AWREGION;

assign m_axi_gmem1_AWSIZE = swiftkv_run_pe_1_U0_m_axi_gmem1_AWSIZE;

assign m_axi_gmem1_AWUSER = swiftkv_run_pe_1_U0_m_axi_gmem1_AWUSER;

assign m_axi_gmem1_AWVALID = swiftkv_run_pe_1_U0_m_axi_gmem1_AWVALID;

assign m_axi_gmem1_BREADY = swiftkv_run_pe_1_U0_m_axi_gmem1_BREADY;

assign m_axi_gmem1_RREADY = swiftkv_run_pe_1_U0_m_axi_gmem1_RREADY;

assign m_axi_gmem1_WDATA = swiftkv_run_pe_1_U0_m_axi_gmem1_WDATA;

assign m_axi_gmem1_WID = swiftkv_run_pe_1_U0_m_axi_gmem1_WID;

assign m_axi_gmem1_WLAST = swiftkv_run_pe_1_U0_m_axi_gmem1_WLAST;

assign m_axi_gmem1_WSTRB = swiftkv_run_pe_1_U0_m_axi_gmem1_WSTRB;

assign m_axi_gmem1_WUSER = swiftkv_run_pe_1_U0_m_axi_gmem1_WUSER;

assign m_axi_gmem1_WVALID = swiftkv_run_pe_1_U0_m_axi_gmem1_WVALID;

assign m_axi_gmem2_ARADDR = swiftkv_run_pe_2_U0_m_axi_gmem2_ARADDR;

assign m_axi_gmem2_ARBURST = swiftkv_run_pe_2_U0_m_axi_gmem2_ARBURST;

assign m_axi_gmem2_ARCACHE = swiftkv_run_pe_2_U0_m_axi_gmem2_ARCACHE;

assign m_axi_gmem2_ARID = swiftkv_run_pe_2_U0_m_axi_gmem2_ARID;

assign m_axi_gmem2_ARLEN = swiftkv_run_pe_2_U0_m_axi_gmem2_ARLEN;

assign m_axi_gmem2_ARLOCK = swiftkv_run_pe_2_U0_m_axi_gmem2_ARLOCK;

assign m_axi_gmem2_ARPROT = swiftkv_run_pe_2_U0_m_axi_gmem2_ARPROT;

assign m_axi_gmem2_ARQOS = swiftkv_run_pe_2_U0_m_axi_gmem2_ARQOS;

assign m_axi_gmem2_ARREGION = swiftkv_run_pe_2_U0_m_axi_gmem2_ARREGION;

assign m_axi_gmem2_ARSIZE = swiftkv_run_pe_2_U0_m_axi_gmem2_ARSIZE;

assign m_axi_gmem2_ARUSER = swiftkv_run_pe_2_U0_m_axi_gmem2_ARUSER;

assign m_axi_gmem2_ARVALID = swiftkv_run_pe_2_U0_m_axi_gmem2_ARVALID;

assign m_axi_gmem2_AWADDR = swiftkv_run_pe_2_U0_m_axi_gmem2_AWADDR;

assign m_axi_gmem2_AWBURST = swiftkv_run_pe_2_U0_m_axi_gmem2_AWBURST;

assign m_axi_gmem2_AWCACHE = swiftkv_run_pe_2_U0_m_axi_gmem2_AWCACHE;

assign m_axi_gmem2_AWID = swiftkv_run_pe_2_U0_m_axi_gmem2_AWID;

assign m_axi_gmem2_AWLEN = swiftkv_run_pe_2_U0_m_axi_gmem2_AWLEN;

assign m_axi_gmem2_AWLOCK = swiftkv_run_pe_2_U0_m_axi_gmem2_AWLOCK;

assign m_axi_gmem2_AWPROT = swiftkv_run_pe_2_U0_m_axi_gmem2_AWPROT;

assign m_axi_gmem2_AWQOS = swiftkv_run_pe_2_U0_m_axi_gmem2_AWQOS;

assign m_axi_gmem2_AWREGION = swiftkv_run_pe_2_U0_m_axi_gmem2_AWREGION;

assign m_axi_gmem2_AWSIZE = swiftkv_run_pe_2_U0_m_axi_gmem2_AWSIZE;

assign m_axi_gmem2_AWUSER = swiftkv_run_pe_2_U0_m_axi_gmem2_AWUSER;

assign m_axi_gmem2_AWVALID = swiftkv_run_pe_2_U0_m_axi_gmem2_AWVALID;

assign m_axi_gmem2_BREADY = swiftkv_run_pe_2_U0_m_axi_gmem2_BREADY;

assign m_axi_gmem2_RREADY = swiftkv_run_pe_2_U0_m_axi_gmem2_RREADY;

assign m_axi_gmem2_WDATA = swiftkv_run_pe_2_U0_m_axi_gmem2_WDATA;

assign m_axi_gmem2_WID = swiftkv_run_pe_2_U0_m_axi_gmem2_WID;

assign m_axi_gmem2_WLAST = swiftkv_run_pe_2_U0_m_axi_gmem2_WLAST;

assign m_axi_gmem2_WSTRB = swiftkv_run_pe_2_U0_m_axi_gmem2_WSTRB;

assign m_axi_gmem2_WUSER = swiftkv_run_pe_2_U0_m_axi_gmem2_WUSER;

assign m_axi_gmem2_WVALID = swiftkv_run_pe_2_U0_m_axi_gmem2_WVALID;

assign m_axi_gmem3_ARADDR = swiftkv_run_pe_3_U0_m_axi_gmem3_ARADDR;

assign m_axi_gmem3_ARBURST = swiftkv_run_pe_3_U0_m_axi_gmem3_ARBURST;

assign m_axi_gmem3_ARCACHE = swiftkv_run_pe_3_U0_m_axi_gmem3_ARCACHE;

assign m_axi_gmem3_ARID = swiftkv_run_pe_3_U0_m_axi_gmem3_ARID;

assign m_axi_gmem3_ARLEN = swiftkv_run_pe_3_U0_m_axi_gmem3_ARLEN;

assign m_axi_gmem3_ARLOCK = swiftkv_run_pe_3_U0_m_axi_gmem3_ARLOCK;

assign m_axi_gmem3_ARPROT = swiftkv_run_pe_3_U0_m_axi_gmem3_ARPROT;

assign m_axi_gmem3_ARQOS = swiftkv_run_pe_3_U0_m_axi_gmem3_ARQOS;

assign m_axi_gmem3_ARREGION = swiftkv_run_pe_3_U0_m_axi_gmem3_ARREGION;

assign m_axi_gmem3_ARSIZE = swiftkv_run_pe_3_U0_m_axi_gmem3_ARSIZE;

assign m_axi_gmem3_ARUSER = swiftkv_run_pe_3_U0_m_axi_gmem3_ARUSER;

assign m_axi_gmem3_ARVALID = swiftkv_run_pe_3_U0_m_axi_gmem3_ARVALID;

assign m_axi_gmem3_AWADDR = swiftkv_run_pe_3_U0_m_axi_gmem3_AWADDR;

assign m_axi_gmem3_AWBURST = swiftkv_run_pe_3_U0_m_axi_gmem3_AWBURST;

assign m_axi_gmem3_AWCACHE = swiftkv_run_pe_3_U0_m_axi_gmem3_AWCACHE;

assign m_axi_gmem3_AWID = swiftkv_run_pe_3_U0_m_axi_gmem3_AWID;

assign m_axi_gmem3_AWLEN = swiftkv_run_pe_3_U0_m_axi_gmem3_AWLEN;

assign m_axi_gmem3_AWLOCK = swiftkv_run_pe_3_U0_m_axi_gmem3_AWLOCK;

assign m_axi_gmem3_AWPROT = swiftkv_run_pe_3_U0_m_axi_gmem3_AWPROT;

assign m_axi_gmem3_AWQOS = swiftkv_run_pe_3_U0_m_axi_gmem3_AWQOS;

assign m_axi_gmem3_AWREGION = swiftkv_run_pe_3_U0_m_axi_gmem3_AWREGION;

assign m_axi_gmem3_AWSIZE = swiftkv_run_pe_3_U0_m_axi_gmem3_AWSIZE;

assign m_axi_gmem3_AWUSER = swiftkv_run_pe_3_U0_m_axi_gmem3_AWUSER;

assign m_axi_gmem3_AWVALID = swiftkv_run_pe_3_U0_m_axi_gmem3_AWVALID;

assign m_axi_gmem3_BREADY = swiftkv_run_pe_3_U0_m_axi_gmem3_BREADY;

assign m_axi_gmem3_RREADY = swiftkv_run_pe_3_U0_m_axi_gmem3_RREADY;

assign m_axi_gmem3_WDATA = swiftkv_run_pe_3_U0_m_axi_gmem3_WDATA;

assign m_axi_gmem3_WID = swiftkv_run_pe_3_U0_m_axi_gmem3_WID;

assign m_axi_gmem3_WLAST = swiftkv_run_pe_3_U0_m_axi_gmem3_WLAST;

assign m_axi_gmem3_WSTRB = swiftkv_run_pe_3_U0_m_axi_gmem3_WSTRB;

assign m_axi_gmem3_WUSER = swiftkv_run_pe_3_U0_m_axi_gmem3_WUSER;

assign m_axi_gmem3_WVALID = swiftkv_run_pe_3_U0_m_axi_gmem3_WVALID;

assign q_pe0_address0 = swiftkv_run_pe_0_U0_q_address0;

assign q_pe0_ce0 = swiftkv_run_pe_0_U0_q_ce0;

assign q_pe0_d0 = 512'd0;

assign q_pe0_we0 = 1'b0;

assign q_pe1_address0 = swiftkv_run_pe_1_U0_q_address0;

assign q_pe1_ce0 = swiftkv_run_pe_1_U0_q_ce0;

assign q_pe1_d0 = 512'd0;

assign q_pe1_we0 = 1'b0;

assign q_pe2_address0 = swiftkv_run_pe_2_U0_q_address0;

assign q_pe2_ce0 = swiftkv_run_pe_2_U0_q_ce0;

assign q_pe2_d0 = 512'd0;

assign q_pe2_we0 = 1'b0;

assign q_pe3_address0 = swiftkv_run_pe_3_U0_q_address0;

assign q_pe3_ce0 = swiftkv_run_pe_3_U0_q_ce0;

assign q_pe3_d0 = 512'd0;

assign q_pe3_we0 = 1'b0;

assign swiftkv_broadcast_pe_commands_U0_ap_continue = 1'b1;

assign swiftkv_broadcast_pe_commands_U0_ap_start = ((ap_sync_reg_swiftkv_broadcast_pe_commands_U0_ap_ready ^ 1'b1) & ap_start);

assign swiftkv_broadcast_rope_U0_ap_continue = 1'b1;

assign swiftkv_broadcast_rope_U0_ap_start = ((ap_sync_reg_swiftkv_broadcast_rope_U0_ap_ready ^ 1'b1) & ap_start);

assign swiftkv_gather_attention_streams_U0_ap_continue = ap_sync_continue;

assign swiftkv_gather_attention_streams_U0_ap_start = (ap_sync_reg_swiftkv_gather_attention_streams_U0_ap_start | ap_start);

assign swiftkv_run_pe_0_U0_ap_continue = ap_sync_continue;

assign swiftkv_run_pe_0_U0_ap_start = ((ap_sync_reg_swiftkv_run_pe_0_U0_ap_ready ^ 1'b1) & ap_start);

assign swiftkv_run_pe_1_U0_ap_continue = ap_sync_continue;

assign swiftkv_run_pe_1_U0_ap_start = ((ap_sync_reg_swiftkv_run_pe_1_U0_ap_ready ^ 1'b1) & ap_start);

assign swiftkv_run_pe_2_U0_ap_continue = ap_sync_continue;

assign swiftkv_run_pe_2_U0_ap_start = ((ap_sync_reg_swiftkv_run_pe_2_U0_ap_ready ^ 1'b1) & ap_start);

assign swiftkv_run_pe_3_U0_ap_continue = ap_sync_continue;

assign swiftkv_run_pe_3_U0_ap_start = ((ap_sync_reg_swiftkv_run_pe_3_U0_ap_ready ^ 1'b1) & ap_start);

assign v_pe0_address0 = swiftkv_run_pe_0_U0_v_address0;

assign v_pe0_ce0 = swiftkv_run_pe_0_U0_v_ce0;

assign v_pe0_d0 = 512'd0;

assign v_pe0_we0 = 1'b0;

assign v_pe1_address0 = swiftkv_run_pe_1_U0_v_address0;

assign v_pe1_ce0 = swiftkv_run_pe_1_U0_v_ce0;

assign v_pe1_d0 = 512'd0;

assign v_pe1_we0 = 1'b0;

assign v_pe2_address0 = swiftkv_run_pe_2_U0_v_address0;

assign v_pe2_ce0 = swiftkv_run_pe_2_U0_v_ce0;

assign v_pe2_d0 = 512'd0;

assign v_pe2_we0 = 1'b0;

assign v_pe3_address0 = swiftkv_run_pe_3_U0_v_address0;

assign v_pe3_ce0 = swiftkv_run_pe_3_U0_v_ce0;

assign v_pe3_d0 = 512'd0;

assign v_pe3_we0 = 1'b0;

endmodule //int4_decoder_token_controller_swiftkv_run_four_pes
