// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module int4_decoder_token_controller_int4_rms_normalize_quantize_pe_14_Pipeline_quantize_reverse_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        normalized_address0,
        normalized_ce0,
        normalized_q0,
        inverse_scale,
        quantized_word_out,
        quantized_word_out_ap_vld,
        grp_fu_144_p_din0,
        grp_fu_144_p_din1,
        grp_fu_144_p_dout0,
        grp_fu_144_p_ce,
        grp_fu_154_p_din0,
        grp_fu_154_p_din1,
        grp_fu_154_p_opcode,
        grp_fu_154_p_dout0,
        grp_fu_154_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] normalized_address0;
output   normalized_ce0;
input  [31:0] normalized_q0;
input  [31:0] inverse_scale;
output  [479:0] quantized_word_out;
output   quantized_word_out_ap_vld;
output  [31:0] grp_fu_144_p_din0;
output  [31:0] grp_fu_144_p_din1;
input  [31:0] grp_fu_144_p_dout0;
output   grp_fu_144_p_ce;
output  [31:0] grp_fu_154_p_din0;
output  [31:0] grp_fu_154_p_din1;
output  [4:0] grp_fu_154_p_opcode;
input  [0:0] grp_fu_154_p_dout0;
output   grp_fu_154_p_ce;

reg ap_idle;
reg normalized_ce0;
reg quantized_word_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_166_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_reg_508;
reg   [0:0] tmp_reg_508_pp0_iter1_reg;
reg   [0:0] tmp_reg_508_pp0_iter2_reg;
reg   [0:0] tmp_reg_508_pp0_iter3_reg;
reg   [0:0] tmp_reg_508_pp0_iter4_reg;
reg   [0:0] tmp_reg_508_pp0_iter5_reg;
reg   [0:0] tmp_reg_508_pp0_iter6_reg;
reg   [0:0] tmp_reg_508_pp0_iter7_reg;
reg   [0:0] tmp_reg_508_pp0_iter8_reg;
reg   [0:0] tmp_reg_508_pp0_iter9_reg;
reg   [0:0] tmp_reg_508_pp0_iter10_reg;
reg   [0:0] tmp_reg_508_pp0_iter11_reg;
reg   [0:0] tmp_reg_508_pp0_iter12_reg;
reg   [0:0] tmp_reg_508_pp0_iter13_reg;
reg   [0:0] tmp_reg_508_pp0_iter14_reg;
reg   [0:0] tmp_reg_508_pp0_iter15_reg;
reg   [0:0] tmp_reg_508_pp0_iter16_reg;
reg   [0:0] tmp_reg_508_pp0_iter17_reg;
reg   [0:0] tmp_reg_508_pp0_iter18_reg;
reg   [31:0] normalized_load_reg_517;
reg   [31:0] scaled_reg_522;
reg   [31:0] scaled_reg_522_pp0_iter6_reg;
reg   [31:0] scaled_reg_522_pp0_iter7_reg;
wire   [31:0] select_ln179_fu_231_p3;
reg   [31:0] select_ln179_reg_529;
wire   [31:0] grp_fu_130_p2;
reg   [31:0] rounded_reg_534;
reg   [31:0] rounded_reg_534_pp0_iter15_reg;
wire   [31:0] rounded_8_fu_280_p3;
reg   [31:0] rounded_8_reg_541;
reg   [31:0] rounded_8_reg_541_pp0_iter17_reg;
reg   [0:0] xs_sign_reg_547;
reg   [0:0] xs_sign_reg_547_pp0_iter19_reg;
reg   [7:0] xs_exp_reg_552;
wire   [22:0] trunc_ln342_fu_354_p1;
reg   [22:0] trunc_ln342_reg_558;
wire   [14:0] val_fu_445_p3;
reg   [14:0] val_reg_563;
wire   [63:0] zext_ln174_fu_174_p1;
wire    ap_block_pp0_stage0;
reg   [479:0] quantized_word_fu_96;
wire   [479:0] quantized_word_7_fu_471_p3;
wire    ap_loop_init;
reg   [5:0] index_fu_100;
wire   [5:0] add_ln175_fu_179_p2;
reg   [5:0] ap_sig_allocacmp_index_8;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] bitcast_ln179_fu_190_p1;
wire   [7:0] tmp_64_fu_193_p4;
wire   [22:0] trunc_ln179_fu_203_p1;
wire   [0:0] icmp_ln179_2_fu_213_p2;
wire   [0:0] icmp_ln179_fu_207_p2;
wire   [0:0] or_ln179_fu_219_p2;
wire   [0:0] and_ln179_fu_225_p2;
wire   [31:0] bitcast_ln180_fu_239_p1;
wire   [7:0] tmp_66_fu_242_p4;
wire   [22:0] trunc_ln180_fu_252_p1;
wire   [0:0] icmp_ln180_4_fu_262_p2;
wire   [0:0] icmp_ln180_fu_256_p2;
wire   [0:0] or_ln180_fu_268_p2;
wire   [0:0] grp_fu_143_p2;
wire   [0:0] and_ln180_fu_274_p2;
wire   [31:0] bitcast_ln183_fu_287_p1;
wire   [7:0] tmp_68_fu_290_p4;
wire   [22:0] trunc_ln183_fu_300_p1;
wire   [0:0] icmp_ln183_2_fu_310_p2;
wire   [0:0] icmp_ln183_fu_304_p2;
wire   [0:0] or_ln183_fu_316_p2;
wire   [0:0] grp_fu_148_p2;
wire   [0:0] and_ln183_fu_322_p2;
wire   [31:0] data_fu_328_p3;
wire   [24:0] mantissa_fu_358_p4;
wire   [8:0] zext_ln317_fu_371_p1;
wire   [8:0] add_ln317_fu_374_p2;
wire   [7:0] sub_ln18_fu_388_p2;
wire   [0:0] tmp_257_fu_380_p3;
wire  signed [8:0] sext_ln18_fu_393_p1;
wire   [8:0] select_ln18_fu_397_p3;
wire  signed [31:0] sext_ln18_8_fu_405_p1;
wire   [78:0] zext_ln15_fu_367_p1;
wire   [78:0] zext_ln18_fu_409_p1;
wire   [78:0] lshr_ln18_fu_413_p2;
wire   [78:0] shl_ln18_fu_419_p2;
wire   [14:0] tmp_258_fu_425_p4;
wire   [14:0] tmp_259_fu_435_p4;
wire   [14:0] result_8_fu_456_p2;
wire   [464:0] trunc_ln189_fu_467_p1;
wire   [14:0] quantized_fu_461_p3;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 quantized_word_fu_96 = 480'd0;
#0 index_fu_100 = 6'd0;
#0 ap_done_reg = 1'b0;
end

int4_decoder_token_controller_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U1369(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(scaled_reg_522_pp0_iter7_reg),
    .din1(select_ln179_reg_529),
    .ce(1'b1),
    .dout(grp_fu_130_p2)
);

int4_decoder_token_controller_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U1372(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rounded_reg_534),
    .din1(32'd1182792704),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_143_p2)
);

int4_decoder_token_controller_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U1373(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rounded_8_reg_541),
    .din1(32'd3330276352),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_148_p2)
);

int4_decoder_token_controller_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_fu_166_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            index_fu_100 <= add_ln175_fu_179_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            index_fu_100 <= 6'd31;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            quantized_word_fu_96 <= 480'd0;
        end else if ((ap_enable_reg_pp0_iter20 == 1'b1)) begin
            quantized_word_fu_96 <= quantized_word_7_fu_471_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        rounded_8_reg_541 <= rounded_8_fu_280_p3;
        rounded_8_reg_541_pp0_iter17_reg <= rounded_8_reg_541;
        rounded_reg_534 <= grp_fu_130_p2;
        rounded_reg_534_pp0_iter15_reg <= rounded_reg_534;
        scaled_reg_522 <= grp_fu_144_p_dout0;
        scaled_reg_522_pp0_iter6_reg <= scaled_reg_522;
        scaled_reg_522_pp0_iter7_reg <= scaled_reg_522_pp0_iter6_reg;
        select_ln179_reg_529[31] <= select_ln179_fu_231_p3[31];
        tmp_reg_508_pp0_iter10_reg <= tmp_reg_508_pp0_iter9_reg;
        tmp_reg_508_pp0_iter11_reg <= tmp_reg_508_pp0_iter10_reg;
        tmp_reg_508_pp0_iter12_reg <= tmp_reg_508_pp0_iter11_reg;
        tmp_reg_508_pp0_iter13_reg <= tmp_reg_508_pp0_iter12_reg;
        tmp_reg_508_pp0_iter14_reg <= tmp_reg_508_pp0_iter13_reg;
        tmp_reg_508_pp0_iter15_reg <= tmp_reg_508_pp0_iter14_reg;
        tmp_reg_508_pp0_iter16_reg <= tmp_reg_508_pp0_iter15_reg;
        tmp_reg_508_pp0_iter17_reg <= tmp_reg_508_pp0_iter16_reg;
        tmp_reg_508_pp0_iter18_reg <= tmp_reg_508_pp0_iter17_reg;
        tmp_reg_508_pp0_iter2_reg <= tmp_reg_508_pp0_iter1_reg;
        tmp_reg_508_pp0_iter3_reg <= tmp_reg_508_pp0_iter2_reg;
        tmp_reg_508_pp0_iter4_reg <= tmp_reg_508_pp0_iter3_reg;
        tmp_reg_508_pp0_iter5_reg <= tmp_reg_508_pp0_iter4_reg;
        tmp_reg_508_pp0_iter6_reg <= tmp_reg_508_pp0_iter5_reg;
        tmp_reg_508_pp0_iter7_reg <= tmp_reg_508_pp0_iter6_reg;
        tmp_reg_508_pp0_iter8_reg <= tmp_reg_508_pp0_iter7_reg;
        tmp_reg_508_pp0_iter9_reg <= tmp_reg_508_pp0_iter8_reg;
        trunc_ln342_reg_558 <= trunc_ln342_fu_354_p1;
        val_reg_563 <= val_fu_445_p3;
        xs_exp_reg_552 <= {{data_fu_328_p3[30:23]}};
        xs_sign_reg_547 <= data_fu_328_p3[32'd31];
        xs_sign_reg_547_pp0_iter19_reg <= xs_sign_reg_547;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        normalized_load_reg_517 <= normalized_q0;
        tmp_reg_508 <= ap_sig_allocacmp_index_8[32'd5];
        tmp_reg_508_pp0_iter1_reg <= tmp_reg_508;
    end
end

always @ (*) begin
    if (((tmp_fu_166_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter19_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_index_8 = 6'd31;
    end else begin
        ap_sig_allocacmp_index_8 = index_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        normalized_ce0 = 1'b1;
    end else begin
        normalized_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_508_pp0_iter18_reg == 1'd1))) begin
        quantized_word_out_ap_vld = 1'b1;
    end else begin
        quantized_word_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln175_fu_179_p2 = ($signed(ap_sig_allocacmp_index_8) + $signed(6'd63));

assign add_ln317_fu_374_p2 = ($signed(zext_ln317_fu_371_p1) + $signed(9'd385));

assign and_ln179_fu_225_p2 = (or_ln179_fu_219_p2 & grp_fu_154_p_dout0);

assign and_ln180_fu_274_p2 = (or_ln180_fu_268_p2 & grp_fu_143_p2);

assign and_ln183_fu_322_p2 = (or_ln183_fu_316_p2 & grp_fu_148_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln179_fu_190_p1 = scaled_reg_522_pp0_iter6_reg;

assign bitcast_ln180_fu_239_p1 = rounded_reg_534_pp0_iter15_reg;

assign bitcast_ln183_fu_287_p1 = rounded_8_reg_541_pp0_iter17_reg;

assign data_fu_328_p3 = ((and_ln183_fu_322_p2[0:0] == 1'b1) ? 32'd3330276352 : bitcast_ln183_fu_287_p1);

assign grp_fu_144_p_ce = 1'b1;

assign grp_fu_144_p_din0 = normalized_load_reg_517;

assign grp_fu_144_p_din1 = inverse_scale;

assign grp_fu_154_p_ce = 1'b1;

assign grp_fu_154_p_din0 = scaled_reg_522;

assign grp_fu_154_p_din1 = 32'd0;

assign grp_fu_154_p_opcode = 5'd3;

assign icmp_ln179_2_fu_213_p2 = ((trunc_ln179_fu_203_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_fu_207_p2 = ((tmp_64_fu_193_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln180_4_fu_262_p2 = ((trunc_ln180_fu_252_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_256_p2 = ((tmp_66_fu_242_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln183_2_fu_310_p2 = ((trunc_ln183_fu_300_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln183_fu_304_p2 = ((tmp_68_fu_290_p4 != 8'd255) ? 1'b1 : 1'b0);

assign lshr_ln18_fu_413_p2 = zext_ln15_fu_367_p1 >> zext_ln18_fu_409_p1;

assign mantissa_fu_358_p4 = {{{{1'd1}, {trunc_ln342_reg_558}}}, {1'd0}};

assign normalized_address0 = zext_ln174_fu_174_p1;

assign or_ln179_fu_219_p2 = (icmp_ln179_fu_207_p2 | icmp_ln179_2_fu_213_p2);

assign or_ln180_fu_268_p2 = (icmp_ln180_fu_256_p2 | icmp_ln180_4_fu_262_p2);

assign or_ln183_fu_316_p2 = (icmp_ln183_fu_304_p2 | icmp_ln183_2_fu_310_p2);

assign quantized_fu_461_p3 = ((xs_sign_reg_547_pp0_iter19_reg[0:0] == 1'b1) ? result_8_fu_456_p2 : val_reg_563);

assign quantized_word_7_fu_471_p3 = {{trunc_ln189_fu_467_p1}, {quantized_fu_461_p3}};

assign quantized_word_out = quantized_word_fu_96;

assign result_8_fu_456_p2 = (15'd0 - val_reg_563);

assign rounded_8_fu_280_p3 = ((and_ln180_fu_274_p2[0:0] == 1'b1) ? 32'd1182792704 : rounded_reg_534_pp0_iter15_reg);

assign select_ln179_fu_231_p3 = ((and_ln179_fu_225_p2[0:0] == 1'b1) ? 32'd1056964608 : 32'd3204448256);

assign select_ln18_fu_397_p3 = ((tmp_257_fu_380_p3[0:0] == 1'b1) ? sext_ln18_fu_393_p1 : add_ln317_fu_374_p2);

assign sext_ln18_8_fu_405_p1 = $signed(select_ln18_fu_397_p3);

assign sext_ln18_fu_393_p1 = $signed(sub_ln18_fu_388_p2);

assign shl_ln18_fu_419_p2 = zext_ln15_fu_367_p1 << zext_ln18_fu_409_p1;

assign sub_ln18_fu_388_p2 = (8'd127 - xs_exp_reg_552);

assign tmp_257_fu_380_p3 = add_ln317_fu_374_p2[32'd8];

assign tmp_258_fu_425_p4 = {{lshr_ln18_fu_413_p2[38:24]}};

assign tmp_259_fu_435_p4 = {{shl_ln18_fu_419_p2[38:24]}};

assign tmp_64_fu_193_p4 = {{bitcast_ln179_fu_190_p1[30:23]}};

assign tmp_66_fu_242_p4 = {{bitcast_ln180_fu_239_p1[30:23]}};

assign tmp_68_fu_290_p4 = {{bitcast_ln183_fu_287_p1[30:23]}};

assign tmp_fu_166_p3 = ap_sig_allocacmp_index_8[32'd5];

assign trunc_ln179_fu_203_p1 = bitcast_ln179_fu_190_p1[22:0];

assign trunc_ln180_fu_252_p1 = bitcast_ln180_fu_239_p1[22:0];

assign trunc_ln183_fu_300_p1 = bitcast_ln183_fu_287_p1[22:0];

assign trunc_ln189_fu_467_p1 = quantized_word_fu_96[464:0];

assign trunc_ln342_fu_354_p1 = data_fu_328_p3[22:0];

assign val_fu_445_p3 = ((tmp_257_fu_380_p3[0:0] == 1'b1) ? tmp_258_fu_425_p4 : tmp_259_fu_435_p4);

assign zext_ln15_fu_367_p1 = mantissa_fu_358_p4;

assign zext_ln174_fu_174_p1 = ap_sig_allocacmp_index_8;

assign zext_ln18_fu_409_p1 = $unsigned(sext_ln18_8_fu_405_p1);

assign zext_ln317_fu_371_p1 = xs_exp_reg_552;

always @ (posedge ap_clk) begin
    select_ln179_reg_529[30:0] <= 31'b0111111000000000000000000000000;
end

endmodule //int4_decoder_token_controller_int4_rms_normalize_quantize_pe_14_Pipeline_quantize_reverse_loop
