-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity int4_decoder_token_controller_int4_swiglu_quantize_pe2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    gate_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    gate_ce0 : OUT STD_LOGIC;
    gate_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    up_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    up_ce0 : OUT STD_LOGIC;
    up_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
    quantized_pe2_din : OUT STD_LOGIC_VECTOR (479 downto 0);
    quantized_pe2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    quantized_pe2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    quantized_pe2_full_n : IN STD_LOGIC;
    quantized_pe2_write : OUT STD_LOGIC;
    scale_pe2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    scale_pe2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_pe2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    scale_pe2_full_n : IN STD_LOGIC;
    scale_pe2_write : OUT STD_LOGIC );
end;


architecture behav of int4_decoder_token_controller_int4_swiglu_quantize_pe2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (19 downto 0) := "00000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (19 downto 0) := "00000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (19 downto 0) := "00000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (19 downto 0) := "00000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (19 downto 0) := "00000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (19 downto 0) := "00000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (19 downto 0) := "00001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (19 downto 0) := "00010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (19 downto 0) := "00100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (19 downto 0) := "01000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (19 downto 0) := "10000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_38800200 : STD_LOGIC_VECTOR (31 downto 0) := "00111000100000000000001000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_467FFC00 : STD_LOGIC_VECTOR (31 downto 0) := "01000110011111111111110000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv7_54 : STD_LOGIC_VECTOR (6 downto 0) := "1010100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal quantized_pe2_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal scale_pe2_blk_n : STD_LOGIC;
    signal tmp_s_fu_159_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_reg_260 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal max_abs_fu_176_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal max_abs_reg_265 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln767_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln767_reg_272 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln767_2_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln767_2_reg_277 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln767_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln767_reg_282 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_124_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul33_i_reg_288 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal grp_fu_129_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal div37_i_reg_293 : STD_LOGIC_VECTOR (31 downto 0);
    signal inverse_scale_fu_217_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal inverse_scale_reg_298 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal select_ln772_fu_227_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln772_reg_303 : STD_LOGIC_VECTOR (31 downto 0);
    signal swiglu_group_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal swiglu_group_ce0 : STD_LOGIC;
    signal swiglu_group_we0 : STD_LOGIC;
    signal swiglu_group_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_start : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_done : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_idle : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_ready : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_ce0 : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_we0 : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_gate_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_gate_ce0 : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_up_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_up_ce0 : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_max_abs_bits_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_max_abs_bits_2_out_ap_vld : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_ce : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_ce : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_ce : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_start : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_done : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_idle : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_ready : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_swiglu_group_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_swiglu_group_ce0 : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_quantized_word_out : STD_LOGIC_VECTOR (479 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_quantized_word_out_ap_vld : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_ce : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_ce : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_opcode : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_ce : STD_LOGIC;
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln720_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal group_fu_76 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln720_fu_153_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state20 : BOOLEAN;
    signal grp_fu_124_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_124_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_fu_129_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_129_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_134_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_134_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_30_fu_181_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln767_fu_191_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal or_ln767_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln772_fu_224_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_124_ce : STD_LOGIC;
    signal grp_fu_129_ce : STD_LOGIC;
    signal grp_fu_134_ce : STD_LOGIC;
    signal grp_fu_134_opcode : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_308_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_308_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_308_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_308_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (19 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component int4_decoder_token_controller_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        swiglu_group_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        swiglu_group_ce0 : OUT STD_LOGIC;
        swiglu_group_we0 : OUT STD_LOGIC;
        swiglu_group_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        tmp_39 : IN STD_LOGIC_VECTOR (7 downto 0);
        gate_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        gate_ce0 : OUT STD_LOGIC;
        gate_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
        up_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        up_ce0 : OUT STD_LOGIC;
        up_q0 : IN STD_LOGIC_VECTOR (511 downto 0);
        max_abs_bits_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        max_abs_bits_2_out_ap_vld : OUT STD_LOGIC;
        grp_fu_308_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_308_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_308_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_308_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_308_p_ce : OUT STD_LOGIC;
        grp_fu_124_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_124_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_124_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_124_p_ce : OUT STD_LOGIC;
        grp_fu_129_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_129_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_129_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_129_p_ce : OUT STD_LOGIC );
    end component;


    component int4_decoder_token_controller_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        swiglu_group_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        swiglu_group_ce0 : OUT STD_LOGIC;
        swiglu_group_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        inverse_scale : IN STD_LOGIC_VECTOR (31 downto 0);
        quantized_word_out : OUT STD_LOGIC_VECTOR (479 downto 0);
        quantized_word_out_ap_vld : OUT STD_LOGIC;
        grp_fu_308_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_308_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_308_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
        grp_fu_308_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_308_p_ce : OUT STD_LOGIC;
        grp_fu_124_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_124_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_124_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_124_p_ce : OUT STD_LOGIC;
        grp_fu_134_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_134_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_134_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
        grp_fu_134_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_134_p_ce : OUT STD_LOGIC );
    end component;


    component int4_decoder_token_controller_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component int4_decoder_token_controller_fdiv_32ns_32ns_32_12_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component int4_decoder_token_controller_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component int4_decoder_token_controller_fadd_32ns_32ns_32_7_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component int4_decoder_token_controller_int4_swiglu_quantize_pe0_swiglu_group_RAM_1P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    swiglu_group_U : component int4_decoder_token_controller_int4_swiglu_quantize_pe0_swiglu_group_RAM_1P_BRAM_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => swiglu_group_address0,
        ce0 => swiglu_group_ce0,
        we0 => swiglu_group_we0,
        d0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_d0,
        q0 => swiglu_group_q0);

    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106 : component int4_decoder_token_controller_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_start,
        ap_done => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_done,
        ap_idle => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_idle,
        ap_ready => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_ready,
        swiglu_group_address0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_address0,
        swiglu_group_ce0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_ce0,
        swiglu_group_we0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_we0,
        swiglu_group_d0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_d0,
        tmp_39 => tmp_s_reg_260,
        gate_address0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_gate_address0,
        gate_ce0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_gate_ce0,
        gate_q0 => gate_q0,
        up_address0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_up_address0,
        up_ce0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_up_ce0,
        up_q0 => up_q0,
        max_abs_bits_2_out => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_max_abs_bits_2_out,
        max_abs_bits_2_out_ap_vld => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_max_abs_bits_2_out_ap_vld,
        grp_fu_308_p_din0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_din0,
        grp_fu_308_p_din1 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_din1,
        grp_fu_308_p_opcode => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_opcode,
        grp_fu_308_p_dout0 => grp_fu_308_p2,
        grp_fu_308_p_ce => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_ce,
        grp_fu_124_p_din0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_din0,
        grp_fu_124_p_din1 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_din1,
        grp_fu_124_p_dout0 => grp_fu_124_p2,
        grp_fu_124_p_ce => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_ce,
        grp_fu_129_p_din0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_din0,
        grp_fu_129_p_din1 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_din1,
        grp_fu_129_p_dout0 => grp_fu_129_p2,
        grp_fu_129_p_ce => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_ce);

    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117 : component int4_decoder_token_controller_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_start,
        ap_done => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_done,
        ap_idle => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_idle,
        ap_ready => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_ready,
        swiglu_group_address0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_swiglu_group_address0,
        swiglu_group_ce0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_swiglu_group_ce0,
        swiglu_group_q0 => swiglu_group_q0,
        inverse_scale => inverse_scale_reg_298,
        quantized_word_out => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_quantized_word_out,
        quantized_word_out_ap_vld => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_quantized_word_out_ap_vld,
        grp_fu_308_p_din0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_din0,
        grp_fu_308_p_din1 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_din1,
        grp_fu_308_p_opcode => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_opcode,
        grp_fu_308_p_dout0 => grp_fu_308_p2,
        grp_fu_308_p_ce => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_ce,
        grp_fu_124_p_din0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_din0,
        grp_fu_124_p_din1 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_din1,
        grp_fu_124_p_dout0 => grp_fu_124_p2,
        grp_fu_124_p_ce => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_ce,
        grp_fu_134_p_din0 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_din0,
        grp_fu_134_p_din1 => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_din1,
        grp_fu_134_p_opcode => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_opcode,
        grp_fu_134_p_dout0 => grp_fu_134_p2,
        grp_fu_134_p_ce => grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_ce);

    fmul_32ns_32ns_32_4_max_dsp_1_U1026 : component int4_decoder_token_controller_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_124_p0,
        din1 => grp_fu_124_p1,
        ce => grp_fu_124_ce,
        dout => grp_fu_124_p2);

    fdiv_32ns_32ns_32_12_no_dsp_1_U1027 : component int4_decoder_token_controller_fdiv_32ns_32ns_32_12_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_129_p0,
        din1 => grp_fu_129_p1,
        ce => grp_fu_129_ce,
        dout => grp_fu_129_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U1028 : component int4_decoder_token_controller_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_134_p0,
        din1 => grp_fu_134_p1,
        ce => grp_fu_134_ce,
        opcode => grp_fu_134_opcode,
        dout => grp_fu_134_p2);

    fadd_32ns_32ns_32_7_full_dsp_1_U1029 : component int4_decoder_token_controller_fadd_32ns_32ns_32_7_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_308_p0,
        din1 => grp_fu_308_p1,
        ce => grp_fu_308_ce,
        dout => grp_fu_308_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln720_fu_147_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
                    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_ready = ap_const_logic_1)) then 
                    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln720_fu_147_p2 = ap_const_lv1_0))) then 
                    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_ready = ap_const_logic_1)) then 
                    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    group_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                group_fu_76 <= ap_const_lv7_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln720_fu_147_p2 = ap_const_lv1_0))) then 
                group_fu_76 <= add_ln720_fu_153_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                and_ln767_reg_282 <= and_ln767_fu_211_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                div37_i_reg_293 <= grp_fu_129_p2;
                mul33_i_reg_288 <= grp_fu_124_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln767_2_reg_277 <= icmp_ln767_2_fu_201_p2;
                icmp_ln767_reg_272 <= icmp_ln767_fu_195_p2;
                max_abs_reg_265 <= max_abs_fu_176_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                inverse_scale_reg_298 <= inverse_scale_fu_217_p3;
                select_ln772_reg_303 <= select_ln772_fu_227_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                    tmp_s_reg_260(7 downto 1) <= tmp_s_fu_159_p3(7 downto 1);
            end if;
        end if;
    end process;
    tmp_s_reg_260(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state20, ap_CS_fsm_state2, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_done, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_done, icmp_ln720_fu_147_p2, ap_CS_fsm_state3, ap_CS_fsm_state19, ap_block_state1, ap_block_state20)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln720_fu_147_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state19) and (grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state20 => 
                if (((ap_const_boolean_0 = ap_block_state20) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln720_fu_153_p2 <= std_logic_vector(unsigned(group_fu_76) + unsigned(ap_const_lv7_1));
    and_ln767_fu_211_p2 <= (or_ln767_fu_207_p2 and grp_fu_134_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;

    ap_ST_fsm_state19_blk_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_done)
    begin
        if ((grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state19_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state19_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state20_blk_assign_proc : process(ap_block_state20)
    begin
        if ((ap_const_boolean_1 = ap_block_state20)) then 
            ap_ST_fsm_state20_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state20_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_done)
    begin
        if ((grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state20_assign_proc : process(quantized_pe2_full_n, scale_pe2_full_n)
    begin
                ap_block_state20 <= ((scale_pe2_full_n = ap_const_logic_0) or (quantized_pe2_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln720_fu_147_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln720_fu_147_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln720_fu_147_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln720_fu_147_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln772_fu_224_p1 <= mul33_i_reg_288;
    gate_address0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_gate_address0;
    gate_ce0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_gate_ce0;

    grp_fu_124_ce_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_ce, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_ce, ap_CS_fsm_state3, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_124_ce <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_124_ce <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_ce;
        else 
            grp_fu_124_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_124_p0_assign_proc : process(max_abs_reg_265, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_din0, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_din0, ap_CS_fsm_state3, ap_CS_fsm_state19, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_124_p0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_124_p0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_124_p0 <= max_abs_reg_265;
        else 
            grp_fu_124_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_124_p1_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_din1, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_din1, ap_CS_fsm_state3, ap_CS_fsm_state19, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_124_p1 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_124_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_124_p1 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_124_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            grp_fu_124_p1 <= ap_const_lv32_38800200;
        else 
            grp_fu_124_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_129_ce_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_ce, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_129_ce <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_ce;
        else 
            grp_fu_129_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_129_p0_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_din0, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_129_p0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_129_p0 <= ap_const_lv32_467FFC00;
        else 
            grp_fu_129_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_129_p1_assign_proc : process(max_abs_reg_265, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_din1, ap_CS_fsm_state3, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_129_p1 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_129_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_129_p1 <= max_abs_reg_265;
        else 
            grp_fu_129_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_134_ce_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_ce, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_134_ce <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_ce;
        else 
            grp_fu_134_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_134_opcode_assign_proc : process(ap_CS_fsm_state4, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_opcode, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_134_opcode <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_opcode;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_134_opcode <= ap_const_lv5_1;
        else 
            grp_fu_134_opcode <= "XXXXX";
        end if; 
    end process;


    grp_fu_134_p0_assign_proc : process(max_abs_fu_176_p1, ap_CS_fsm_state4, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_din0, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_134_p0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_134_p0 <= max_abs_fu_176_p1;
        else 
            grp_fu_134_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_134_p1_assign_proc : process(ap_CS_fsm_state4, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_din1, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_134_p1 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_134_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_134_p1 <= ap_const_lv32_0;
        else 
            grp_fu_134_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_308_ce_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_ce, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_ce, ap_CS_fsm_state3, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_308_ce <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_ce;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_308_ce <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_ce;
        else 
            grp_fu_308_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_308_p0_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_din0, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_din0, ap_CS_fsm_state3, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_308_p0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_308_p0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_din0;
        else 
            grp_fu_308_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_308_p1_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_din1, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_din1, ap_CS_fsm_state3, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_308_p1 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_grp_fu_308_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_308_p1 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_grp_fu_308_p_din1;
        else 
            grp_fu_308_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_start <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_ap_start_reg;
    grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_start <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_ap_start_reg;
    icmp_ln720_fu_147_p2 <= "1" when (group_fu_76 = ap_const_lv7_54) else "0";
    icmp_ln767_2_fu_201_p2 <= "1" when (trunc_ln767_fu_191_p1 = ap_const_lv23_0) else "0";
    icmp_ln767_fu_195_p2 <= "0" when (tmp_30_fu_181_p4 = ap_const_lv8_FF) else "1";
    inverse_scale_fu_217_p3 <= 
        ap_const_lv32_0 when (and_ln767_reg_282(0) = '1') else 
        div37_i_reg_293;
    max_abs_fu_176_p1 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_max_abs_bits_2_out;
    or_ln767_fu_207_p2 <= (icmp_ln767_reg_272 or icmp_ln767_2_reg_277);

    quantized_pe2_blk_n_assign_proc : process(quantized_pe2_full_n, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            quantized_pe2_blk_n <= quantized_pe2_full_n;
        else 
            quantized_pe2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    quantized_pe2_din <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_quantized_word_out;

    quantized_pe2_write_assign_proc : process(ap_CS_fsm_state20, ap_block_state20)
    begin
        if (((ap_const_boolean_0 = ap_block_state20) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            quantized_pe2_write <= ap_const_logic_1;
        else 
            quantized_pe2_write <= ap_const_logic_0;
        end if; 
    end process;


    scale_pe2_blk_n_assign_proc : process(scale_pe2_full_n, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            scale_pe2_blk_n <= scale_pe2_full_n;
        else 
            scale_pe2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    scale_pe2_din <= select_ln772_reg_303;

    scale_pe2_write_assign_proc : process(ap_CS_fsm_state20, ap_block_state20)
    begin
        if (((ap_const_boolean_0 = ap_block_state20) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            scale_pe2_write <= ap_const_logic_1;
        else 
            scale_pe2_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln772_fu_227_p3 <= 
        ap_const_lv32_0 when (and_ln767_reg_282(0) = '1') else 
        bitcast_ln772_fu_224_p1;

    swiglu_group_address0_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_address0, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_swiglu_group_address0, ap_CS_fsm_state3, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            swiglu_group_address0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_swiglu_group_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            swiglu_group_address0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_address0;
        else 
            swiglu_group_address0 <= "XXXXX";
        end if; 
    end process;


    swiglu_group_ce0_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_ce0, grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_swiglu_group_ce0, ap_CS_fsm_state3, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            swiglu_group_ce0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_quantize_reverse_loop_fu_117_swiglu_group_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            swiglu_group_ce0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_ce0;
        else 
            swiglu_group_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    swiglu_group_we0_assign_proc : process(grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            swiglu_group_we0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_swiglu_group_we0;
        else 
            swiglu_group_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_30_fu_181_p4 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_max_abs_bits_2_out(30 downto 23);
    tmp_s_fu_159_p3 <= (group_fu_76 & ap_const_lv1_0);
    trunc_ln767_fu_191_p1 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_max_abs_bits_2_out(23 - 1 downto 0);
    up_address0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_up_address0;
    up_ce0 <= grp_int4_swiglu_quantize_pe2_Pipeline_swiglu_word_loop_swiglu_lane_loop_fu_106_up_ce0;
end behav;
