-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    engine1_control_stream_dout : IN STD_LOGIC_VECTOR (58 downto 0);
    engine1_control_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    engine1_control_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    engine1_control_stream_empty_n : IN STD_LOGIC;
    engine1_control_stream_read : OUT STD_LOGIC;
    value0_engine1_stream_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    value0_engine1_stream_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    value0_engine1_stream_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    value0_engine1_stream_empty_n : IN STD_LOGIC;
    value0_engine1_stream_read : OUT STD_LOGIC;
    value1_engine1_stream_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    value1_engine1_stream_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    value1_engine1_stream_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    value1_engine1_stream_empty_n : IN STD_LOGIC;
    value1_engine1_stream_read : OUT STD_LOGIC;
    engine1_phase_stream_din : OUT STD_LOGIC_VECTOR (56 downto 0);
    engine1_phase_stream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    engine1_phase_stream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    engine1_phase_stream_full_n : IN STD_LOGIC;
    engine1_phase_stream_write : OUT STD_LOGIC;
    update_phase_count : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of int4_decoder_token_controller_swiftkv_prepare_update_engine_phases_Pipeline_prepare_update_engine_phase_loop_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv96_0 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln1182_reg_514 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1188_reg_518 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op39_read_state2 : BOOLEAN;
    signal ap_predicate_op42_read_state2 : BOOLEAN;
    signal icmp_ln1212_reg_522 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op54_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1182_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal engine1_phase_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal engine1_control_stream_blk_n : STD_LOGIC;
    signal value0_engine1_stream_blk_n : STD_LOGIC;
    signal value1_engine1_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln1182_reg_514_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1188_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1188_reg_518_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1212_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1212_reg_522_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_reg_526 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_reg_526_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1235_fu_281_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1235_reg_531 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1235_reg_531_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_value_word_1_phi_fu_194_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter0_value_word_1_reg_191 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter1_value_word_1_reg_191 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter2_value_word_1_reg_191 : STD_LOGIC_VECTOR (127 downto 0);
    signal zext_ln1182_fu_383_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_mux_value_word_2_phi_fu_203_p4 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter0_value_word_2_reg_200 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter1_value_word_2_reg_200 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_phi_reg_pp0_iter2_value_word_2_reg_200 : STD_LOGIC_VECTOR (127 downto 0);
    signal value_word_04_fu_128 : STD_LOGIC_VECTOR (95 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal update_phase_06_fu_132 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal update_phase_10_fu_239_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_update_phase : STD_LOGIC_VECTOR (15 downto 0);
    signal rescale_history_fu_136 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal empty_fu_140 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal value_shift_fu_144 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal value_shift_8_fu_148 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal value_shift_9_fu_152 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal value_shift_10_fu_156 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal phase_fu_245_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_173_fu_271_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_s_fu_420_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_420_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal packed_values_fu_406_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_173 : BOOLEAN;
    signal ap_condition_409 : BOOLEAN;
    signal tmp_s_fu_420_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_420_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_420_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_420_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component int4_decoder_token_controller_sparsemux_9_2_5_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        din3 : IN STD_LOGIC_VECTOR (4 downto 0);
        def : IN STD_LOGIC_VECTOR (4 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component int4_decoder_token_controller_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_5_1_1_U533 : component int4_decoder_token_controller_sparsemux_9_2_5_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 5,
        CASE1 => "01",
        din1_WIDTH => 5,
        CASE2 => "10",
        din2_WIDTH => 5,
        CASE3 => "11",
        din3_WIDTH => 5,
        def_WIDTH => 5,
        sel_WIDTH => 2,
        dout_WIDTH => 5)
    port map (
        din0 => value_shift_fu_144,
        din1 => value_shift_8_fu_148,
        din2 => value_shift_9_fu_152,
        din3 => value_shift_10_fu_156,
        def => tmp_s_fu_420_p9,
        sel => trunc_ln_reg_526_pp0_iter1_reg,
        dout => tmp_s_fu_420_p11);

    flow_control_loop_pipe_sequential_init_U : component int4_decoder_token_controller_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_value_word_1_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_173)) then
                if (((icmp_ln1188_reg_518 = ap_const_lv1_1) and (icmp_ln1182_reg_514 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter2_value_word_1_reg_191 <= value0_engine1_stream_dout;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_value_word_1_reg_191 <= ap_phi_reg_pp0_iter1_value_word_1_reg_191;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_value_word_2_reg_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_173)) then
                if (((icmp_ln1212_reg_522 = ap_const_lv1_1) and (icmp_ln1182_reg_514 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter2_value_word_2_reg_200 <= value1_engine1_stream_dout;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_value_word_2_reg_200 <= ap_phi_reg_pp0_iter1_value_word_2_reg_200;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_140 <= ap_const_lv18_20000;
                elsif ((ap_const_boolean_1 = ap_condition_409)) then 
                    empty_fu_140 <= engine1_control_stream_dout(57 downto 40);
                end if;
            end if; 
        end if;
    end process;

    rescale_history_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    rescale_history_fu_136 <= ap_const_lv1_0;
                elsif ((ap_const_boolean_1 = ap_condition_409)) then 
                    rescale_history_fu_136 <= engine1_control_stream_dout(58 downto 58);
                end if;
            end if; 
        end if;
    end process;

    update_phase_06_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1182_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    update_phase_06_fu_132 <= update_phase_10_fu_239_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    update_phase_06_fu_132 <= ap_const_lv16_0;
                end if;
            end if; 
        end if;
    end process;

    value_word_04_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    value_word_04_fu_128 <= ap_const_lv96_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    value_word_04_fu_128 <= ap_phi_mux_value_word_2_phi_fu_203_p4(127 downto 32);
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln1182_reg_514 <= icmp_ln1182_fu_233_p2;
                icmp_ln1182_reg_514_pp0_iter1_reg <= icmp_ln1182_reg_514;
                icmp_ln1188_reg_518 <= icmp_ln1188_fu_249_p2;
                icmp_ln1188_reg_518_pp0_iter1_reg <= icmp_ln1188_reg_518;
                icmp_ln1212_reg_522 <= icmp_ln1212_fu_255_p2;
                icmp_ln1212_reg_522_pp0_iter1_reg <= icmp_ln1212_reg_522;
                icmp_ln1235_reg_531 <= icmp_ln1235_fu_281_p2;
                icmp_ln1235_reg_531_pp0_iter1_reg <= icmp_ln1235_reg_531;
                trunc_ln_reg_526 <= ap_sig_allocacmp_update_phase(2 downto 1);
                trunc_ln_reg_526_pp0_iter1_reg <= trunc_ln_reg_526;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_value_word_1_reg_191 <= ap_phi_reg_pp0_iter0_value_word_1_reg_191;
                ap_phi_reg_pp0_iter1_value_word_2_reg_200 <= ap_phi_reg_pp0_iter0_value_word_2_reg_200;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1188_reg_518 = ap_const_lv1_1) and (icmp_ln1182_reg_514 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                value_shift_10_fu_156 <= engine1_control_stream_dout(39 downto 35);
                value_shift_8_fu_148 <= engine1_control_stream_dout(29 downto 25);
                value_shift_9_fu_152 <= engine1_control_stream_dout(34 downto 30);
                value_shift_fu_144 <= engine1_control_stream_dout(24 downto 20);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(engine1_control_stream_empty_n, ap_predicate_op39_read_state2, value0_engine1_stream_empty_n, ap_predicate_op42_read_state2, value1_engine1_stream_empty_n, ap_predicate_op54_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((ap_predicate_op54_read_state2 = ap_const_boolean_1) and (value1_engine1_stream_empty_n = ap_const_logic_0)) or ((ap_predicate_op42_read_state2 = ap_const_boolean_1) and (value0_engine1_stream_empty_n = ap_const_logic_0)) or ((ap_predicate_op39_read_state2 = ap_const_boolean_1) and (engine1_control_stream_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(engine1_phase_stream_full_n)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (engine1_phase_stream_full_n = ap_const_logic_0);
    end process;


    ap_condition_173_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_173 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_409_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln1182_reg_514, icmp_ln1188_reg_518)
    begin
                ap_condition_409 <= ((icmp_ln1188_reg_518 = ap_const_lv1_1) and (icmp_ln1182_reg_514 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1182_fu_233_p2)
    begin
        if (((icmp_ln1182_fu_233_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_value_word_1_phi_fu_194_p4_assign_proc : process(icmp_ln1182_reg_514_pp0_iter1_reg, icmp_ln1188_reg_518_pp0_iter1_reg, ap_phi_reg_pp0_iter2_value_word_1_reg_191, zext_ln1182_fu_383_p1)
    begin
        if (((icmp_ln1188_reg_518_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1182_reg_514_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_value_word_1_phi_fu_194_p4 <= zext_ln1182_fu_383_p1;
        else 
            ap_phi_mux_value_word_1_phi_fu_194_p4 <= ap_phi_reg_pp0_iter2_value_word_1_reg_191;
        end if; 
    end process;


    ap_phi_mux_value_word_2_phi_fu_203_p4_assign_proc : process(icmp_ln1182_reg_514_pp0_iter1_reg, icmp_ln1212_reg_522_pp0_iter1_reg, ap_phi_mux_value_word_1_phi_fu_194_p4, ap_phi_reg_pp0_iter2_value_word_2_reg_200)
    begin
        if (((icmp_ln1212_reg_522_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln1182_reg_514_pp0_iter1_reg = ap_const_lv1_0))) then 
            ap_phi_mux_value_word_2_phi_fu_203_p4 <= ap_phi_mux_value_word_1_phi_fu_194_p4;
        else 
            ap_phi_mux_value_word_2_phi_fu_203_p4 <= ap_phi_reg_pp0_iter2_value_word_2_reg_200;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_value_word_1_reg_191 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_value_word_2_reg_200 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op39_read_state2_assign_proc : process(icmp_ln1182_reg_514, icmp_ln1188_reg_518)
    begin
                ap_predicate_op39_read_state2 <= ((icmp_ln1188_reg_518 = ap_const_lv1_1) and (icmp_ln1182_reg_514 = ap_const_lv1_0));
    end process;


    ap_predicate_op42_read_state2_assign_proc : process(icmp_ln1182_reg_514, icmp_ln1188_reg_518)
    begin
                ap_predicate_op42_read_state2 <= ((icmp_ln1188_reg_518 = ap_const_lv1_1) and (icmp_ln1182_reg_514 = ap_const_lv1_0));
    end process;


    ap_predicate_op54_read_state2_assign_proc : process(icmp_ln1182_reg_514, icmp_ln1212_reg_522)
    begin
                ap_predicate_op54_read_state2 <= ((icmp_ln1212_reg_522 = ap_const_lv1_1) and (icmp_ln1182_reg_514 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_update_phase_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, update_phase_06_fu_132)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_update_phase <= ap_const_lv16_0;
        else 
            ap_sig_allocacmp_update_phase <= update_phase_06_fu_132;
        end if; 
    end process;


    engine1_control_stream_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, engine1_control_stream_empty_n, ap_predicate_op39_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op39_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            engine1_control_stream_blk_n <= engine1_control_stream_empty_n;
        else 
            engine1_control_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    engine1_control_stream_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op39_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op39_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            engine1_control_stream_read <= ap_const_logic_1;
        else 
            engine1_control_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    engine1_phase_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, engine1_phase_stream_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            engine1_phase_stream_blk_n <= engine1_phase_stream_full_n;
        else 
            engine1_phase_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    engine1_phase_stream_din <= ((((icmp_ln1235_reg_531_pp0_iter1_reg & rescale_history_fu_136) & empty_fu_140) & tmp_s_fu_420_p11) & packed_values_fu_406_p1);

    engine1_phase_stream_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            engine1_phase_stream_write <= ap_const_logic_1;
        else 
            engine1_phase_stream_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1182_fu_233_p2 <= "1" when (ap_sig_allocacmp_update_phase = update_phase_count) else "0";
    icmp_ln1188_fu_249_p2 <= "1" when (phase_fu_245_p1 = ap_const_lv3_0) else "0";
    icmp_ln1212_fu_255_p2 <= "1" when (phase_fu_245_p1 = ap_const_lv3_4) else "0";
    icmp_ln1235_fu_281_p2 <= "0" when (tmp_173_fu_271_p4 = ap_const_lv13_0) else "1";
    packed_values_fu_406_p1 <= ap_phi_mux_value_word_2_phi_fu_203_p4(32 - 1 downto 0);
    phase_fu_245_p1 <= ap_sig_allocacmp_update_phase(3 - 1 downto 0);
    tmp_173_fu_271_p4 <= ap_sig_allocacmp_update_phase(15 downto 3);
    tmp_s_fu_420_p9 <= "XXXXX";
    update_phase_10_fu_239_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_update_phase) + unsigned(ap_const_lv16_1));

    value0_engine1_stream_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, value0_engine1_stream_empty_n, ap_predicate_op42_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op42_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            value0_engine1_stream_blk_n <= value0_engine1_stream_empty_n;
        else 
            value0_engine1_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    value0_engine1_stream_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op42_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op42_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            value0_engine1_stream_read <= ap_const_logic_1;
        else 
            value0_engine1_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    value1_engine1_stream_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, value1_engine1_stream_empty_n, ap_predicate_op54_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op54_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            value1_engine1_stream_blk_n <= value1_engine1_stream_empty_n;
        else 
            value1_engine1_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    value1_engine1_stream_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op54_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op54_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            value1_engine1_stream_read <= ap_const_logic_1;
        else 
            value1_engine1_stream_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1182_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(value_word_04_fu_128),128));
end behav;
