-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity int4_decoder_token_controller_swiftkv_update_values_and_quantize_Pipeline_attention_quantize_reverse_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    attention_group_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    attention_group_ce0 : OUT STD_LOGIC;
    attention_group_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    inverse_scale : IN STD_LOGIC_VECTOR (31 downto 0);
    quantized_word_out : OUT STD_LOGIC_VECTOR (479 downto 0);
    quantized_word_out_ap_vld : OUT STD_LOGIC;
    grp_fu_351_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_351_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_351_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_351_p_ce : OUT STD_LOGIC;
    grp_fu_361_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_361_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_361_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_361_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_361_p_ce : OUT STD_LOGIC );
end;


architecture behav of int4_decoder_token_controller_swiftkv_update_values_and_quantize_Pipeline_attention_quantize_reverse_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv480_lc_1 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv6_1F : STD_LOGIC_VECTOR (5 downto 0) := "011111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_467FFC00 : STD_LOGIC_VECTOR (31 downto 0) := "01000110011111111111110000000000";
    constant ap_const_lv32_C67FFC00 : STD_LOGIC_VECTOR (31 downto 0) := "11000110011111111111110000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_FFFFFFE8 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111101000";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_FFFFFFE7 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111100111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv8_F : STD_LOGIC_VECTOR (7 downto 0) := "00001111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_3F000000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111000000000000000000000000";
    constant ap_const_lv32_BF000000 : STD_LOGIC_VECTOR (31 downto 0) := "10111111000000000000000000000000";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_fu_202_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_reg_822 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_822_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal attention_group_load_reg_831 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_837 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_837_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_837_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1547_fu_234_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1547_reg_843 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1547_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1547_reg_848 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1547_reg_848_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1547_fu_245_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1547_reg_853 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1547_fu_268_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1547_reg_859 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1547_reg_859_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1547_fu_278_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1547_reg_864 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_reg_870 : STD_LOGIC_VECTOR (30 downto 0);
    signal lshr_ln1547_2_fu_308_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln1547_2_reg_875 : STD_LOGIC_VECTOR (31 downto 0);
    signal bit_select27_i_i_fu_314_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal bit_select27_i_i_reg_880 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1547_1_fu_322_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1547_1_reg_885 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1547_2_fu_328_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1547_2_reg_890 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln1547_1_reg_895 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_5_reg_900 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1547_3_fu_497_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1547_3_reg_905 : STD_LOGIC_VECTOR (31 downto 0);
    signal scaled_reg_910 : STD_LOGIC_VECTOR (31 downto 0);
    signal scaled_reg_910_pp0_iter9_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal scaled_reg_910_pp0_iter10_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1549_fu_545_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1549_reg_917 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_166_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal rounded_reg_922 : STD_LOGIC_VECTOR (31 downto 0);
    signal rounded_reg_922_pp0_iter18_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal rounded_1_fu_594_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal rounded_1_reg_929 : STD_LOGIC_VECTOR (31 downto 0);
    signal rounded_1_reg_929_pp0_iter20_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_sign_reg_935 : STD_LOGIC_VECTOR (0 downto 0);
    signal xs_sign_reg_935_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal xs_exp_reg_940 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln342_fu_668_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln342_reg_946 : STD_LOGIC_VECTOR (22 downto 0);
    signal val_fu_759_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal val_reg_951 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln1543_fu_210_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal quantized_word_fu_132 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal quantized_word_1_fu_785_p3 : STD_LOGIC_VECTOR (479 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal lane_fu_136 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln1544_fu_215_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_lane_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_s_fu_250_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_260_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln1547_1_fu_272_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1547_1_fu_294_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln1547_4_fu_298_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln1547_5_fu_304_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal and_ln1547_2_fu_339_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1547_1_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1547_2_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_355_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1547_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1547_1_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1547_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1547_fu_373_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln1547_fu_387_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1547_1_fu_395_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1547_2_fu_404_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln1547_3_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln1547_fu_398_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln1547_fu_407_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln1_fu_379_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln1547_1_fu_413_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1547_3_fu_421_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1547_2_fu_425_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln1547_3_fu_459_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1547_2_fu_452_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1547_3_fu_464_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1547_4_fu_449_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_6_fu_470_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pi_assign_1_fu_477_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal LD_fu_489_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln766_fu_493_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln1549_fu_504_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_507_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1549_fu_517_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln1549_1_fu_527_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1549_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1549_fu_533_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1549_fu_539_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln1550_fu_553_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_fu_556_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1550_fu_566_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln1550_1_fu_576_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1550_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1550_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1550_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln1553_fu_601_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_fu_604_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1553_fu_614_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln1553_1_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1553_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1553_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1553_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_fu_642_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mantissa_fu_672_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln317_fu_685_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_fu_688_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_fu_702_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_694_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln18_fu_707_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_fu_711_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_1_fu_719_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_681_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_fu_723_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_fu_727_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_fu_733_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_15_fu_739_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_16_fu_749_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal result_1_fu_770_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln1559_fu_781_p1 : STD_LOGIC_VECTOR (464 downto 0);
    signal quantized_fu_775_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter20_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter21_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter22_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component int4_decoder_token_controller_fadd_32ns_32ns_32_7_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component int4_decoder_token_controller_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component int4_decoder_token_controller_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component int4_decoder_token_controller_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fadd_32ns_32ns_32_7_full_dsp_1_U720 : component int4_decoder_token_controller_fadd_32ns_32ns_32_7_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => scaled_reg_910_pp0_iter10_reg,
        din1 => select_ln1549_reg_917,
        ce => ap_const_logic_1,
        dout => grp_fu_166_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U723 : component int4_decoder_token_controller_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => rounded_reg_922,
        din1 => ap_const_lv32_467FFC00,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_179_p2);

    fcmp_32ns_32ns_1_2_no_dsp_1_U724 : component int4_decoder_token_controller_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => rounded_1_reg_929,
        din1 => ap_const_lv32_C67FFC00,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_4,
        dout => grp_fu_184_p2);

    flow_control_loop_pipe_sequential_init_U : component int4_decoder_token_controller_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter22_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    lane_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (tmp_fu_202_p3 = ap_const_lv1_0))) then 
                    lane_fu_136 <= add_ln1544_fu_215_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    lane_fu_136 <= ap_const_lv6_1F;
                end if;
            end if; 
        end if;
    end process;

    quantized_word_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    quantized_word_fu_132 <= ap_const_lv480_lc_1;
                elsif ((ap_enable_reg_pp0_iter23 = ap_const_logic_1)) then 
                    quantized_word_fu_132 <= quantized_word_1_fu_785_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln1547_1_reg_885 <= add_ln1547_1_fu_322_p2;
                add_ln1547_reg_864 <= add_ln1547_fu_278_p2;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
                ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
                ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                bit_select27_i_i_reg_880 <= bit_select27_i_i_fu_314_p3;
                icmp_ln1547_reg_848 <= icmp_ln1547_fu_240_p2;
                icmp_ln1547_reg_848_pp0_iter3_reg <= icmp_ln1547_reg_848;
                lshr_ln1547_1_reg_895 <= add_ln1547_2_fu_425_p2(63 downto 1);
                lshr_ln1547_2_reg_875 <= lshr_ln1547_2_fu_308_p2;
                rounded_1_reg_929 <= rounded_1_fu_594_p3;
                rounded_1_reg_929_pp0_iter20_reg <= rounded_1_reg_929;
                rounded_reg_922 <= grp_fu_166_p2;
                rounded_reg_922_pp0_iter18_reg <= rounded_reg_922;
                scaled_reg_910 <= grp_fu_351_p_dout0;
                scaled_reg_910_pp0_iter10_reg <= scaled_reg_910_pp0_iter9_reg;
                scaled_reg_910_pp0_iter9_reg <= scaled_reg_910;
                select_ln1547_3_reg_905 <= select_ln1547_3_fu_497_p3;
                select_ln1547_reg_853 <= select_ln1547_fu_245_p3;
                    select_ln1549_reg_917(31) <= select_ln1549_fu_545_p3(31);
                sub_ln1547_2_reg_890 <= sub_ln1547_2_fu_328_p2;
                tmp_1_reg_837_pp0_iter2_reg <= tmp_1_reg_837;
                tmp_1_reg_837_pp0_iter3_reg <= tmp_1_reg_837_pp0_iter2_reg;
                tmp_3_reg_870 <= add_ln1547_fu_278_p2(31 downto 1);
                tmp_5_reg_900 <= add_ln1547_2_fu_425_p2(25 downto 25);
                tmp_reg_822_pp0_iter10_reg <= tmp_reg_822_pp0_iter9_reg;
                tmp_reg_822_pp0_iter11_reg <= tmp_reg_822_pp0_iter10_reg;
                tmp_reg_822_pp0_iter12_reg <= tmp_reg_822_pp0_iter11_reg;
                tmp_reg_822_pp0_iter13_reg <= tmp_reg_822_pp0_iter12_reg;
                tmp_reg_822_pp0_iter14_reg <= tmp_reg_822_pp0_iter13_reg;
                tmp_reg_822_pp0_iter15_reg <= tmp_reg_822_pp0_iter14_reg;
                tmp_reg_822_pp0_iter16_reg <= tmp_reg_822_pp0_iter15_reg;
                tmp_reg_822_pp0_iter17_reg <= tmp_reg_822_pp0_iter16_reg;
                tmp_reg_822_pp0_iter18_reg <= tmp_reg_822_pp0_iter17_reg;
                tmp_reg_822_pp0_iter19_reg <= tmp_reg_822_pp0_iter18_reg;
                tmp_reg_822_pp0_iter20_reg <= tmp_reg_822_pp0_iter19_reg;
                tmp_reg_822_pp0_iter21_reg <= tmp_reg_822_pp0_iter20_reg;
                tmp_reg_822_pp0_iter2_reg <= tmp_reg_822_pp0_iter1_reg;
                tmp_reg_822_pp0_iter3_reg <= tmp_reg_822_pp0_iter2_reg;
                tmp_reg_822_pp0_iter4_reg <= tmp_reg_822_pp0_iter3_reg;
                tmp_reg_822_pp0_iter5_reg <= tmp_reg_822_pp0_iter4_reg;
                tmp_reg_822_pp0_iter6_reg <= tmp_reg_822_pp0_iter5_reg;
                tmp_reg_822_pp0_iter7_reg <= tmp_reg_822_pp0_iter6_reg;
                tmp_reg_822_pp0_iter8_reg <= tmp_reg_822_pp0_iter7_reg;
                tmp_reg_822_pp0_iter9_reg <= tmp_reg_822_pp0_iter8_reg;
                trunc_ln1547_reg_859 <= trunc_ln1547_fu_268_p1;
                trunc_ln1547_reg_859_pp0_iter3_reg <= trunc_ln1547_reg_859;
                trunc_ln342_reg_946 <= trunc_ln342_fu_668_p1;
                val_reg_951 <= val_fu_759_p3;
                xs_exp_reg_940 <= data_fu_642_p3(30 downto 23);
                xs_sign_reg_935 <= data_fu_642_p3(31 downto 31);
                xs_sign_reg_935_pp0_iter22_reg <= xs_sign_reg_935;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                attention_group_load_reg_831 <= attention_group_q0;
                sub_ln1547_reg_843 <= sub_ln1547_fu_234_p2;
                tmp_1_reg_837 <= attention_group_q0(31 downto 31);
                tmp_reg_822 <= ap_sig_allocacmp_lane_1(5 downto 5);
                tmp_reg_822_pp0_iter1_reg <= tmp_reg_822;
            end if;
        end if;
    end process;
    select_ln1549_reg_917(30 downto 0) <= "0111111000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    LD_fu_489_p1 <= pi_assign_1_fu_477_p5(32 - 1 downto 0);
    add_ln1544_fu_215_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_lane_1) + unsigned(ap_const_lv6_3F));
    add_ln1547_1_fu_322_p2 <= std_logic_vector(unsigned(sub_ln1547_1_fu_272_p2) + unsigned(ap_const_lv32_FFFFFFE7));
    add_ln1547_2_fu_425_p2 <= std_logic_vector(unsigned(select_ln1547_1_fu_413_p3) + unsigned(zext_ln1547_3_fu_421_p1));
    add_ln1547_3_fu_464_p2 <= std_logic_vector(unsigned(sub_ln1547_3_fu_459_p2) + unsigned(select_ln1547_2_fu_452_p3));
    add_ln1547_fu_278_p2 <= std_logic_vector(unsigned(sub_ln1547_1_fu_272_p2) + unsigned(ap_const_lv32_FFFFFFE8));
    add_ln317_fu_688_p2 <= std_logic_vector(unsigned(zext_ln317_fu_685_p1) + unsigned(ap_const_lv9_181));
    and_ln1547_1_fu_368_p2 <= (xor_ln1547_fu_362_p2 and bit_select27_i_i_reg_880);
    and_ln1547_2_fu_339_p2 <= (select_ln1547_reg_853 and lshr_ln1547_2_reg_875);
    and_ln1547_fu_349_p2 <= (icmp_ln1547_2_fu_343_p2 and icmp_ln1547_1_fu_334_p2);
    and_ln1549_fu_539_p2 <= (or_ln1549_fu_533_p2 and grp_fu_361_p_dout0);
    and_ln1550_fu_588_p2 <= (or_ln1550_fu_582_p2 and grp_fu_179_p2);
    and_ln1553_fu_636_p2 <= (or_ln1553_fu_630_p2 and grp_fu_184_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, tmp_fu_202_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_fu_202_p3 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter22_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter22_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23)
    begin
        if (((ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) 
    and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_lane_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, lane_fu_136)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_lane_1 <= ap_const_lv6_1F;
        else 
            ap_sig_allocacmp_lane_1 <= lane_fu_136;
        end if; 
    end process;

    attention_group_address0 <= zext_ln1543_fu_210_p1(5 - 1 downto 0);

    attention_group_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            attention_group_ce0 <= ap_const_logic_1;
        else 
            attention_group_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    bit_select27_i_i_fu_314_p3 <= select_ln1547_fu_245_p3(to_integer(unsigned(add_ln1547_fu_278_p2)) downto to_integer(unsigned(add_ln1547_fu_278_p2))) when (to_integer(unsigned(add_ln1547_fu_278_p2)) >= 0 and to_integer(unsigned(add_ln1547_fu_278_p2)) <=31) else "-";
    bitcast_ln1549_fu_504_p1 <= scaled_reg_910_pp0_iter9_reg;
    bitcast_ln1550_fu_553_p1 <= rounded_reg_922_pp0_iter18_reg;
    bitcast_ln1553_fu_601_p1 <= rounded_1_reg_929_pp0_iter20_reg;
    bitcast_ln766_fu_493_p1 <= LD_fu_489_p1;
    data_fu_642_p3 <= 
        ap_const_lv32_C67FFC00 when (and_ln1553_fu_636_p2(0) = '1') else 
        bitcast_ln1553_fu_601_p1;
    grp_fu_351_p_ce <= ap_const_logic_1;
    grp_fu_351_p_din0 <= select_ln1547_3_reg_905;
    grp_fu_351_p_din1 <= inverse_scale;
    grp_fu_361_p_ce <= ap_const_logic_1;
    grp_fu_361_p_din0 <= scaled_reg_910;
    grp_fu_361_p_din1 <= ap_const_lv32_0;
    grp_fu_361_p_opcode <= ap_const_lv5_3;
    icmp_ln1547_1_fu_334_p2 <= "1" when (signed(tmp_3_reg_870) > signed(ap_const_lv31_0)) else "0";
    icmp_ln1547_2_fu_343_p2 <= "0" when (and_ln1547_2_fu_339_p2 = ap_const_lv32_0) else "1";
    icmp_ln1547_3_fu_390_p2 <= "1" when (signed(add_ln1547_reg_864) > signed(ap_const_lv32_0)) else "0";
    icmp_ln1547_fu_240_p2 <= "1" when (attention_group_load_reg_831 = ap_const_lv32_0) else "0";
    icmp_ln1549_1_fu_527_p2 <= "1" when (trunc_ln1549_fu_517_p1 = ap_const_lv23_0) else "0";
    icmp_ln1549_fu_521_p2 <= "0" when (tmp_7_fu_507_p4 = ap_const_lv8_FF) else "1";
    icmp_ln1550_1_fu_576_p2 <= "1" when (trunc_ln1550_fu_566_p1 = ap_const_lv23_0) else "0";
    icmp_ln1550_fu_570_p2 <= "0" when (tmp_9_fu_556_p4 = ap_const_lv8_FF) else "1";
    icmp_ln1553_1_fu_624_p2 <= "1" when (trunc_ln1553_fu_614_p1 = ap_const_lv23_0) else "0";
    icmp_ln1553_fu_618_p2 <= "0" when (tmp_11_fu_604_p4 = ap_const_lv8_FF) else "1";
    lshr_ln1547_2_fu_308_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv32_FFFFFFFF),to_integer(unsigned('0' & zext_ln1547_5_fu_304_p1(31-1 downto 0)))));
    lshr_ln1547_fu_398_p2 <= std_logic_vector(shift_right(unsigned(zext_ln1547_fu_387_p1),to_integer(unsigned('0' & zext_ln1547_1_fu_395_p1(31-1 downto 0)))));
    lshr_ln18_fu_727_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_681_p1),to_integer(unsigned('0' & zext_ln18_fu_723_p1(31-1 downto 0)))));
    mantissa_fu_672_p4 <= ((ap_const_lv1_1 & trunc_ln342_reg_946) & ap_const_lv1_0);
    or_ln1547_fu_373_p2 <= (and_ln1547_fu_349_p2 or and_ln1547_1_fu_368_p2);
    or_ln1549_fu_533_p2 <= (icmp_ln1549_fu_521_p2 or icmp_ln1549_1_fu_527_p2);
    or_ln1550_fu_582_p2 <= (icmp_ln1550_fu_570_p2 or icmp_ln1550_1_fu_576_p2);
    or_ln1553_fu_630_p2 <= (icmp_ln1553_fu_618_p2 or icmp_ln1553_1_fu_624_p2);
    or_ln1_fu_379_p3 <= (ap_const_lv1_0 & or_ln1547_fu_373_p2);
    pi_assign_1_fu_477_p5 <= (zext_ln1547_4_fu_449_p1(63 downto 32) & tmp_6_fu_470_p3 & zext_ln1547_4_fu_449_p1(22 downto 0));
    quantized_fu_775_p3 <= 
        result_1_fu_770_p2 when (xs_sign_reg_935_pp0_iter22_reg(0) = '1') else 
        val_reg_951;
    quantized_word_1_fu_785_p3 <= (trunc_ln1559_fu_781_p1 & quantized_fu_775_p3);
    quantized_word_out <= quantized_word_fu_132;

    quantized_word_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, tmp_reg_822_pp0_iter21_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_822_pp0_iter21_reg = ap_const_lv1_1))) then 
            quantized_word_out_ap_vld <= ap_const_logic_1;
        else 
            quantized_word_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    result_1_fu_770_p2 <= std_logic_vector(unsigned(ap_const_lv15_0) - unsigned(val_reg_951));
    rounded_1_fu_594_p3 <= 
        ap_const_lv32_467FFC00 when (and_ln1550_fu_588_p2(0) = '1') else 
        rounded_reg_922_pp0_iter18_reg;
    select_ln1547_1_fu_413_p3 <= 
        lshr_ln1547_fu_398_p2 when (icmp_ln1547_3_fu_390_p2(0) = '1') else 
        shl_ln1547_fu_407_p2;
    select_ln1547_2_fu_452_p3 <= 
        ap_const_lv8_7F when (tmp_5_reg_900(0) = '1') else 
        ap_const_lv8_7E;
    select_ln1547_3_fu_497_p3 <= 
        ap_const_lv32_0 when (icmp_ln1547_reg_848_pp0_iter3_reg(0) = '1') else 
        bitcast_ln766_fu_493_p1;
    select_ln1547_fu_245_p3 <= 
        sub_ln1547_reg_843 when (tmp_1_reg_837(0) = '1') else 
        attention_group_load_reg_831;
    select_ln1549_fu_545_p3 <= 
        ap_const_lv32_3F000000 when (and_ln1549_fu_539_p2(0) = '1') else 
        ap_const_lv32_BF000000;
    select_ln18_fu_711_p3 <= 
        sext_ln18_fu_707_p1 when (tmp_14_fu_694_p3(0) = '1') else 
        add_ln317_fu_688_p2;
        sext_ln18_1_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_fu_711_p3),32));

        sext_ln18_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_fu_702_p2),9));

    shl_ln1547_fu_407_p2 <= std_logic_vector(shift_left(unsigned(zext_ln1547_fu_387_p1),to_integer(unsigned('0' & zext_ln1547_2_fu_404_p1(31-1 downto 0)))));
    shl_ln18_fu_733_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_681_p1),to_integer(unsigned('0' & zext_ln18_fu_723_p1(31-1 downto 0)))));
    sub_ln1547_1_fu_272_p2 <= std_logic_vector(unsigned(ap_const_lv32_20) - unsigned(tmp_2_fu_260_p3));
    sub_ln1547_2_fu_328_p2 <= std_logic_vector(unsigned(ap_const_lv32_19) - unsigned(sub_ln1547_1_fu_272_p2));
    sub_ln1547_3_fu_459_p2 <= std_logic_vector(unsigned(ap_const_lv8_F) - unsigned(trunc_ln1547_reg_859_pp0_iter3_reg));
    sub_ln1547_4_fu_298_p2 <= std_logic_vector(signed(ap_const_lv5_19) - signed(trunc_ln1547_1_fu_294_p1));
    sub_ln1547_fu_234_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(attention_group_q0));
    sub_ln18_fu_702_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_reg_940));
    tmp_11_fu_604_p4 <= bitcast_ln1553_fu_601_p1(30 downto 23);
    tmp_14_fu_694_p3 <= add_ln317_fu_688_p2(8 downto 8);
    tmp_15_fu_739_p4 <= lshr_ln18_fu_727_p2(38 downto 24);
    tmp_16_fu_749_p4 <= shl_ln18_fu_733_p2(38 downto 24);
    
    tmp_2_fu_260_p3_proc : process(tmp_s_fu_250_p4)
    begin
        tmp_2_fu_260_p3 <= std_logic_vector(to_unsigned(32, 32));
        for i in 0 to 32 - 1 loop
            if tmp_s_fu_250_p4(i) = '1' then
                tmp_2_fu_260_p3 <= std_logic_vector(to_unsigned(i,32));
                exit;
            end if;
        end loop;
    end process;

    tmp_4_fu_355_p3 <= add_ln1547_reg_864(31 downto 31);
    tmp_6_fu_470_p3 <= (tmp_1_reg_837_pp0_iter3_reg & add_ln1547_3_fu_464_p2);
    tmp_7_fu_507_p4 <= bitcast_ln1549_fu_504_p1(30 downto 23);
    tmp_9_fu_556_p4 <= bitcast_ln1550_fu_553_p1(30 downto 23);
    tmp_fu_202_p3 <= ap_sig_allocacmp_lane_1(5 downto 5);
    
    tmp_s_fu_250_p4_proc : process(select_ln1547_fu_245_p3)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_s_fu_250_p4_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_1F(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        v0_cpy := select_ln1547_fu_245_p3;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_1F(5-1 downto 0)));
            for tmp_s_fu_250_p4_i in 0 to 32-1 loop
                v0_cpy(tmp_s_fu_250_p4_i) := select_ln1547_fu_245_p3(32-1-tmp_s_fu_250_p4_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        tmp_s_fu_250_p4 <= resvalue(32-1 downto 0);
    end process;

    trunc_ln1547_1_fu_294_p1 <= sub_ln1547_1_fu_272_p2(5 - 1 downto 0);
    trunc_ln1547_fu_268_p1 <= tmp_2_fu_260_p3(8 - 1 downto 0);
    trunc_ln1549_fu_517_p1 <= bitcast_ln1549_fu_504_p1(23 - 1 downto 0);
    trunc_ln1550_fu_566_p1 <= bitcast_ln1550_fu_553_p1(23 - 1 downto 0);
    trunc_ln1553_fu_614_p1 <= bitcast_ln1553_fu_601_p1(23 - 1 downto 0);
    trunc_ln1559_fu_781_p1 <= quantized_word_fu_132(465 - 1 downto 0);
    trunc_ln342_fu_668_p1 <= data_fu_642_p3(23 - 1 downto 0);
    val_fu_759_p3 <= 
        tmp_15_fu_739_p4 when (tmp_14_fu_694_p3(0) = '1') else 
        tmp_16_fu_749_p4;
    xor_ln1547_fu_362_p2 <= (tmp_4_fu_355_p3 xor ap_const_lv1_1);
    zext_ln1543_fu_210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_lane_1),64));
    zext_ln1547_1_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1547_1_reg_885),64));
    zext_ln1547_2_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln1547_2_reg_890),64));
    zext_ln1547_3_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln1_fu_379_p3),64));
    zext_ln1547_4_fu_449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1547_1_reg_895),64));
    zext_ln1547_5_fu_304_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln1547_4_fu_298_p2),32));
    zext_ln1547_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln1547_reg_853),64));
    zext_ln15_fu_681_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_672_p4),79));
    zext_ln18_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_1_fu_719_p1),79));
    zext_ln317_fu_685_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_reg_940),9));
end behav;
